import { cited } from "../citations.js";
import type { LanguageGuide } from "../types.js";

const relatedLanguages = [
  { name: "Argobba", relationship: "Closest documented relative", explanation: cited("Argobba and Amharic form a particularly close pairing within South Ethio-Semitic. Similarity does not make Argobba a dialect: it has its own communities and varieties, and language shift toward Amharic has placed it under severe pressure. For learners, comparison is most useful as evidence that familiar Amharic forms have a family history beyond the standard language.", "glottolog", "oxford-handbook") },
  { name: "Tigrinya", relationship: "Fellow Ethio-Semitic language", explanation: cited("Tigrinya shares Semitic structures and the Ethiopic script, so an Amharic reader will recognize many signs and some roots. Its sound changes, vocabulary, verbal system, and regional standards are nevertheless distinct. Script familiarity provides a head start, not automatic comprehension.", "glottolog", "wiki-amharic") },
  { name: "Geʽez", relationship: "Classical and liturgical relative", explanation: cited("Geʽez is no longer an ordinary community vernacular, but remains a liturgical and scholarly language and supplies Amharic with script tradition, learned vocabulary, names, and textual genres. Amharic did not simply descend from the modern liturgical register; both belong inside a longer, branching Ethio-Semitic history.", "unicode-ethiopic", "oxford-handbook") },
  { name: "Arabic", slug: "arabic", relationship: "More distant Semitic relative and contact language", explanation: cited("Arabic and Amharic share a remote Semitic inheritance, including recognizable root-based word formation, while long Red Sea, Islamic, commercial, and literary connections added contact vocabulary. Their scripts and most everyday words differ, and neither is a variety of the other.", "glottolog", "oxford-handbook") },
  { name: "Oromo", relationship: "Cushitic contact language", explanation: cited("Oromo is Afro-Asiatic but Cushitic rather than Semitic. Centuries of multilingual life have produced borrowing and structural convergence in both directions. Today many Ethiopians use both languages, so Oromo-Amharic interaction is a living social relationship, not merely a historical footnote.", "oxford-handbook", "constitution") }
] satisfies LanguageGuide["relationships"]["languages"];

export const amharicGuide = {
  slug: "amharic",
  name: "Amharic",
  autonym: "አማርኛ",
  status: "published",
  publishedAt: "2026-07-09",
  summary: "Amharic joins a many-centuries-old Ethiopian writing tradition to quick modern conversation, intricate Semitic verbs, expressive politeness, journalism, music, film, literature, and the everyday life of a multilingual country and diaspora.",
  family: "Afro-Asiatic, Semitic, Ethio-Semitic",
  macroRegion: "Ethiopia and global Ethiopian diasporas",
  primaryScript: "Ethiopic (Geʽez) script",
  difficultyLabel: "Very demanding",
  learnerHook: "Reading ቡና as buna, hearing whether a consonant is held double, and noticing that one verb can name its subject and object turn an unfamiliar wall of signs into a language whose internal clues are everywhere.",
  hero: { imageAlt: "Amharic printed in Ethiopic fidel beside a handwritten note and a cup of coffee.", callToActionLabel: "Explore Amharic in use" },
  classification: "South Ethio-Semitic language, closely related to Argobba",
  speakerCommunity: "Amharic is a first language for large communities in Ethiopia and a widely learned additional language used across regional, ethnic, and religious lines. It is the federal government's working language and has extensive roles in national media, publishing, popular entertainment, urban commerce, and communication among people with different home languages. Those functions should not be collapsed into the claim that it is every Ethiopian's mother tongue or the country's only important language. Ethiopia's constitution gives equal state recognition to all Ethiopian languages and allows member states to determine their own working languages. Amharic is also heard in diasporas in North America, Europe, the Middle East, Africa, and Australia, where heritage speakers may understand family conversation more easily than they read fidel or command formal vocabulary.",
  facts: [
    { label: "Family", value: "Afro-Asiatic · Semitic · Ethio-Semitic · South" },
    { label: "Closest relative", value: "Argobba" },
    { label: "Writing", value: "Left-to-right Ethiopic abugida, commonly called fidel" },
    { label: "Federal role", value: "Working language of Ethiopia's federal government" },
    { label: "Core order", value: "Generally subject–object–verb, with modifiers before nouns" },
    { label: "Sound cues", value: "Ejectives and contrastive consonant length" }
  ],
  learnerOverview: "Begin with speech and fidel together. The script is large, but it is not a random inventory of hundreds of unrelated pictures: signs are arranged in families, traditionally called orders, whose changed shapes pair a consonant with a vowel. Learn a row through words and audio rather than reciting its seven forms in isolation. At the same time, train three listening contrasts that romanization routinely hides: plain versus ejective consonants, single versus geminated or long consonants, and the different central vowels often written e or ə in scholarly transcription. Amharic grammar becomes less forbidding when complete verbs are treated as buildable objects. A form can include negation, a lexical root, tense/aspect, subject agreement, an object suffix, and a final marker. Save it inside a sentence and color the pieces. Use a reliable course or tutor for production because ordinary Latin spellings vary wildly. The most productive early cultural habit is to follow one recurring voice—a cooking presenter, interview program, series, radio host, or relative—while reading short captions. Discover Discomfort's guide to less-commonly taught languages recommends combining older institutional materials with current tutors and community media; that mixed strategy fits Amharic unusually well. Excellent reference grammars exist, while polished beginner ecosystems and searchable subtitles remain less abundant than for global commercial languages.",
  origins: {
    overview: cited("Amharic belongs to the South Ethio-Semitic group within the Semitic branch of Afro-Asiatic. Its history unfolded in a region where Semitic, Cushitic, Omotic, and Nilo-Saharan languages have long met. The neat family-tree statement is therefore only a beginning. Amharic grammar retains Semitic root-and-pattern resources, while centuries of contact within Ethiopia shaped sounds, constructions, discourse habits, and vocabulary. Written evidence becomes substantial in the early modern period, although Amharic was spoken much earlier. Geʽez held prestige in church, scholarship, and royal writing; Amharic increasingly occupied courtly, administrative, literary, and later mass-public domains. It is safer to picture overlapping languages and registers than a single moment when Amharic abruptly replaced Geʽez.", "glottolog", "oxford-handbook", "wiki-amharic"),
    timeline: [
      { period: "First millennium CE", event: cited("Geʽez supported a major manuscript and inscriptional tradition and the Ethiopic script developed its consonant-vowel organization. The script later expanded for sounds needed by Amharic and other Ethiopian and Eritrean languages.", "unicode-ethiopic", "w3c-ethiopic") },
      { period: "Medieval centuries", event: cited("South Ethio-Semitic varieties developed amid sustained interaction with Cushitic languages in the Ethiopian highlands. Amharic's precise early geography and subgrouping have been debated, so confident one-line origin legends should be treated cautiously.", "oxford-handbook", "glottolog") },
      { period: "14th–17th centuries", event: cited("Amharic appears in songs, praise poetry, royal and missionary records, and mixed-language texts while Geʽez remains central to formal literary and ecclesiastical life. Spoken use was broader than the surviving written record can show.", "wiki-amharic", "oxford-handbook") },
      { period: "19th–early 20th centuries", event: cited("Expansion of the Ethiopian state greatly widened Amharic's administrative and educational reach. That history created access and a shared lingua franca for many people, but also coercion, unequal opportunity, and language shift for others; serious accounts must hold these experiences together.", "oxford-handbook", "language-policy") },
      { period: "1995 constitutional order", event: cited("The federal constitution declared equal state recognition for all Ethiopian languages, designated Amharic the federal government's working language, and authorized member states to choose their own working languages.", "constitution", "language-policy") },
      { period: "Digital present", event: cited("Unicode encoding, Ethiopic keyboards, web publishing, social media, and new speech and text datasets have widened Amharic's digital presence. Technical support is improving, though fonts, line breaking, search, spelling variation, and language-technology coverage remain uneven.", "unicode-ethiopic", "w3c-ethiopic", "caco") }
    ],
    contactHistory: cited("Amharic's neighbors are visible in more than loanword lists. Long interaction with Agaw languages, Oromo, Somali, Gurage languages, Tigrinya, and many other Ethiopian languages belongs to the formation of regional speech and multilingual repertoires. Geʽez supplied a deep learned, religious, and literary layer. Arabic entered through religious scholarship, trade, and wider Red Sea networks; Italian left words associated with occupation, urban life, machinery, and food; English now dominates much higher-education, technology, and international vocabulary. Borrowings become Amharic material: speakers fit them into fidel, assign them morphology, shorten them, and joke with them. Attributing every shared feature to one conquest or one donor language usually oversimplifies a long contact zone.", "oxford-handbook", "wiki-amharic"),
    standardization: cited("Contemporary formal Amharic is centered on Addis Ababa usage and reproduced through education, federal institutions, publishing, and broadcasting. Standardization has never made spelling perfectly phonetic. Historically distinct consonant series have merged in much modern pronunciation but survive in conventional spellings, and gemination is ordinarily not written. Editors also vary over compounds, punctuation, and newer technical terms. The standard opens national institutions and a large media world, yet it coexists with regional varieties and with the rights and expanding public functions of other Ethiopian languages.", "w3c-ethiopic", "dialects", "constitution")
  },
  variants: {
    overview: cited("Learner materials often present one Addis Ababa-centered standard. Research commonly distinguishes regional centers associated with Addis Ababa, Shewa, Gojjam, Gondar, and Wollo, while warning that actual variation also follows migration, age, class, education, multilingualism, religion, and neighborhood. A speaker can shift toward broadcast forms in a formal interview and toward family features at home. Diaspora Amharic adds new contact settings and heritage profiles. These are not progressively worse copies of a capital norm.", "dialects", "ldc-amharic"),
    items: [
      { name: "Addis Ababa-centered standard", note: cited("The main target in schools, national broadcasting, and most courses. Addis Ababa itself is intensely multilingual, so its daily Amharic includes social and contact variation beyond a single announcer voice.", "ldc-amharic", "dialects") },
      { name: "Shewa, Gojjam, Gondar, and Wollo varieties", note: cited("These labels point to established regional patterns in pronunciation, forms, and vocabulary, not sealed boxes. Movement and intermarriage blur boundaries, and detailed descriptions remain uneven.", "ldc-amharic", "dialects") },
      { name: "Second-language Amharic", note: cited("Millions use Amharic alongside Oromo, Somali, Tigrinya, Wolaytta, Sidama, Afar, Gurage languages, and many others. Contact accents and constructions are normal products of multilingual communication, not evidence that their speakers lack an identity or intellect.", "constitution", "oxford-handbook") },
      { name: "Diaspora and heritage Amharic", note: cited("Families may mix Amharic with English, Arabic, Hebrew, Italian, Swedish, or other community languages. Some heritage speakers possess rich household listening skills but limited formal literacy; others learn Amharic later to reconnect with relatives, music, faith, or history.", "dd-less-common") },
      { name: "Liturgical and literary Geʽez influence", note: cited("Geʽez vocabulary, quotations, and styles appear in religious and elevated contexts, but Geʽez is a related language, not an unusually formal Amharic dialect. Reading it is an additional specialization.", "unicode-ethiopic", "oxford-handbook") }
    ]
  },
  pronunciation: {
    overview: cited("The script gives vowels more help than Arabic or Hebrew writing, but it does not reveal every contrast. Amharic has ejectives—consonants produced with a compressed, upward glottalic release—conventionally transliterated with a mark, as in ṭ or q'. It also contrasts short and long, or geminated, consonants. Gemination can distinguish words and grammatical forms yet is normally invisible in ordinary fidel. The vowel system includes central qualities for which English-based spellings are inconsistent. Learn pronunciations from a speaker and treat romanization as a disposable annotation, not the sound itself.", "ldc-amharic", "w3c-ethiopic", "leslau"),
    script: "Ethiopic examples with practical transliteration; ə represents a central vowel and doubled letters mark gemination",
    soundSystem: cited("A useful learner inventory groups plain stops such as t and k against ejectives such as ጥ ṭ and ቀ q. Ejectives are not simply louder consonants; the air mechanism and abrupt release matter. Consonant length deserves equal attention: a held consonant can mark lexical difference or verb morphology. Seven commonly described vowel qualities are distributed across the traditional fidel orders, although the sign-to-sound relationship contains historical spellings and contextual variation. Several written consonant series—such as ሀ, ሐ, and ኀ in many modern varieties—may share a pronunciation while retaining different spellings.", "leslau", "ldc-amharic", "w3c-ethiopic"),
    prosody: cited("Amharic is not normally taught as a lexical tone language. Word prominence, phrase-final movement, focus, questions, and expressive lengthening nevertheless shape natural speech. The greater beginner problem is often timing: if a geminated consonant is shortened, the following vowel can sound misplaced and a familiar word becomes difficult to identify. Shadow short clauses with their discourse melody, especially greetings, polite requests, and negative verb forms, rather than pronouncing each fidel as an equally weighted beat.", "leslau", "ldc-amharic"),
    learnerTraps: ["Treating ejective ጥ, ጭ, ጽ, ጰ, and ቀ as ordinary t, ch, s, p, and k", "Failing to hold geminated consonants because standard writing usually leaves length unmarked", "Assuming every scholarly or informal romanization uses e, ä, ə, and apostrophes the same way", "Reading the sixth order as one fixed vowel even when it closes a syllable or participates in a cluster", "Expecting historically distinct fidel series to remain distinct in every contemporary accent"],
    sampleWords: [
      { original: "ቡና", transliteration: "buna", translation: "coffee", note: "A clean first-order/u/fourth-order contrast; keep both vowels audible." },
      { original: "ጤና", transliteration: "ṭena", translation: "health", note: "The opening ጥ-series consonant is ejective; compare it with ordinary ተ t." },
      { original: "ቀን", transliteration: "qän", translation: "day", note: "The initial q is ejective or strongly glottalized in standard descriptions, not English k." },
      { original: "አማርኛ", transliteration: "amarəñña", translation: "Amharic", note: "The final palatal nasal is geminated: hold it before the last vowel." },
      { original: "መጽሐፍ", transliteration: "mäṣḥaf", translation: "book", note: "Conventional spelling preserves consonant distinctions many speakers merge in ordinary pronunciation." },
      { original: "እንጀራ", transliteration: "ənjära", translation: "injera", note: "The initial central vowel is not a full English ee; the common English spelling injera is not a transliteration key." },
      { original: "ይሄዳል", transliteration: "yəhhedal", translation: "he goes; he will go", note: "The h is geminated in careful analysis although ordinary fidel does not mark that length." }
    ]
  },
  writing: {
    overview: cited("Amharic uses Ethiopic fidel, a left-to-right abugida descended from the writing tradition first used for Geʽez. In an abugida, the basic sign represents a consonant with a vowel, and systematic changes to its shape indicate other vowels. A learner therefore meets families such as ለ lä, ሉ lu, ሊ li, ላ la, ሌ le, ል lə, ሎ lo. The pattern is regular enough to organize memory, but individual families change shape in different ways and some have labialized extensions. Modern Amharic normally uses spaces between words, while traditional Ethiopic punctuation remains visible in formal and historical text.", "unicode-ethiopic", "w3c-ethiopic"),
    primaryScript: "Ethiopic (Geʽez) script, commonly called fidel",
    romanization: cited("There is no single everyday romanization standard. Linguistic works distinguish sounds with symbols such as ä, ə, š, č, ñ, ṭ, and ṣ; maps and passports may use different conventions; messaging often substitutes plain Latin letters. Romanization is useful for recording pronunciation and searching resources, but it hides fidel spelling choices and commonly omits gemination. Install an Amharic keyboard early and save both script and audio.", "ldc-amharic", "w3c-ethiopic"),
    spellingNorms: cited("Modern words are separated by spaces, though the Ethiopic wordspace ፡ appears in older or stylistically traditional text. Full stop ። and other Ethiopic punctuation coexist with international punctuation. Conventional spelling preserves multiple letter families with merged pronunciations, so dictation requires lexical knowledge. Gemination is generally unwritten. Unicode encodes characters rather than seven-position font tricks; sound digital practice stores actual Ethiopic code points and uses an appropriate font instead of images or legacy encodings.", "unicode-ethiopic", "w3c-ethiopic"),
    styleNotes: [
      cited("Learn fidel by consonant family and real word: ቤት bet “house” is more memorable than an isolated chart coordinate.", "w3c-ethiopic"),
      cited("Do not ‘correct’ ሀ/ሐ/ኀ or ሰ/ሠ solely by modern pronunciation. Conventional spelling and etymology may distinguish them even when your model speaker does not.", "w3c-ethiopic"),
      cited("Printed newspapers, social posts, handwritten notes, and liturgical manuscripts demand different visual skills. Begin with a clear modern font, then broaden deliberately.", "unicode-ethiopic", "iu-materials")
    ]
  },
  grammar: {
    overview: cited("Amharic grammar rewards analysis at both ends of the sentence. Noun phrases place many modifiers before the noun and use suffixes for definiteness, possession, and some grammatical roles. The finite verb, normally late in the clause, agrees with its subject and can also carry an object pronoun. Verbs are built from consonantal roots through stems and patterns, but Amharic also uses many transparent prefixes and suffixes. Calling it simply ‘root-and-pattern’ or simply ‘agglutinative’ misses the productive mixture.", "leslau", "dependency-grammar"),
    typologicalProfile: cited("The unmarked clause order is subject–object–verb, and the language is broadly head-final: relative clauses precede their noun, possessors precede possessed nouns, and many English prepositional meanings use postpositions or bound forms. Grammatical gender is most visible in singular agreement: second- and third-person singular forms often distinguish masculine and feminine, while first person does not. Definite articles and object marking interact with specificity, and everyday conversation omits recoverable subjects because the verb already identifies them.", "leslau", "dependency-grammar", "wiki-amharic"),
    morphology: cited("A verb root commonly contains three consonants, though other shapes occur. Different vocalic and consonantal patterns create stems connected with simple action, causation, passivity, reciprocity, and related meanings. Around that stem gather subject markers, tense/aspect material, negation, object suffixes, and sometimes auxiliaries. Nouns accept the definite article -u/-wa, possessive suffixes, plural -očč, and case-related marking. Sound alternations and unwritten gemination mean that visual segmentation alone is insufficient; pair paradigms with recorded sentences.", "leslau", "wiki-amharic"),
    syntax: cited("Amharic's final verb makes long written sentences feel backward to English readers, but the useful skill is to locate nested boundaries. A relative verb beginning with yä- stands before the noun it describes. Complement clauses and converbs can package background events before the main verb. Definite or specific direct objects often receive the marker -n, and an object may also be resumed by a suffix on the verb, especially when topical or definite. Word order can move constituents for focus, so SOV is a default, not a prohibition.", "relative-clauses", "dependency-grammar", "leslau"),
    advancedPainPoints: ["Hearing morphologically significant gemination that the script does not show", "Choosing among perfective, imperfective, jussive, gerundive, and compound constructions in discourse", "Tracking subject and object agreement inside long verbs", "Building yä- relative clauses and nominalized expressions without copying English order", "Separating colloquial reductions from formal written conventions", "Using honorific and polite agreement naturally rather than mechanically"],
    topics: [
      { title: "Final verbs and object marking", body: cited("In a neutral transitive clause, the object precedes the verb. Definite/specific objects commonly take -n. In ልጁ መጽሐፉን አነበበ, the ending on ‘book’ marks it as the definite object; the past verb closes the clause. Train yourself to wait for that verb before deciding what happened.", "leslau", "dependency-grammar"), example: "ልጁ መጽሐፉን አነበበ። (Ləju mäṣḥafun anbäbä.)", exampleTranslation: "The boy read the book." },
      { title: "Subject agreement and omitted pronouns", body: cited("Finite verbs identify person, number, and in several singular persons gender. An independent subject pronoun is therefore optional unless it is contrastive or clarifying. እሄዳለሁ already means ‘I go/I will go’; adding እኔ can emphasize ‘I’ against someone else.", "leslau", "wiki-amharic"), example: "(እኔ) ነገ እሄዳለሁ። ((Əne) nägä əhedallähu.)", exampleTranslation: "I will go tomorrow." },
      { title: "The negative frame", body: cited("Many finite negatives use a discontinuous pattern: al- at the front and -m at the end. The two pieces act like brackets around the verbal material. Because pronunciation contracts in fast speech, learn positive and negative pairs from audio rather than adding a memorized syllable at the last moment.", "leslau"), example: "አልገባኝም። (Algäbaññəm.)", exampleTranslation: "I don't understand. (Literally, it did not enter me.)" },
      { title: "Possession on the noun", body: cited("Possession can be expressed with suffixes: ቤቴ bete ‘my house’ packages noun and possessor in one word. Full possessors normally precede the possessed expression with yä-, a highly productive linker also important in relative structures.", "leslau", "relative-clauses"), example: "ይህ ቤቴ ነው። (Yəh bete näw.)", exampleTranslation: "This is my house." },
      { title: "Relative clauses before the noun", body: cited("Amharic places the describing clause before its head noun and marks the relative verb with yä-. The form can also contain agreement and an object suffix. In ‘the book that I bought,’ the learner must process the buying event before reaching ‘book,’ the reverse of the common English order.", "relative-clauses", "dependency-grammar"), example: "የገዛሁት መጽሐፍ ጥሩ ነው። (Yägäzzahut mäṣḥaf ṭəru näw.)", exampleTranslation: "The book that I bought is good." },
      { title: "Object suffixes on verbs", body: cited("A verb may carry a suffix referring to a definite or topical object. አየሁት ayähut contains first-person subject agreement and a third-person masculine object: ‘I saw him/it.’ This double marking is a key reason isolated dictionary forms do not prepare learners for conversation.", "dependency-grammar", "wiki-amharic"), example: "ትናንት አየሁት። (Tənant ayähut.)", exampleTranslation: "I saw him yesterday." },
      { title: "Existence and possession", body: cited("Amharic commonly expresses possession through an existential construction rather than a direct equivalent of English ‘have.’ The possessor appears in a form meaning roughly ‘to/at me,’ while the possessed item is said to exist.", "leslau"), example: "ሁለት ወንድሞች አሉኝ። (Hulätt wändəmmočč alluññ.)", exampleTranslation: "I have two brothers. (Two brothers exist to me.)" },
      { title: "Polite and honorific agreement", body: cited("Address is grammatical as well as lexical. አንተ antä and አንቺ anči are familiar singular masculine and feminine; እርስዎ ərswo is polite. Polite agreement may use plural-looking or honorific verb forms, and respectful third-person reference has its own conventions. Match the whole phrase used by your interlocutor rather than swapping only the pronoun.", "leslau"), example: "እርስዎ እንዴት ነዎት? (Ərswo endet näwot?)", exampleTranslation: "How are you? (polite)" }
    ]
  },
  whereSpoken: {
    overview: cited("Amharic is concentrated in Ethiopia, especially as a first language in Amhara Region and Addis Ababa and as a first or additional language in many cities and communities elsewhere. Census-style totals age quickly and definitions differ: mother tongue, ability, regular home use, and lingua-franca competence are not interchangeable. The durable point is functional breadth. Amharic connects many people to federal services and national media, while regional states and communities sustain other working and educational languages. Migration has also created substantial Amharic-speaking networks abroad.", "constitution", "language-policy", "wiki-amharic"),
    regions: [
      { place: "Amhara Region", note: cited("A major first-language heartland with meaningful internal variation around Gojjam, Gondar, Wollo, and Shewa. Urban-rural and multilingual differences cut across these labels.", "ldc-amharic", "dialects") },
      { place: "Addis Ababa", note: cited("The capital anchors the prestige standard and brings Amharic into daily contact with Oromo and many other Ethiopian and international languages. Its speech is socially diverse, despite serving as the teaching norm.", "ldc-amharic", "oxford-handbook") },
      { place: "Across Ethiopia", note: cited("Amharic is widely learned for interregional communication, media, schooling, commerce, and federal administration. Its reach varies, and constitutional recognition of other languages is essential context.", "constitution", "language-policy") },
      { place: "Eritrea and the Horn", note: cited("Amharic may be understood or used through historical, family, media, or migration ties, but it should not be presented as Eritrea's national language. Tigrinya, Arabic, Tigre, and other languages occupy distinct roles.", "oxford-handbook") },
      { place: "Global diaspora", note: cited("Communities in the United States, Canada, Europe, the Middle East, southern Africa, and Australia support churches, mosques, associations, restaurants, artists, broadcasters, and heritage schools. Family competence often spans several languages and literacy levels.", "dd-less-common") }
    ]
  },
  difficulty: {
    label: "Very demanding",
    overview: cited("For an English-speaking beginner, Amharic combines several genuinely new systems: a large abugida, ejectives, unwritten consonant length, mostly verb-final syntax, gendered agreement, and verbs with many moving parts. Yet difficulty is uneven. Fidel becomes legible through families; there is no grammatical case maze like some European languages; and recurring verbal pieces eventually make long forms informative. Heritage learners, speakers of another Ethiopian language, and learners with Semitic-language experience begin from very different places. A difficulty label should guide planning, not rank intelligence or cultures.", "leslau", "dd-less-common"),
    easierAspects: ["Fidel families make the inventory more systematic than its size first suggests", "Vowels are represented more explicitly than in many other Semitic writing systems", "Frequent agreement markers provide clues to who acts on whom", "A large music, television, radio, and online media world supports immersion", "Root families can make vocabulary reinforce itself once core patterns become familiar"],
    hardAspects: ["Producing ejectives without turning them into plain consonants", "Hearing gemination that normal spelling does not mark", "Remembering conventional spellings for historically distinct but merged consonants", "Unpacking nested morphology and clause-final verbs at natural speed", "Finding graded, accurately transcribed modern material with matching audio", "Navigating respectful, familiar, formal, regional, and heritage usage"],
    plateauRisks: ["Remaining dependent on inconsistent Latin transliteration", "Knowing a fidel chart but reading too little connected prose", "Memorizing a root while ignoring the actual stem and collocations speakers use", "Consuming music or television passively without replaying short scenes", "Treating all Amharic outside a textbook standard as error", "Using archaic institutional-course dialogues as the only model for present-day interaction"],
    workload: cited("A sustainable plan gives script, sound, morphology, and culture separate attention every week. Spend ten minutes daily reading familiar fidel aloud; shadow a thirty-second recording until ejectives and consonant timing survive at speed; analyze three real verbs; hold one corrected conversation; and read one short caption, story, or news paragraph for meaning. An older intensive course supplies drills, a modern tutor supplies living usage, and community media supplies motivation. Expect basic greetings and decoding within months, but comfortable unscripted conversation and newspaper or literary reading require sustained exposure over years.", "dd-less-common", "fsi", "iu-materials")
  },
  advancedLearning: {
    strategy: cited("At intermediate level, stop collecting naked verb paradigms. Build a searchable notebook of complete clauses tagged for root, stem, aspect, subject, object, negation, and register. Read the same event in a headline, a broadcast report, and an informal retelling; notice which nominalizations and Geʽez-derived terms disappear in speech. Ask a tutor to mark gemination in transliteration or audio because fidel alone will not show it. Heritage learners should test literacy and productive control separately rather than assuming strong comprehension makes beginner materials unnecessary.", "leslau", "caco"),
    mediaPractice: cited("Use one predictable genre first. News intros repeat institutional vocabulary, cooking videos pair actions with visible objects, interviews expose respectful address, sitcoms provide turn-taking, and songs make poetic compression memorable. Work in short loops: listen without text, transcribe what you can in fidel, check a caption or speaker, shadow, then retell. Compare broadcasters from Addis Ababa with regional and diaspora voices. Religious media can be linguistically rich, but label Geʽez quotations and specialized Orthodox, Muslim, Protestant, or Jewish vocabulary rather than treating one tradition as neutral everyday speech.", "iu-materials", "caco"),
    dictionariesAndCorpora: cited("Kane's Amharic–English Dictionary remains a major deep reference, though learners must interpret its transliteration and dated examples carefully. Leslau's Reference Grammar answers structural questions rather than supplying conversational frequency. The Contemporary Amharic Corpus offers roughly 24 million automatically tagged tokens gathered from edited and web sources; it is valuable for research, collocation, and spelling patterns, but randomized sentences and automatic annotation limit it as a reading course. Cross-check corpus findings with speakers and current media.", "leslau", "caco"),
    resources: [
      { type: "other", title: "Discover Discomfort: Less-Common Language Learning Resources", url: "https://discoverdiscomfort.com/less-common-language-learning-resources/", level: "all", description: cited("A practical framework for assembling a learning system when one polished app does not cover the language: institutional courses, tutors, dictionaries, and community media each solve different problems.", "dd-less-common") },
      { type: "course", title: "FSI Amharic Basic Course", url: "https://www.fsi-language-courses.org/fsi-amharic-basic-course/", level: "beginner", description: cited("A large public-domain-style archive of structured lessons and audio. Its dialogues and social framing are dated, but pronunciation drills and systematic sequencing remain useful when paired with a present-day speaker.", "fsi") },
      { type: "other", title: "Indiana University Amharic Language Materials", url: "https://cle.indiana.edu/web-images/celt-materials.html", level: "all", description: cited("A university language-materials portal listing Amharic within its African Studies holdings and audio-visual archive.", "iu-materials") },
      { type: "book", title: "Reference Grammar of Amharic", url: "https://glottolog.org/resource/reference/id/69646", level: "advanced", description: cited("Wolf Leslau's comprehensive reference for the phonology, morphology, syntax, and examples that compact learner guides necessarily simplify.", "leslau") },
      { type: "corpus", title: "Contemporary Amharic Corpus (CACO)", url: "https://www.findke.ovgu.de/en/Research/Data+Sets/Contemporary+Amharic+Corpus+(CACO).html", level: "advanced", description: cited("A research corpus of about 24 million orthographic tokens with automatic morphosyntactic annotation and downloadable data.", "caco") },
      { type: "other", title: "Ethiopic (Amharic) Orthography Notes", url: "https://r12a.github.io/scripts/ethi/am.html", level: "intermediate", description: cited("A current, highly visual reference for characters, punctuation, line breaking, typography, and Unicode behavior in modern Amharic.", "w3c-ethiopic") }
    ]
  },
  wordsAndTexts: {
    overview: cited("Amharic social life is audible in formulas whose literal pieces and practical uses diverge. ደህና dehna invokes well-being in greetings and leave-taking; እንኳን ደህና መጡ ənkwan dehna mäṭṭu welcomes someone with respectful agreement; አይዞህ ayzoh encourages a man facing trouble, with gendered alternatives for other addressees. Coffee vocabulary travels internationally, but Ethiopian coffee conversation involves invitations, hospitality, roasting, and extended company that the borrowed English word cannot contain. Learners gain more by asking when a phrase is said, to whom, and with what response than by hunting supposedly untranslatable words.", "leslau", "wiki-amharic"),
    notableWords: [
      { term: "ሰላም", transliteration: "sälam", meaning: "peace; hello", note: cited("A greeting and a word for peace with recognizable Semitic relatives. Its familiarity should not tempt learners to flatten every religious or social use into English ‘hi.’", "wiki-amharic") },
      { term: "ቡና", transliteration: "buna", meaning: "coffee", note: cited("An ordinary drink word embedded in one of Ethiopia's most internationally visible hospitality traditions. The language of preparation and invitation is as valuable as the noun.", "wiki-amharic") },
      { term: "እንጀራ", transliteration: "ənjära", meaning: "injera; by extension livelihood in some contexts", note: cited("The staple flatbread also participates in expressions about earning one's living. English ‘injera’ captures the food but not every figurative extension.", "leslau") },
      { term: "ደህና", transliteration: "dähna", meaning: "well; safe; fine", note: cited("A small word that powers greetings, farewells, reassurance, and questions about well-being. Learn it through whole exchanges.", "leslau") },
      { term: "አይዞህ", transliteration: "ayzoh", meaning: "take heart; hang in there (to a man)", note: cited("An encouraging formula whose ending changes with the addressee. Depending on the moment it can console, embolden, or acknowledge effort.", "leslau") },
      { term: "ፍቅር", transliteration: "fəqər", meaning: "love", note: cited("A productive literary and everyday word found in names, song titles, religious language, and ordinary statements of affection.", "wiki-amharic") },
      { term: "ትዕግሥት", transliteration: "təʿgəśt", meaning: "patience; endurance", note: cited("Its spelling preserves learned distinctions and its use ranges from an abstract virtue to a common personal name.", "w3c-ethiopic") },
      { term: "እሺ", transliteration: "əši", meaning: "okay; all right; yes in acknowledgment", note: cited("A high-frequency interaction word. Its intonation can signal willing agreement, reluctant acceptance, transition, or ‘I hear you.’", "leslau") }
    ],
    loanwordLayers: cited("Inherited Ethio-Semitic roots sit beside a large Geʽez learned layer that is especially visible in religion, administration, education, and literature. Contact with Cushitic and other Ethiopian languages is older and deeper than a tidy list of labeled borrowings can represent. Arabic contributed through trade and Islamic scholarship; Italian loans often evoke vehicles, tools, foods, and urban modernity; English supplies current technical and institutional vocabulary. Speakers may prefer an inherited, Geʽez-shaped, borrowed, or newly coined term according to audience and politics. Etymology is useful when it explains a text, not when it divides a living vocabulary into pure and impure parts.", "oxford-handbook", "wiki-amharic"),
    idioms: [
      { original: "የአይን አውጣ", transliteration: "yä-ayən awṭa", translation: "shameless; brazen", note: "Literally evokes someone who has ‘taken out the eye,’ a vivid way of describing behavior unrestrained by social regard." },
      { original: "ሆድና ጀርባ መሆን", transliteration: "hod-na järba mä-hon", translation: "to become enemies; to be completely at odds", note: "Literally, to be belly and back: two sides that cannot face the same direction." },
      { original: "እጅና ጓንት", transliteration: "əj-na gwant", translation: "inseparable; closely matched", note: "Literally ‘hand and glove,’ used for people or things that fit together closely." },
      { original: "አፍ አውጥቶ መናገር", transliteration: "af awṭto mänagär", translation: "to say something openly and plainly", note: "Literally, to bring out one's mouth and speak—useful when a matter is finally stated without concealment." },
      { original: "ውሃ ቅዳ ውሃ መልስ", transliteration: "wuha qədda, wuha mälləs", translation: "futile, repetitive work", note: "Literally ‘draw water, return water’: effort that merely undoes itself. Exact use and wording can vary, so confirm with your speech community." }
    ],
    textGenres: ["Qəne learned poetry, church commentary, and Geʽez-influenced religious writing", "Royal chronicles, historical narratives, lives, and manuscript traditions", "Modern novels, short stories, plays, memoirs, essays, and children's books", "Newspapers, political commentary, public notices, and long-form journalism", "Azmari performance, popular song, hip-hop, gospel, liturgical music, and music video", "Cinema, television drama, comedy, dubbed media, radio, podcasts, and online interviews", "Diaspora literature, heritage-school texts, social video, memes, and multilingual digital writing"]
  },
  relationships: { overview: cited("Amharic belongs genealogically with Ethio-Semitic languages, most closely Argobba, and more broadly with Semitic languages including Tigrinya, Geʽez, Arabic, and Hebrew. Genealogy is not the whole profile. Sustained contact with Oromo, Agaw languages, Somali, Gurage languages, and many other languages helped shape Amharic and continues through individual multilingualism. Shared fidel does not prove close relationship—some Cushitic languages also use or have used Ethiopic—and different scripts do not erase family ties. Keep script, ancestry, borrowing, and present-day bilingualism as four separate questions.", "glottolog", "oxford-handbook", "unicode-ethiopic"), languages: relatedLanguages },
  culturalNotes: "Amharic is neither a synonym for Ethiopian nor the possession of one political story. It is a home language, a federal working language, a lingua franca, a heritage language, and sometimes a language associated with unequal state power; different speakers can experience several of these realities at once. Ask which languages a person uses rather than inferring them from name, ethnicity, religion, or birthplace. Respect address choices: familiar masculine and feminine forms, polite እርስዎ, kin terms, professional titles, and honorific agreement carry relationships. Transliteration of Ethiopian names varies, and many people do not use a Western inherited-surname system; reproduce the spelling a person chooses. In cultural study, range beyond a single coffee-ceremony image toward novels, Muslim scholarship, Orthodox and Protestant traditions, Jewish histories, regional popular music, labor migration, comedy, cinema, and contemporary debate.",
  resources: [
    { type: "other", title: "Discover Discomfort: Less-Common Language Learning Resources", url: "https://discoverdiscomfort.com/less-common-language-learning-resources/", level: "all", description: cited("A candid resource-building strategy applicable to Amharic's mix of excellent older references and dispersed modern media.", "dd-less-common") },
    { type: "course", title: "FSI Amharic Basic Course", url: "https://www.fsi-language-courses.org/fsi-amharic-basic-course/", level: "beginner", description: cited("Extensive lessons and audio best mined for sound and structure while a modern tutor updates usage and context.", "fsi") },
    { type: "other", title: "Indiana University Language Materials", url: "https://cle.indiana.edu/web-images/celt-materials.html", level: "all", description: cited("A university portal to archived Amharic and other African-language learning media.", "iu-materials") },
    { type: "book", title: "Reference Grammar of Amharic", url: "https://glottolog.org/resource/reference/id/69646", level: "advanced", description: cited("The major detailed grammatical reference to consult after a learner explanation raises a harder question.", "leslau") },
    { type: "corpus", title: "Contemporary Amharic Corpus", url: "https://www.findke.ovgu.de/en/Research/Data+Sets/Contemporary+Amharic+Corpus+(CACO).html", level: "advanced", description: cited("A large downloadable, automatically annotated text collection for research into forms and collocations.", "caco") },
    { type: "other", title: "Ethiopic Script Resources", url: "https://www.w3.org/TR/ethi-lreq/", level: "intermediate", description: cited("W3C guidance connecting Amharic orthography with practical digital layout, characters, punctuation, and typographic support.", "w3c-ethiopic") }
  ],
  relatedLanguages,
  phrases: [
    { original: "ሰላም", transliteration: "sälam", translation: "Hello; peace.", usageNote: "Broad and neutral; more elaborate greetings vary with time, relationship, and region." },
    { original: "እንዴት ነህ?", transliteration: "endet näh?", translation: "How are you?", usageNote: "Familiar, addressed to a man. To a woman: እንዴት ነሽ? endet näš?" },
    { original: "እንዴት ነዎት?", transliteration: "endet näwot?", translation: "How are you?", usageNote: "Polite or respectful." },
    { original: "ደህና ነኝ።", transliteration: "dähna näññ", translation: "I'm well." },
    { original: "አመሰግናለሁ።", transliteration: "amäsäggənallähu", translation: "Thank you." },
    { original: "እባክህ", transliteration: "əbbakəh", translation: "Please.", usageNote: "To a man. To a woman use እባክሽ əbbakiš; polite/plural እባክዎ əbbakwo." },
    { original: "ይቅርታ", transliteration: "yəqərta", translation: "Excuse me; sorry." },
    { original: "አልገባኝም።", transliteration: "algäbaññəm", translation: "I don't understand.", literalMeaning: "It did not enter me." },
    { original: "እንደገና ይናገሩ።", transliteration: "əndägäna yənagäru", translation: "Please say it again.", usageNote: "Polite request." },
    { original: "ቀስ ብለው ይናገሩ።", transliteration: "qäs bəläw yənagäru", translation: "Please speak slowly.", usageNote: "Polite; literally asks the person to speak ‘slowly.’" },
    { original: "አማርኛ እየተማርኩ ነው።", transliteration: "amarəñña əyyätämarku näw", translation: "I am learning Amharic." },
    { original: "ይህ ምን ማለት ነው?", transliteration: "yəh mən malät näw?", translation: "What does this mean?" },
    { original: "ስንት ነው?", transliteration: "sənt näw?", translation: "How much is it?; how many is it?", usageNote: "Context supplies the item or quantity." },
    { original: "እሺ", transliteration: "əši", translation: "Okay; all right." },
    { original: "ደህና ሁን", transliteration: "dähna hun", translation: "Goodbye; be well.", usageNote: "Familiar to a man; forms change for a woman, a group, or respectful address." },
    { original: "እንኳን ደህና መጡ", transliteration: "ənkwan dähna mäṭṭu", translation: "Welcome.", usageNote: "Respectful/plural welcome formula." }
  ],
  sources: [
    { id: "dd-less-common", title: "Best Less-Common Language Learning Resources: What Actually Works", url: "https://discoverdiscomfort.com/less-common-language-learning-resources/", publisher: "Discover Discomfort", accessedAt: "2026-07-10" },
    { id: "wiki-amharic", title: "Amharic", url: "https://en.wikipedia.org/wiki/Amharic", publisher: "Wikipedia", accessedAt: "2026-07-10" },
    { id: "glottolog", title: "Glottolog: Amharic", url: "https://glottolog.org/resource/languoid/id/amha1245", publisher: "Glottolog", updatedAt: "2026", accessedAt: "2026-07-10" },
    { id: "constitution", title: "Constitution of the Federal Democratic Republic of Ethiopia, Article 5", url: "https://www.servat.unibe.ch/icl/et00000_.html", publisher: "International Constitutional Law Project, University of Bern", publishedAt: "1995", accessedAt: "2026-07-10" },
    { id: "language-policy", title: "Language Law and Policy of the Federal Government of Ethiopia", url: "https://doi.org/10.32566/ah.2021.1.4", publisher: "ACTA HUMANA", publishedAt: "2021", accessedAt: "2026-07-10" },
    { id: "oxford-handbook", title: "The Oxford Handbook of Ethiopian Languages", url: "https://academic.oup.com/edited-volume/46265", publisher: "Oxford University Press", publishedAt: "2023", accessedAt: "2026-07-10" },
    { id: "unicode-ethiopic", title: "The Unicode Standard, Chapter 19: Ethiopic", url: "https://www.unicode.org/versions/Unicode17.0.0/core-spec/chapter-19/", publisher: "Unicode Consortium", updatedAt: "2025", accessedAt: "2026-07-10" },
    { id: "w3c-ethiopic", title: "Ethiopic Script Resources and Amharic Orthography Notes", url: "https://www.w3.org/TR/ethi-lreq/", publisher: "W3C Internationalization Working Group", updatedAt: "2026-04-27", accessedAt: "2026-07-10" },
    { id: "ldc-amharic", title: "Language Specific Peculiarities Document for Amharic as Spoken in Ethiopia", url: "https://catalog.ldc.upenn.edu/docs/LDC2019S22/LSP_307_performer09292015.pdf", publisher: "Linguistic Data Consortium, University of Pennsylvania", publishedAt: "2015", accessedAt: "2026-07-10" },
    { id: "dialects", title: "Differences between the Amharic Dialects of Gondar and Addis Ababa", url: "https://cris.tau.ac.il/en/publications/differences-between-the-amharic-dialects-of-gondar-and-addis-abab/", publisher: "Curzon / Tel Aviv University research portal", publishedAt: "1999", accessedAt: "2026-07-10" },
    { id: "leslau", title: "Reference Grammar of Amharic", url: "https://glottolog.org/resource/reference/id/69646", publisher: "Harrassowitz", publishedAt: "1995", accessedAt: "2026-07-10" },
    { id: "relative-clauses", title: "On Amharic Relative Clauses", url: "https://www.cambridge.org/core/services/aop-cambridge-core/content/view/6941FB3A570E4EB9F8D482DB296AE3D3/S0041977X00121135a.pdf/on_amharic_relative_clauses1.pdf", publisher: "Bulletin of the School of Oriental and African Studies", accessedAt: "2026-07-10" },
    { id: "dependency-grammar", title: "A Dependency Grammar for Amharic", url: "https://web.stanford.edu/group/cslipublications/cslipublications/LFG/7/pdfs/lfg02.pdf", publisher: "CSLI Publications, Stanford University", publishedAt: "2002", accessedAt: "2026-07-10" },
    { id: "caco", title: "Contemporary Amharic Corpus (CACO)", url: "https://www.findke.ovgu.de/en/Research/Data+Sets/Contemporary+Amharic+Corpus+(CACO).html", publisher: "Otto von Guericke University Magdeburg", updatedAt: "2019-11-26", accessedAt: "2026-07-10" },
    { id: "iu-materials", title: "Language Learning Materials", url: "https://cle.indiana.edu/web-images/celt-materials.html", publisher: "Indiana University Center for Language Excellence", accessedAt: "2026-07-10" },
    { id: "fsi", title: "FSI Amharic Basic Course", url: "https://www.fsi-language-courses.org/fsi-amharic-basic-course/", publisher: "Foreign Service Institute course archive", accessedAt: "2026-07-10" }
  ],
  seo: { title: "Amharic Language Guide: Fidel, Grammar, History and Phrases", description: "A deeply researched guide to Amharic pronunciation, Ethiopic fidel, Semitic verb structure, regional and social variation, practical phrases, literature, media, and learning resources." }
} satisfies LanguageGuide;
