import { cited } from "../citations.js";
import type { LanguageGuide } from "../types.js";

const relatedLanguages = [
  { name: "Argobba", relationship: "Closest documented relative", explanation: cited("Argobba and Amharic are close relatives within South Ethio-Semitic. Argobba has its own communities and varieties, though many speakers have shifted toward Amharic. Compare familiar words to see their shared history while keeping the two languages distinct.", "glottolog", "oxford-handbook") },
  { name: "Tigrinya", relationship: "Fellow Ethio-Semitic language", explanation: cited("Tigrinya shares Semitic structures and the Ethiopic script, so an Amharic reader will recognize many signs and some roots. Its sound changes, vocabulary, verbal system, and regional standards are nevertheless distinct. Script familiarity provides a head start, not automatic comprehension.", "glottolog", "wiki-amharic") },
  { name: "Geʽez", relationship: "Classical and liturgical relative", explanation: cited("Geʽez is no longer an ordinary community vernacular, but remains a liturgical and scholarly language and supplies Amharic with script tradition, learned vocabulary, names, and textual genres. Amharic did not simply descend from the modern liturgical register; both belong inside a longer, branching Ethio-Semitic history.", "unicode-ethiopic", "oxford-handbook") },
  { name: "Arabic", slug: "arabic", relationship: "More distant Semitic relative and contact language", explanation: cited("Arabic and Amharic share a remote Semitic inheritance, including recognizable root-based word formation, while long Red Sea, Islamic, commercial, and literary connections added contact vocabulary. Their scripts and most everyday words differ, and neither is a variety of the other.", "glottolog", "oxford-handbook") },
  { name: "Oromo", relationship: "Cushitic contact language", explanation: cited("Oromo is Afro-Asiatic but Cushitic rather than Semitic. Centuries of multilingual life have produced borrowing and structural convergence in both directions. Today many Ethiopians use both languages, so Oromo-Amharic interaction is a living social relationship, not merely a historical footnote.", "oxford-handbook", "constitution") }
] satisfies LanguageGuide["relationships"]["languages"];

export const amharicGuide = {
  slug: "amharic",
  name: "Amharic",
  autonym: "አማርኛ",
  status: "published",
  publishedAt: "2026-07-09",
  summary: "Amharic uses Ethiopic fidel, verbs that carry several meanings at once, and forms of address that reflect relationships. Follow its speakers across a multilingual Ethiopia and diaspora.",
  family: "Afro-Asiatic, Semitic, Ethio-Semitic",
  macroRegion: "Ethiopia and global Ethiopian diasporas",
  primaryScript: "Ethiopic (Geʽez) script",
  difficultyLabel: "Very demanding",
  learnerHook: "Read ቡና as buna, listen for a held consonant, then notice how an Amharic verb can tell you who acted and who was affected.",
  hero: { imageAlt: "Amharic printed in Ethiopic fidel beside a handwritten note and a cup of coffee.", callToActionLabel: "Explore Amharic in use" },
  classification: "South Ethio-Semitic language, closely related to Argobba",
  speakerCommunity: "Many Ethiopians speak Amharic at home, while others learn it for work, media, or conversation across communities. Ethiopia's federal government now lists Amharic alongside Afar, Oromo, Somali, and Tigrinya as working languages. The constitution gives all Ethiopian languages equal state recognition and lets regional states choose their own working languages.\n\nAmharic also travels with Ethiopian communities in North America, Europe, the Middle East, Africa, and Australia. A heritage speaker may follow family conversation well but still want help reading fidel or writing formal messages. These different experiences all belong to the language's present life.",
  facts: [
    { label: "Family", value: "Afro-Asiatic · Semitic · Ethio-Semitic · South" },
    { label: "Closest relative", value: "Argobba" },
    { label: "Writing", value: "Left-to-right Ethiopic abugida, commonly called fidel" },
    { label: "Federal role", value: "One of five listed federal working languages" },
    { label: "Core order", value: "Generally subject–object–verb, with modifiers before nouns" },
    { label: "Sound cues", value: "Ejectives and contrastive consonant length" }
  ],
  introduction: cited("Amharic (አማርኛ) is a South Ethio-Semitic language in the Afro-Asiatic family, spoken at home across Ethiopia and by Ethiopian communities abroad. It also serves as a common language between people with different mother tongues and is one of Ethiopia's federal working languages. In the 2007 national census, about 21.6 million residents reported Amharic as their mother tongue; that dated measure excludes people who learned it later.\n\nAmharic is written in the Ethiopic script, commonly called fidel, whose signs combine a consonant with a vowel. A family of signs changes shape as the vowel changes: በ, ቡ, ቢ, and ባ share the same consonant, for example. This writing tradition has roots in Geʽez, the classical language still used in Ethiopian religious life, but Amharic has its own centuries-long literary and public history.\n\nIn speech, holding a consonant longer can distinguish words even when ordinary spelling does not mark the difference. In a common sentence pattern, the verb comes last, and its form can identify the actor and sometimes the person affected. These features belong to a living language shaped by contact with Ethiopia's many other languages.", "ess-census-2007", "oxford-handbook", "glottolog", "embassy-profile", "unicode-ethiopic", "w3c-ethiopic", "leslau"),
  origins: {
    overview: cited("Amharic belongs to the South Ethio-Semitic group within the Semitic branch of Afro-Asiatic. Its speakers have long lived among speakers of Cushitic, Omotic, and other Ethiopian languages. Family ancestry explains part of Amharic's grammar; contact explains other sounds, words, and ways of speaking.\n\nPeople spoke Amharic before much of it appeared in surviving written records. Geʽez held a strong place in church and scholarly writing, while Amharic gradually took on more courtly, administrative, literary, and public roles. The two languages overlapped for centuries.", "glottolog", "oxford-handbook", "wiki-amharic"),
    timeline: [
      { period: "First millennium CE", event: cited("Geʽez supported a major manuscript and inscriptional tradition and the Ethiopic script developed its consonant-vowel organization. The script later expanded for sounds needed by Amharic and other Ethiopian and Eritrean languages.", "unicode-ethiopic", "w3c-ethiopic") },
      { period: "Medieval centuries", event: cited("South Ethio-Semitic varieties developed amid sustained interaction with Cushitic languages in the Ethiopian highlands. Amharic's precise early geography and subgrouping have been debated, so confident one-line origin legends should be treated cautiously.", "oxford-handbook", "glottolog") },
      { period: "14th–17th centuries", event: cited("Amharic appears in songs, praise poetry, royal and missionary records, and mixed-language texts while Geʽez remains central to formal literary and ecclesiastical life. Spoken use was broader than the surviving written record can show.", "wiki-amharic", "oxford-handbook") },
      { period: "19th–early 20th centuries", event: cited("Expansion of the Ethiopian state greatly widened Amharic's administrative and educational reach. That history created access and a shared lingua franca for many people, but also coercion, unequal opportunity, and language shift for others; serious accounts must hold these experiences together.", "oxford-handbook", "language-policy") },
      { period: "1995 constitutional order", event: cited("The federal constitution gave all Ethiopian languages equal state recognition, named Amharic as the federal working language, and let regional states choose their working languages. Federal practice has since expanded to list five working languages.", "constitution", "embassy-profile") },
      { period: "Digital present", event: cited("Unicode encoding, Ethiopic keyboards, web publishing, social media, and new speech and text datasets have widened Amharic's digital presence. Technical support is improving, though fonts, line breaking, search, spelling variation, and language-technology coverage remain uneven.", "unicode-ethiopic", "w3c-ethiopic", "caco") }
    ],
    contactHistory: cited("Amharic speakers have long interacted with people who speak Agaw languages, Oromo, Somali, Gurage languages, Tigrinya, and many others. That contact shaped regional speech as well as shared vocabulary. Geʽez also supplied learned and religious words.\n\nArabic words came through scholarship and Red Sea trade; Italian left words for some tools, foods, and parts of urban life. English now supplies many technical terms. Speakers fit borrowed words into fidel and Amharic word patterns, so a word's foreign history does not make it foreign in today's conversation.", "oxford-handbook", "wiki-amharic"),
    standardization: cited("Schools, publishers, and broadcasters often use an Addis Ababa-centered formal Amharic. Its spelling keeps some older consonant distinctions that many speakers no longer pronounce, and it usually leaves held consonants unmarked. Editors can differ on compounds and new technical words.\n\nThe standard helps people follow national media and public writing. Regional varieties and the other federal working languages have their own roles; one broadcast style cannot represent every Ethiopian speaker.", "w3c-ethiopic", "dialects", "embassy-profile")
  },
  variants: {
    overview: cited("Most courses teach a form of Amharic centered on Addis Ababa. Speakers from Shewa, Gojjam, Gondar, Wollo, and other areas may use different sounds, words, or forms. Migration, age, and other home languages also shape speech.\n\nThe same person may speak closer to the broadcast standard in an interview and use family forms at home. Diaspora communities add more settings for change. A regional form is part of living Amharic, not a failed version of the capital's speech.", "dialects", "ldc-amharic"),
    items: [
      { name: "Addis Ababa-centered standard", note: cited("The main target in schools, national broadcasting, and most courses. Addis Ababa itself is intensely multilingual, so its daily Amharic includes social and contact variation beyond a single announcer voice.", "ldc-amharic", "dialects") },
      { name: "Shewa, Gojjam, Gondar, and Wollo varieties", note: cited("These labels point to established regional patterns in pronunciation, forms, and vocabulary, not sealed boxes. Movement and intermarriage blur boundaries, and detailed descriptions remain uneven.", "ldc-amharic", "dialects") },
      { name: "Second-language Amharic", note: cited("Many people use Amharic alongside Oromo, Somali, Tigrinya, Wolaytta, Sidama, Afar, Gurage languages, and others. Their accents and word choices reflect multilingual lives and deserve the same respect as first-language varieties.", "constitution", "oxford-handbook") },
      { name: "Diaspora and heritage Amharic", note: cited("Families abroad may use Amharic alongside a language of their new home. A study of one Ethiopian family in Norway shows children hearing Amharic at home and in a community church school while also using Norwegian. Do not assume that hearing family talk, speaking, and reading develop at the same pace.", "heritage-norway") },
      { name: "Liturgical and literary Geʽez influence", note: cited("Geʽez vocabulary, quotations, and styles appear in religious and elevated contexts, but Geʽez is a related language, not an unusually formal Amharic dialect. Reading it is an additional specialization.", "unicode-ethiopic", "oxford-handbook") }
    ]
  },
  pronunciation: {
    overview: cited("Fidel shows a consonant with a vowel, but the script does not tell you everything about pronunciation. Amharic has ejectives: speakers release these consonants with a tight burst of air rather than saying an ordinary t or k. It also distinguishes a short consonant from a held one, called gemination.\n\nOrdinary writing rarely marks that held sound. Latin spellings also vary, especially for Amharic's central vowels. Learn a word with audio and fidel together, then treat its romanization as a temporary aid.", "ldc-amharic", "w3c-ethiopic", "leslau"),
    script: "Ethiopic examples with practical transliteration; ə represents a central vowel and doubled letters mark gemination",
    soundSystem: cited("Compare an ordinary t or k with the ejective sounds often written ṭ and q in study materials. Ejectives have a different release, not simply more volume. A held consonant can also change a word or verb form.\n\nFidel families show seven main vowel patterns, though sound and spelling do not always match one-to-one. Many speakers pronounce historically distinct signs such as ሀ, ሐ, and ኀ alike. They still learn which sign belongs in each conventional spelling.", "leslau", "ldc-amharic", "w3c-ethiopic"),
    prosody: cited("A change of pitch across a phrase can show a question, emphasis, or feeling, although Amharic is not normally taught as a tone language. Listen for the timing of a held consonant too; shortening it can make a familiar word hard to recognize.\n\nRepeat a short greeting or request after a speaker, matching the whole phrase's rhythm. Reading every fidel sign with equal weight will not give you that rhythm.", "leslau", "ldc-amharic"),
    learnerTraps: ["Treating ejective ጥ, ጭ, ጽ, ጰ, and ቀ as ordinary t, ch, s, p, and k", "Failing to hold geminated consonants because standard writing usually leaves length unmarked", "Assuming every scholarly or informal romanization uses e, ä, ə, and apostrophes the same way", "Reading the sixth order as one fixed vowel even when it closes a syllable or participates in a cluster", "Expecting historically distinct fidel series to remain distinct in every contemporary accent"],
    sampleWords: [
      { original: "ቡና", transliteration: "buna", translation: "coffee", note: "The two signs include their vowels. Say both syllables clearly." },
      { original: "ጤና", transliteration: "ṭena", translation: "health", note: "The opening ጥ-series consonant is ejective; compare it with ordinary ተ t." },
      { original: "ቀን", transliteration: "qän", translation: "day", note: "The initial q is ejective or strongly glottalized in standard descriptions, not English k." },
      { original: "አማርኛ", transliteration: "amarəñña", translation: "Amharic", note: "The final palatal nasal is geminated: hold it before the last vowel." },
      { original: "መጽሐፍ", transliteration: "mäṣḥaf", translation: "book", note: "Conventional spelling preserves consonant distinctions many speakers merge in ordinary pronunciation." },
      { original: "እንጀራ", transliteration: "ənjära", translation: "injera", note: "The initial central vowel is not a full English ee; the common English spelling injera is not a transliteration key." },
      { original: "ይሄዳል", transliteration: "yəhedal", translation: "he goes; he will go", note: "The first sign gives a short central vowel before the verb stem. Listen to the whole word's rhythm." }
    ]
  },
  writing: {
    overview: cited("Amharic uses Ethiopic fidel and reads from left to right. Each basic sign joins a consonant to a vowel; changing the sign changes the vowel. A writing system built this way is called an abugida.\n\nFollow one family: ለ lä, ሉ lu, ሊ li, ላ la, ሌ le, ል lə, ሎ lo. Other families follow similar patterns, though their shapes do not change identically. Modern writing usually puts spaces between words, and you may also see Ethiopic punctuation.", "unicode-ethiopic", "w3c-ethiopic"),
    primaryScript: "Ethiopic (Geʽez) script, commonly called fidel",
    romanization: cited("People write Amharic in Latin letters in several ways. A grammar may use ä, ə, š, č, ñ, or ṭ to show sounds that a casual message leaves unmarked. Romanization can help you search and remember a pronunciation, but it can hide the original spelling and a held consonant.\n\nInstall an Amharic keyboard early. Keep the fidel form and audio beside any Latin spelling you use.", "ldc-amharic", "w3c-ethiopic"),
    spellingNorms: cited("Writers normally separate modern Amharic words with spaces. Older or traditional text may use ፡ as a word divider, and ። is an Ethiopic full stop. Several signs keep distinct spellings even where many speakers now pronounce them alike.\n\nFidel usually leaves held consonants unmarked, so you must learn their sounds with the word. For digital text, type real Unicode Ethiopic characters with an appropriate font. An image of a word will be harder to search, select, or read with assistive tools.", "unicode-ethiopic", "w3c-ethiopic"),
    styleNotes: [
      cited("Learn fidel by consonant family and real word: ቤት bet “house” is more memorable than an isolated chart coordinate.", "w3c-ethiopic"),
      cited("Do not ‘correct’ ሀ/ሐ/ኀ or ሰ/ሠ solely by modern pronunciation. Conventional spelling and etymology may distinguish them even when your model speaker does not.", "w3c-ethiopic"),
      cited("Printed newspapers, social posts, handwritten notes, and liturgical manuscripts demand different visual skills. Begin with a clear modern font, then broaden deliberately.", "unicode-ethiopic", "iu-materials")
    ]
  },
  grammar: {
    overview: cited("Amharic often places the verb near the end of a sentence. The verb shows who acts and can also point to someone affected by the action. Before you reach it, descriptions usually appear ahead of the noun they describe.\n\nA verb may grow from a group of consonants, with changed vowels and added pieces giving it a new form. Nouns also take endings for meanings such as “the” or “my.” Learn these patterns through whole sentences, where you can see each part's job.", "leslau", "dependency-grammar"),
    typologicalProfile: cited("In a basic clause, the actor comes first, the object next, and the verb last. A clause describing a noun also comes before that noun. Where English puts a word such as “in” before a noun, Amharic often puts a related element after it or attaches one.\n\nForms for “you” and “he” or “she” can differ by gender in the singular; “I” does not. A verb may already show its subject, so speakers can leave out a separate pronoun when everyone knows whom they mean.", "leslau", "dependency-grammar", "wiki-amharic"),
    morphology: cited("Many Amharic verb roots have three consonants. Speakers change the vowels, double a consonant, or add pieces to make related forms, including forms where someone causes an action. Other pieces can show the subject, an object, negation, or whether the action is complete.\n\nNouns take endings too: -očč can show plural, while a suffix can mean “my” or mark a definite noun. A written form may hide a held consonant. Pair each pattern with a recording so you learn what the word actually sounds like.", "leslau", "wiki-amharic"),
    syntax: cited("In a long sentence, look for the final main verb and then work backward. A description beginning with yä- can tell you which noun comes next. Other verb forms may give background before the main event.\n\nA specific object can take -n, and the verb may also carry a piece that points back to that object. Speakers can shift word order to emphasize something, so actor–object–verb is a starting pattern rather than a fixed rule.", "relative-clauses", "dependency-grammar", "leslau"),
    advancedPainPoints: ["Hearing morphologically significant gemination that the script does not show", "Choosing among perfective, imperfective, jussive, gerundive, and compound constructions in discourse", "Tracking subject and object agreement inside long verbs", "Building yä- relative clauses and nominalized expressions without copying English order", "Separating colloquial reductions from formal written conventions", "Using honorific and polite agreement naturally rather than mechanically"],
    topics: [
      { title: "Final verbs and object marking", body: cited("In a basic sentence, the object comes before the verb. A specific or definite object often takes -n; in ልጁ መጽሐፉን አነበበ, the ending on “book” marks it as the object. Wait for the final verb to learn what the boy did.", "leslau", "dependency-grammar"), example: "ልጁ መጽሐፉን አነበበ። (Ləju mäṣḥafun anbäbä.)", exampleTranslation: "The boy read the book." },
      { title: "Subject agreement and omitted pronouns", body: cited("A complete verb often tells you who acts. እሄዳለሁ already means “I go” or “I will go.” Add the separate word እኔ when you need to emphasize “I” against someone else.", "leslau", "wiki-amharic"), example: "(እኔ) ነገ እሄዳለሁ። ((Əne) nägä əhedallähu.)", exampleTranslation: "I will go tomorrow." },
      { title: "The negative frame", body: cited("Many negative verbs put al- at the beginning and -m at the end. These two pieces surround the rest of the verb like brackets. Listen to a positive and negative pair together so you can hear how fast speech compresses them.", "leslau"), example: "አልገባኝም። (Algäbaññəm.)", exampleTranslation: "I don't understand. (Literally, it did not enter me.)" },
      { title: "Possession on the noun", body: cited("A noun ending can tell you who owns something: ቤቴ bete means “my house.” To name another owner, Amharic often puts that person before the noun with a yä- link. Watch how one short word can hold both the thing and its owner.", "leslau", "relative-clauses"), example: "ይህ ቤቴ ነው። (Yəh bete näw.)", exampleTranslation: "This is my house." },
      { title: "Relative clauses before the noun", body: cited("Amharic puts “that I bought” before “book.” The describing verb begins with yä- and can include pieces for its subject and object. Read the buying event first, then the noun it describes.", "relative-clauses", "dependency-grammar"), example: "የገዛሁት መጽሐፍ ጥሩ ነው። (Yägäzzahut mäṣḥaf ṭəru näw.)", exampleTranslation: "The book that I bought is good." },
      { title: "Object suffixes on verbs", body: cited("The verb አየሁት ayähut means “I saw him” or “I saw it.” Its ending points to a third-person masculine object, while another piece shows “I.” Learn it inside a sentence so you can see how those pieces work together.", "dependency-grammar", "wiki-amharic"), example: "ትናንት አየሁት። (Tənant ayähut.)", exampleTranslation: "I saw him yesterday." },
      { title: "Existence and possession", body: cited("To say “I have two brothers,” Amharic can say that two brothers “exist to me.” The word for their existence carries a piece meaning “to me.” This construction expresses having without an English-style “have” verb.", "leslau"), example: "ሁለት ወንድሞች አሉኝ። (Hulätt wändəmmočč alluññ.)", exampleTranslation: "I have two brothers. (Two brothers exist to me.)" },
      { title: "Polite and honorific agreement", body: cited("Amharic changes more than a pronoun when you address someone politely. Familiar አንተ antä addresses a man and አንቺ anči a woman; polite እርስዎ ərswo goes with a respectful verb form. Learn the whole greeting together rather than replacing only “you.”", "leslau"), example: "እርስዎ እንዴት ነዎት? (Ərswo endet näwot?)", exampleTranslation: "How are you? (polite)" }
    ]
  },
  whereSpoken: {
    overview: cited("Many people speak Amharic first in the Amhara Region and Addis Ababa; others use it as an additional language across Ethiopia. The 2007 national census counted mother tongues, while broad claims about everyone who can speak Amharic use a different measure. Keep the year and definition beside any speaker figure.\n\nAmharic connects people to national media and federal services. The federal government also lists Afar, Oromo, Somali, and Tigrinya as working languages, while regional governments and communities sustain other languages in public life. Migration has brought Amharic to communities abroad.", "ess-census-2007", "embassy-profile", "wiki-amharic"),
    regions: [
      { place: "Amhara Region", note: cited("A major first-language heartland with meaningful internal variation around Gojjam, Gondar, Wollo, and Shewa. Urban-rural and multilingual differences cut across these labels.", "ldc-amharic", "dialects") },
      { place: "Addis Ababa", note: cited("The capital anchors the prestige standard and brings Amharic into daily contact with Oromo and many other Ethiopian and international languages. Its speech is socially diverse, despite serving as the teaching norm.", "ldc-amharic", "oxford-handbook") },
      { place: "Across Ethiopia", note: cited("People learn Amharic for communication across regions, media, schooling, commerce, and federal services. Its reach varies. The federal government also lists four other working languages, and regional states choose their own.", "embassy-profile", "constitution") },
      { place: "Eritrea and the Horn", note: cited("Amharic may be understood or used through historical, family, media, or migration ties, but it should not be presented as Eritrea's national language. Tigrinya, Arabic, Tigre, and other languages occupy distinct roles.", "oxford-handbook") },
      { place: "Global diaspora", note: cited("Ethiopian families have brought Amharic into communities abroad. In an Ethio-Norwegian family study, children heard Amharic religious songs and attended a community church school. Such settings can support the language, though each person's listening, speaking, and reading may develop differently.", "heritage-norway") }
    ]
  },
  difficulty: {
    label: "Very demanding",
    overview: cited("An English-speaking beginner must learn a new script, ejective sounds, held consonants that the script usually hides, and verbs with many pieces. The verb often waits until the end of a sentence. These demands arrive together, so short, repeated practice helps.\n\nFidel becomes easier when you learn its families. Familiar pieces begin to stand out in long verbs too. A heritage learner or someone who knows another Ethiopian or Semitic language may start with different strengths, so use the difficulty label to plan your work rather than predict everyone's experience.", "leslau", "dd-less-common"),
    easierAspects: ["Fidel families make the inventory more systematic than its size first suggests", "Vowels are represented more explicitly than in many other Semitic writing systems", "Frequent agreement markers provide clues to who acts on whom", "A large music, television, radio, and online media world supports immersion", "Root families can make vocabulary reinforce itself once core patterns become familiar"],
    hardAspects: ["Producing ejectives without turning them into plain consonants", "Hearing gemination that normal spelling does not mark", "Remembering conventional spellings for historically distinct but merged consonants", "Unpacking nested morphology and clause-final verbs at natural speed", "Finding graded, accurately transcribed modern material with matching audio", "Navigating respectful, familiar, formal, regional, and heritage usage"],
    plateauRisks: ["Remaining dependent on inconsistent Latin transliteration", "Knowing a fidel chart but reading too little connected prose", "Memorizing a root while ignoring the actual stem and collocations speakers use", "Consuming music or television passively without replaying short scenes", "Treating all Amharic outside a textbook standard as error", "Using archaic institutional-course dialogues as the only model for present-day interaction"],
    workload: cited("Give fidel, sound, verbs, and everyday listening some attention each week. Read a few familiar words aloud daily, then replay a brief recording until you can match its consonant timing. Bring one verb and one short text to a conversation with a teacher or speaker.\n\nAn older course can supply drills, while a tutor and current media show how people speak now. Progress will vary with your starting point and access to speakers. Set separate goals for conversation, reading news, and reading literature.", "dd-less-common", "fsi", "iu-materials")
  },
  advancedLearning: {
    strategy: cited("At an intermediate level, collect complete sentences instead of isolated verb tables. For each verb, mark its root, subject, object, negative pieces, and whether the action is finished or ongoing. Compare a headline, a broadcast report, and a friend's retelling of the same event.\n\nAsk a tutor to mark held consonants in audio because fidel rarely shows them. If you grew up hearing Amharic, check your reading and speaking separately; strong listening does not always mean the same level in writing.", "leslau", "caco"),
    mediaPractice: cited("Choose one familiar kind of program first. Cooking videos let you see the actions, while news intros repeat public vocabulary and interviews show respectful address. Take a short clip, write what you hear in fidel, check the caption with a speaker if you can, then say it back.\n\nCompare Addis Ababa broadcasters with regional and diaspora voices. Religious programs can offer rich language, but note when a speaker quotes Geʽez or uses words specific to a faith tradition. That keeps a specialized register in its setting.", "iu-materials", "caco"),
    dictionariesAndCorpora: cited("Kane's Amharic–English Dictionary gives detailed entries, but some spellings and examples need a current-usage check. Leslau's grammar can explain a difficult verb form. Neither tells you by itself which expression your friends would choose.\n\nThe Contemporary Amharic Corpus holds about 24 million automatically tagged words from edited and web text. Search it for a word's neighbors, then check the full sentence and date. Its tags can be wrong, so compare the result with current media or a speaker.", "kane-dictionary", "leslau", "caco"),
    resources: [
      { type: "other", title: "Discover Discomfort: Less-Common Language Learning Resources", url: "https://discoverdiscomfort.com/less-common-language-learning-resources/", level: "all", description: cited("A practical framework for assembling a learning system when one polished app does not cover the language: institutional courses, tutors, dictionaries, and community media each solve different problems.", "dd-less-common") },
      { type: "course", title: "FSI Amharic Basic Course", url: "https://www.fsi-language-courses.org/fsi-amharic-basic-course/", level: "beginner", description: cited("An archive of structured lessons and audio. Some dialogues and social framing are dated; use the pronunciation drills with feedback from a present-day speaker.", "fsi") },
      { type: "other", title: "Indiana University Amharic Language Materials", url: "https://cle.indiana.edu/web-images/celt-materials.html", level: "all", description: cited("A university language-materials portal listing Amharic within its African Studies holdings and audio-visual archive.", "iu-materials") },
      { type: "book", title: "Reference Grammar of Amharic", url: "https://glottolog.org/resource/reference/id/69646", level: "advanced", description: cited("Wolf Leslau's comprehensive reference for the phonology, morphology, syntax, and examples that compact learner guides necessarily simplify.", "leslau") },
      { type: "corpus", title: "Contemporary Amharic Corpus (CACO)", url: "https://www.findke.ovgu.de/en/Research/Data+Sets/Contemporary+Amharic+Corpus+(CACO).html", level: "advanced", description: cited("A research corpus of about 24 million orthographic tokens with automatic morphosyntactic annotation and downloadable data.", "caco") },
      { type: "other", title: "Ethiopic (Amharic) Orthography Notes", url: "https://r12a.github.io/scripts/ethi/am.html", level: "intermediate", description: cited("A current, highly visual reference for characters, punctuation, line breaking, typography, and Unicode behavior in modern Amharic.", "w3c-ethiopic") }
    ]
  },
  wordsAndTexts: {
    overview: cited("A greeting can tell you about the relationship between speakers. ደህና dehna appears in greetings and farewells, while እንኳን ደህና መጡ ənkwan dehna mäṭṭu welcomes someone respectfully. አይዞህ ayzoh encourages a man; another form addresses a woman.\n\nThe word ቡና buna means “coffee,” but coffee conversation includes invitations and time together as well as the drink. Ask when someone uses a phrase and what reply they expect. That will teach you more than a single English gloss.", "leslau", "wiki-amharic"),
    notableWords: [
      { term: "ሰላም", transliteration: "sälam", meaning: "peace; hello", note: cited("A greeting and a word for peace with recognizable Semitic relatives. Its familiarity should not tempt learners to flatten every religious or social use into English ‘hi.’", "wiki-amharic") },
      { term: "ቡና", transliteration: "buna", meaning: "coffee", note: cited("An ordinary drink word embedded in one of Ethiopia's most internationally visible hospitality traditions. The language of preparation and invitation is as valuable as the noun.", "wiki-amharic") },
      { term: "እንጀራ", transliteration: "ənjära", meaning: "injera; by extension livelihood in some contexts", note: cited("The staple flatbread also participates in expressions about earning one's living. English ‘injera’ captures the food but not every figurative extension.", "leslau") },
      { term: "ደህና", transliteration: "dähna", meaning: "well; safe; fine", note: cited("A small word that powers greetings, farewells, reassurance, and questions about well-being. Learn it through whole exchanges.", "leslau") },
      { term: "አይዞህ", transliteration: "ayzoh", meaning: "take heart; hang in there (to a man)", note: cited("An encouraging formula whose ending changes with the addressee. Depending on the moment it can console, embolden, or acknowledge effort.", "leslau") },
      { term: "ፍቅር", transliteration: "fəqər", meaning: "love", note: cited("A productive literary and everyday word found in names, song titles, religious language, and ordinary statements of affection.", "wiki-amharic") },
      { term: "ትዕግሥት", transliteration: "təʿgəśt", meaning: "patience; endurance", note: cited("Its spelling preserves learned distinctions and its use ranges from an abstract virtue to a common personal name.", "w3c-ethiopic") },
      { term: "እሺ", transliteration: "əši", meaning: "okay; all right; yes in acknowledgment", note: cited("A high-frequency interaction word. Its intonation can signal willing agreement, reluctant acceptance, transition, or ‘I hear you.’", "leslau") }
    ],
    loanwordLayers: cited("Amharic keeps inherited Ethio-Semitic roots and draws learned words from Geʽez, especially in religious and literary writing. Cushitic and other Ethiopian languages have shaped its vocabulary over long periods of contact. Arabic came through trade and scholarship, Italian through a period of occupation and urban contact, and English through education and technology.\n\nA speaker may choose different words for a family conversation, a sermon, or a technical report. Check the audience and setting before calling one option more natural. A word's origin can explain a text without sorting living vocabulary into pure and impure parts.", "oxford-handbook", "wiki-amharic"),
    idioms: [
      { original: "የአይን አውጣ", transliteration: "yä-ayən awṭa", translation: "shameless; brazen", note: "Literally evokes someone who has ‘taken out the eye,’ a vivid way of describing behavior unrestrained by social regard." },
      { original: "ሆድና ጀርባ መሆን", transliteration: "hod-na järba mä-hon", translation: "to become enemies; to be completely at odds", note: "Literally, to be belly and back: two sides that cannot face the same direction." },
      { original: "እጅና ጓንት", transliteration: "əj-na gwant", translation: "inseparable; closely matched", note: "Literally ‘hand and glove,’ used for people or things that fit together closely." },
      { original: "አፍ አውጥቶ መናገር", transliteration: "af awṭto mänagär", translation: "to say something openly and plainly", note: "Literally, to bring out one's mouth and speak: a way to describe finally saying something openly." },
      { original: "ውሃ ቅዳ ውሃ መልስ", transliteration: "wuha qədda, wuha mälləs", translation: "futile, repetitive work", note: "Literally ‘draw water, return water’: effort that merely undoes itself. Exact use and wording can vary, so confirm with your speech community." }
    ],
    textGenres: ["Qəne learned poetry, church commentary, and Geʽez-influenced religious writing", "Royal chronicles, historical narratives, lives, and manuscript traditions", "Modern novels, short stories, plays, memoirs, essays, and children's books", "Newspapers, political commentary, public notices, and long-form journalism", "Azmari performance, popular song, hip-hop, gospel, liturgical music, and music video", "Cinema, television drama, comedy, dubbed media, radio, podcasts, and online interviews", "Diaspora literature, heritage-school texts, social video, memes, and multilingual digital writing"]
  },
  relationships: { overview: cited("Amharic belongs to the Ethio-Semitic group, with Argobba as a close relative. Tigrinya and Geʽez share deeper family history, while Arabic and Hebrew are more distant Semitic relatives.\n\nOromo and Agaw languages belong to the Cushitic branch of Afro-Asiatic; speakers have shaped one another's languages through contact. Sharing fidel does not prove two languages are close relatives, and using different scripts does not erase a family link. Ask separately about ancestry, borrowing, writing, and daily bilingualism.", "glottolog", "oxford-handbook", "unicode-ethiopic"), languages: relatedLanguages },
  culturalNotes: "Amharic has different roles for different speakers: home language, shared language, federal working language, or heritage language. Some people also connect it with unequal state power. Ask which languages a person uses instead of guessing from their name, religion, or birthplace.\n\nFamiliar and polite forms of address carry relationships. Listen for kin terms, professional titles, and respectful እርስዎ before choosing how to address someone. Keep the spelling a person uses for their name; Latin renderings vary, and many Ethiopian names do not follow a Western inherited-surname pattern.\n\nLook beyond a single image of a coffee ceremony. Amharic appears in novels, music, comedy, cinema, journalism, religious writing, and public debate. Those genres show different voices and histories.",
  resources: [
    { type: "other", title: "Discover Discomfort: Less-Common Language Learning Resources", url: "https://discoverdiscomfort.com/less-common-language-learning-resources/", level: "all", description: cited("A candid resource-building strategy applicable to Amharic's mix of excellent older references and dispersed modern media.", "dd-less-common") },
    { type: "course", title: "FSI Amharic Basic Course", url: "https://www.fsi-language-courses.org/fsi-amharic-basic-course/", level: "beginner", description: cited("Extensive lessons and audio best mined for sound and structure while a modern tutor updates usage and context.", "fsi") },
    { type: "other", title: "Indiana University Language Materials", url: "https://cle.indiana.edu/web-images/celt-materials.html", level: "all", description: cited("A university portal to archived Amharic and other African-language learning media.", "iu-materials") },
    { type: "book", title: "Reference Grammar of Amharic", url: "https://glottolog.org/resource/reference/id/69646", level: "advanced", description: cited("The major detailed grammatical reference to consult after a learner explanation raises a harder question.", "leslau") },
    { type: "corpus", title: "Contemporary Amharic Corpus", url: "https://www.findke.ovgu.de/en/Research/Data+Sets/Contemporary+Amharic+Corpus+(CACO).html", level: "advanced", description: cited("A large downloadable, automatically annotated text collection for research into forms and collocations.", "caco") },
    { type: "other", title: "Ethiopic Script Resources", url: "https://www.w3.org/TR/ethi-lreq/", level: "intermediate", description: cited("W3C guidance connecting Amharic orthography with practical digital layout, characters, punctuation, and typographic support.", "w3c-ethiopic") }
  ],
  relatedLanguages,
  phrases: [
    { original: "ሰላም", transliteration: "sälam", translation: "Hello; peace.", usageNote: "Broad and neutral; more elaborate greetings vary with time, relationship, and region." },
    { original: "እንዴት ነህ?", transliteration: "endet näh?", translation: "How are you?", usageNote: "Familiar, addressed to a man. To a woman: እንዴት ነሽ? endet näš?" },
    { original: "እንዴት ነዎት?", transliteration: "endet näwot?", translation: "How are you?", usageNote: "Polite or respectful." },
    { original: "ደህና ነኝ።", transliteration: "dähna näññ", translation: "I'm well." },
    { original: "አመሰግናለሁ።", transliteration: "amäsäggənallähu", translation: "Thank you." },
    { original: "እባክህ", transliteration: "əbbakəh", translation: "Please.", usageNote: "To a man. To a woman use እባክሽ əbbakiš; polite/plural እባክዎ əbbakwo." },
    { original: "ይቅርታ", transliteration: "yəqərta", translation: "Excuse me; sorry." },
    { original: "አልገባኝም።", transliteration: "algäbaññəm", translation: "I don't understand.", literalMeaning: "It did not enter me." },
    { original: "እንደገና ይናገሩ።", transliteration: "əndägäna yənagäru", translation: "Please say it again.", usageNote: "Polite request." },
    { original: "ቀስ ብለው ይናገሩ።", transliteration: "qäs bəläw yənagäru", translation: "Please speak slowly.", usageNote: "Polite; literally asks the person to speak ‘slowly.’" },
    { original: "አማርኛ እየተማርኩ ነው።", transliteration: "amarəñña əyyätämarku näw", translation: "I am learning Amharic." },
    { original: "ይህ ምን ማለት ነው?", transliteration: "yəh mən malät näw?", translation: "What does this mean?" },
    { original: "ስንት ነው?", transliteration: "sənt näw?", translation: "How much is it?; how many is it?", usageNote: "Context supplies the item or quantity." },
    { original: "እሺ", transliteration: "əši", translation: "Okay; all right." },
    { original: "ደህና ሁን", transliteration: "dähna hun", translation: "Goodbye; be well.", usageNote: "Familiar to a man; forms change for a woman, a group, or respectful address." },
    { original: "እንኳን ደህና መጡ", transliteration: "ənkwan dähna mäṭṭu", translation: "Welcome.", usageNote: "Respectful/plural welcome formula." }
  ],
  sources: [
    { id: "dd-less-common", title: "Best Less-Common Language Learning Resources: What Actually Works", url: "https://discoverdiscomfort.com/less-common-language-learning-resources/", publisher: "Discover Discomfort", accessedAt: "2026-07-10" },
    { id: "wiki-amharic", title: "Amharic", url: "https://en.wikipedia.org/wiki/Amharic", publisher: "Wikipedia", accessedAt: "2026-07-10" },
    { id: "glottolog", title: "Glottolog: Amharic", url: "https://glottolog.org/resource/languoid/id/amha1245", publisher: "Glottolog", updatedAt: "2026", accessedAt: "2026-07-10" },
    { id: "constitution", title: "Constitution of the Federal Democratic Republic of Ethiopia, Article 5", url: "https://www.servat.unibe.ch/icl/et00000_.html", publisher: "International Constitutional Law Project, University of Bern", publishedAt: "1995", accessedAt: "2026-07-10" },
    { id: "embassy-profile", title: "Country Profile: Federal Working Languages", url: "https://ethiopianembassy.be/?page_id=2854", publisher: "Embassy of Ethiopia in Belgium", accessedAt: "2026-09-27" },
    { id: "ess-census-2007", title: "Statistical Report on Population and Housing Census Country Level 2007", url: "https://ess.gov.et/download/population-and-housing-census-2007-national_statistical/", publisher: "Ethiopian Statistics Service", publishedAt: "2007", accessedAt: "2026-09-27" },
    { id: "heritage-norway", title: "The Home Literacy Environment as a Venue for Fostering Bilingualism and Biliteracy: The Case of an Ethio-Norwegian Bilingual Family in Oslo, Norway", url: "https://journals.sagepub.com/doi/10.1177/14687984221109415", publisher: "Journal of Early Childhood Literacy", publishedAt: "2025", accessedAt: "2026-09-27" },
    { id: "kane-dictionary", title: "Kane: Amharic-English Dictionary", url: "https://glottolog.org/resource/reference/id/22493", publisher: "Glottolog bibliographic record", publishedAt: "1990", accessedAt: "2026-09-27" },
    { id: "language-policy", title: "Language Law and Policy of the Federal Government of Ethiopia", url: "https://doi.org/10.32566/ah.2021.1.4", publisher: "ACTA HUMANA", publishedAt: "2021", accessedAt: "2026-07-10" },
    { id: "oxford-handbook", title: "The Oxford Handbook of Ethiopian Languages", url: "https://academic.oup.com/edited-volume/46265", publisher: "Oxford University Press", publishedAt: "2023", accessedAt: "2026-07-10" },
    { id: "unicode-ethiopic", title: "The Unicode Standard, Chapter 19: Ethiopic", url: "https://www.unicode.org/versions/Unicode17.0.0/core-spec/chapter-19/", publisher: "Unicode Consortium", updatedAt: "2025", accessedAt: "2026-07-10" },
    { id: "w3c-ethiopic", title: "Ethiopic Script Resources and Amharic Orthography Notes", url: "https://www.w3.org/TR/ethi-lreq/", publisher: "W3C Internationalization Working Group", updatedAt: "2026-04-27", accessedAt: "2026-07-10" },
    { id: "ldc-amharic", title: "Language Specific Peculiarities Document for Amharic as Spoken in Ethiopia", url: "https://catalog.ldc.upenn.edu/docs/LDC2019S22/LSP_307_performer09292015.pdf", publisher: "Linguistic Data Consortium, University of Pennsylvania", publishedAt: "2015", accessedAt: "2026-07-10" },
    { id: "dialects", title: "Differences between the Amharic Dialects of Gondar and Addis Ababa", url: "https://cris.tau.ac.il/en/publications/differences-between-the-amharic-dialects-of-gondar-and-addis-abab/", publisher: "Curzon / Tel Aviv University research portal", publishedAt: "1999", accessedAt: "2026-07-10" },
    { id: "leslau", title: "Reference Grammar of Amharic", url: "https://glottolog.org/resource/reference/id/69646", publisher: "Harrassowitz", publishedAt: "1995", accessedAt: "2026-07-10" },
    { id: "relative-clauses", title: "On Amharic Relative Clauses", url: "https://www.cambridge.org/core/services/aop-cambridge-core/content/view/6941FB3A570E4EB9F8D482DB296AE3D3/S0041977X00121135a.pdf/on_amharic_relative_clauses1.pdf", publisher: "Bulletin of the School of Oriental and African Studies", accessedAt: "2026-07-10" },
    { id: "dependency-grammar", title: "A Dependency Grammar for Amharic", url: "https://web.stanford.edu/group/cslipublications/cslipublications/LFG/7/pdfs/lfg02.pdf", publisher: "CSLI Publications, Stanford University", publishedAt: "2002", accessedAt: "2026-07-10" },
    { id: "caco", title: "Contemporary Amharic Corpus (CACO)", url: "https://www.findke.ovgu.de/en/Research/Data+Sets/Contemporary+Amharic+Corpus+(CACO).html", publisher: "Otto von Guericke University Magdeburg", updatedAt: "2019-11-26", accessedAt: "2026-07-10" },
    { id: "iu-materials", title: "Language Learning Materials", url: "https://cle.indiana.edu/web-images/celt-materials.html", publisher: "Indiana University Center for Language Excellence", accessedAt: "2026-07-10" },
    { id: "fsi", title: "FSI Amharic Basic Course", url: "https://www.fsi-language-courses.org/fsi-amharic-basic-course/", publisher: "Foreign Service Institute course archive", accessedAt: "2026-07-10" }
  ],
  seo: { title: "Amharic Language Guide: Fidel, Grammar, History and Phrases", description: "A deeply researched guide to Amharic pronunciation, Ethiopic fidel, Semitic verb structure, regional and social variation, practical phrases, literature, media, and learning resources." }
} satisfies LanguageGuide;
