import { cited } from "../citations.js";
import type { LanguageGuide } from "../types.js";

const relatedLanguages = [
  { name: "Samoan", slug: "samoan", relationship: "Polynesian relative", explanation: cited("Māori and Samoan belong to the Polynesian branch of Austronesian, so some basic words and grammatical habits share older roots. They developed in different parts of the Pacific, and neither language is simply a regional form of the other. Their present-day speakers do not gain automatic conversational understanding from that family connection.", "abvd", "wiki-maori") },
  { name: "Hawaiian", relationship: "Eastern Polynesian relative", explanation: cited("Hawaiian and Māori share a closer Eastern Polynesian ancestry. Comparisons such as Māori aroha and Hawaiian aloha can help reveal a historical sound correspondence, but familiar-looking words do not erase differences in pronunciation, meaning, or modern cultural use.", "abvd", "wiki-maori") },
  { name: "Tagalog", slug: "tagalog", relationship: "Distant Austronesian relative", explanation: cited("Tagalog and Māori sit on widely separated branches of the Austronesian family. Comparing them shows how far the family extends, from the Philippines across the Pacific, but a learner should not expect Tagalog vocabulary or sentence patterns to transfer directly into Māori conversation.", "abvd", "glottolog") },
  { name: "Indonesian", slug: "indonesian", relationship: "Distant Austronesian relative", explanation: cited("Indonesian belongs to the same enormous family, but its history in Island Southeast Asia and its modern national standard are distinct from Māori. A shared family label is a historical relationship, not a practical shortcut to understanding either language.", "abvd", "glottolog") }
] satisfies LanguageGuide["relationships"]["languages"];

export const maoriGuide = {
  slug: "maori",
  name: "Māori",
  autonym: "te reo Māori",
  status: "published",
  publishedAt: "2026-09-27",
  summary: "Māori is the Indigenous Polynesian language of Aotearoa New Zealand. It lives in homes, marae, schools, broadcasting, writing, and public life, with revitalization led by Māori communities.",
  family: "Austronesian, Malayo-Polynesian, Polynesian, Eastern Polynesian",
  macroRegion: "Aotearoa New Zealand and Māori communities abroad",
  primaryScript: "Latin alphabet with macrons",
  difficultyLabel: "Demanding",
  learnerHook: "Māori gives learners a way to understand place names, family relationships, and everyday conversations in Aotearoa through the words chosen by its speakers.",
  hero: { imageAlt: "Māori language books and handwritten text beside a recording of spoken te reo Māori.", callToActionLabel: "Hear te reo Māori" },
  classification: "An Eastern Polynesian Austronesian language and the Indigenous language of Māori in Aotearoa New Zealand",
  speakerCommunity: "Te reo Māori is spoken by Māori communities across Aotearoa New Zealand and by families abroad. The 2023 New Zealand census recorded 213,849 people who reported speaking Māori, about 4.3 percent of the country's population. This is a census response about language ability, not a count of daily users, first-language speakers, or Māori people as a whole.\n\nThe language serves family life, ceremonies on marae, schools, radio, television, literature, and increasingly digital communication. Speakers differ in fluency, dialect, age, and learning history. Some grew up speaking Māori at home; others have reclaimed it as adults, often alongside English.",
  facts: [
    { label: "Family", value: "Austronesian · Polynesian · Eastern Polynesian" },
    { label: "2023 census", value: "213,849 people reported speaking Māori in Aotearoa New Zealand" },
    { label: "Home", value: "Aotearoa New Zealand, including urban and rural communities" },
    { label: "Writing", value: "Latin letters; macrons mark long vowels" },
    { label: "Public status", value: "Official language of New Zealand" },
    { label: "Signature grammar", value: "Tense and aspect particles, inclusive pronouns, and distinct possessive patterns" }
  ],
  introduction: cited("Māori, or te reo Māori, is the Indigenous language of Māori in Aotearoa New Zealand. It is heard in homes, on marae, in schools, and across radio and television, as well as in the communities Māori have built abroad. In the 2023 New Zealand census, 213,849 people reported speaking Māori; the figure records a census response, not how many people use it every day.\n\nMāori belongs to the Polynesian branch of the Austronesian language family. That makes it a relative of languages such as Samoan and Hawaiian, although each has its own history and speech community. A learner will encounter familiar-looking place names and words like whānau and kia ora, then discover a language with its own sound system, grammar, and ways of speaking to different people.\n\nMāori communities have sustained and renewed the language through family transmission, immersion education, broadcasting, and public advocacy. The 1987 Māori Language Act recognized it as an official language; a 2016 act restated its status and the role of iwi and Māori in its revitalization. Those efforts have made te reo Māori visible in more settings while leaving the daily work of learning and passing it on firmly with speakers and communities.", "stats", "teara", "act", "glottolog", "wiki-maori"),
  origins: {
    overview: cited("Māori developed from the Polynesian languages brought by the ancestors of Māori to Aotearoa. Linguists place it in Eastern Polynesian, within a much wider Austronesian family stretching across Island Southeast Asia and the Pacific. The language was established in Aotearoa before European settlement, with regional speech traditions tied to whakapapa, place, and iwi.\n\nEuropean arrival brought new trade, religion, schooling, and printed texts. Missionaries and Māori writers used the Latin alphabet for books and newspapers, while English gained power through colonial institutions. The language's later decline was closely connected with policies and social pressures favoring English, rather than a lack of expressive range in Māori.", "abvd", "teara", "wiki-maori"),
    timeline: [
      { period: "Before European settlement", event: cited("Polynesian settlers established communities in Aotearoa and their language developed into Māori. Oral forms such as whakapapa, waiata, and formal speech carried knowledge across generations and places.", "teara", "wiki-maori") },
      { period: "19th century", event: cited("Māori writers and printers made extensive use of books, letters, and newspapers; the first Māori-language newspaper appeared in 1842. English spread through colonial government and schools, especially after English became the dominant medium of instruction.", "teara", "teara-writing") },
      { period: "1970s–1980s", event: cited("The 1972 petition for Māori-language teaching became a landmark in public advocacy. Kōhanga reo language nests began in 1982, followed by Māori-medium schooling, and Parliament recognized Māori as an official language in 1987.", "teara", "act") },
      { period: "2000s–present", event: cited("Māori Television began broadcasting in 2004, and the Te Reo channel followed in 2008. The Māori Language Act 2016 reaffirmed official status and created a framework that recognizes iwi and Māori leadership as well as Crown responsibilities.", "teara", "act", "maoriplus") }
    ],
    contactHistory: cited("English is the strongest modern contact language. Māori speakers may use both languages in a conversation, and English has borrowed Māori words such as whānau, mana, and kia ora into wider New Zealand use. These borrowings can lose nuance if treated as exact one-word English equivalents.\n\nMāori has also adapted borrowed vocabulary for changing institutions and technologies. Borrowing does not make a language less Indigenous or less systematic: speakers choose, reshape, and sometimes coin words as new needs arise. Older written records can show forms or spellings that differ from the conventions used in current teaching material.", "teara", "tetaurawhiri", "wiki-maori"),
    standardization: cited("Printed Māori grew through work by Māori authors, translators, teachers, and editors, not through one founding decree. A written standard supports schooling and public communication, but it does not cancel local pronunciation or vocabulary. Macrons now commonly mark long vowels; the Māori Language Commission recommends using them.\n\nOfficial-language recognition has never meant that every person in Aotearoa speaks Māori. Current revitalization depends on spaces in which people can learn, hear, and use it with confidence, including whānau and iwi initiatives, schools, broadcasters, and workplaces. The 2016 legislation explicitly treats te reo Māori as a taonga of iwi and Māori.", "teara", "act", "tki", "tetaurawhiri")
  },
  variants: {
    overview: cited("Māori is often taught through a broadly shared written form, yet speakers bring regional histories into pronunciation, vocabulary, and usage. A learner may hear a familiar word said differently on another marae or encounter a term particular to an iwi. Asking which community a speaker learned from gives you a better model than ranking regional forms as correct and incorrect.\n\nFormality also matters. A television interview, a conversation among relatives, a school lesson, and a formal address on a marae use different language and expectations. Learners should identify the setting before copying a phrase from it.", "teara", "wiki-maori"),
    items: [
      { name: "Eastern North Island traditions", note: cited("Iwi of the eastern North Island preserve local vocabulary and sound patterns. Regional differences are a living part of speech, and a form heard in one community may not be the best model for every other community.", "teara", "wiki-maori") },
      { name: "Western and northern North Island traditions", note: cited("Communities in the west and north use their own lexical and pronunciation traditions. A national classroom resource can introduce common patterns, while local teachers and speakers show how they are used where they live.", "teara", "wiki-maori") },
      { name: "Southern traditions", note: cited("South Island Māori speech is associated with distinctive regional forms, including pronunciations and words linked to particular places. Written public Māori can hide differences that become clearer in local conversation and oral history.", "teara", "wiki-maori") },
      { name: "Contemporary urban and learner speech", note: cited("People who grew up in towns and cities may draw on several iwi connections, classrooms, media, and family speech. Adult learners often meet a standard form first and then build understanding of local and ceremonial practice through relationships with speakers.", "teara", "tetaurawhiri") }
    ]
  },
  pronunciation: {
    overview: cited("Māori spelling gives a learner a helpful start, but reading letters as English usually changes the sound. The five vowel qualities are pronounced more consistently than English vowel letters, and a macron changes vowel length. Listen to a speaker as you learn each word, especially where vowels meet.\n\nThe two-letter spellings ng and wh each represent a sound pattern to learn as a unit. Regional variation affects some pronunciations, particularly wh. A careful learner listens to local speakers rather than insisting on one English approximation.", "massey", "tki", "wiki-maori"),
    script: "Latin alphabet with macrons for long vowels",
    soundSystem: cited("The core vowels are a, e, i, o, and u; each can be short or long. A macron marks the long form, as in Māori and whānau. Māori does not use the full set of English consonant sounds, so an English accent may add sounds that are not present in a word.\n\nThe written ng corresponds to a single velar nasal, like the final sound of English sing, and it can begin a Māori word. The spelling wh has regional pronunciations; an English f-like sound is a common learner starting point, not a universal transcription. R is tapped rather than the usual English r.", "massey", "wiki-maori"),
    prosody: cited("Keep vowels audible and give a long vowel its full length. English speakers often weaken an unstressed vowel or rush two vowels into one; that can blur a Māori word. Listen for the rhythm of whole phrases, including particles such as kei te and kua, instead of stressing every word equally.\n\nSome written forms contain adjacent vowels that should not be turned into an English diphthong automatically. Audio examples from Māori teachers provide a better model than letter-by-letter guesses. Regional speech can have its own timing and melody.", "massey", "tki"),
    learnerTraps: ["Ignoring macrons and therefore changing vowel length", "Pronouncing ng as two consonants", "Using one English pronunciation of wh for every region", "Replacing the tapped r with a strong English r", "Reducing written vowels to English schwa"],
    sampleWords: [
      { original: "Māori", translation: "Māori; Indigenous people or language of Aotearoa", note: "The ā is long. Hear the whole word from a speaker instead of reading it as an English word." },
      { original: "whānau", translation: "family; extended family", note: "Keep the long ā; wh is learned from the speech community you are listening to." },
      { original: "ngā", translation: "the, plural", note: "Begins with a single ng sound and has a long vowel." },
      { original: "kōrero", translation: "speak; speech; conversation", note: "The first vowel is long, and r has a light tap." },
      { original: "aroha", translation: "love; compassion", note: "Pronounce each written vowel instead of reducing the middle of the word." },
      { original: "tēnā", translation: "that near you; greeting element", note: "Both macrons matter in the written form." }
    ]
  },
  writing: {
    overview: cited("Māori is normally written in Latin letters. Modern edited texts generally mark long vowels with macrons: a and ā are different written forms, and the same distinction applies to e, i, o, and u. The Commission recommends macrons, and many keyboards support them directly.\n\nLearners can read a great deal with a small alphabet, but familiar letters still require Māori pronunciation. A historical text may omit macrons or use conventions from its own time. Compare it with a current dictionary before assuming a word has changed meaning.", "tki", "massey", "teara-writing"),
    primaryScript: "Latin alphabet with macrons",
    romanization: cited("Māori already uses a Latin-based spelling, so no separate romanization is needed. Pronunciation guides that replace Māori sounds with English-looking syllables are rough aids only; preserve the original spelling, including macrons, when taking notes or sharing a phrase.", "tki", "massey"),
    spellingNorms: cited("Five vowel letters each have a long counterpart marked by a macron. The digraphs ng and wh function as units in reading and alphabetic teaching. Correct macrons make names and dictionary searches clearer, and dropping them may blur distinct words.\n\nCapitalization and punctuation largely follow modern print conventions, but names and institutional preferences deserve checking. An older archive may show double vowels or unmarked length. Use the form preferred by a community or current authoritative resource for contemporary work.", "tki", "tetaurawhiri"),
    styleNotes: [
      cited("Keep macrons in Māori names and words when the source supplies them; do not silently remove them for an English-language page or search field.", "tki"),
      cited("Treat ng and wh as Māori spelling units rather than as two unrelated English letters; audio should guide the sound.", "massey"),
      cited("Older newspapers and archival documents may use spelling conventions different from modern teaching material. Quote the original faithfully and explain it if the contrast matters.", "teara-writing")
    ]
  },
  grammar: {
    overview: cited("A Māori sentence often starts with a small word or phrase that tells you what kind of statement follows. Kei te, kua, i, and other particles help place an action in time or show how it is unfolding. The main verb does not change the way an English verb changes from go to went.\n\nNouns and pronouns carry equally important choices. Māori distinguishes one, two, and more than two people in parts of its pronoun system, and it distinguishes a group that includes the listener from one that does not. Learn these forms in a complete exchange, because their choice changes who is invited into the sentence.", "kupu-active", "kupu-pronouns"),
    typologicalProfile: cited("Māori commonly puts a tense or aspect marker and verb before the subject: Kei te haere au ki te hui means ‘I am going to the meeting.’ It also has many nonverbal patterns for describing identity, location, possession, and qualities. An English word-for-word order is therefore a poor guide to natural Māori.\n\nThe markers around nouns also matter. Te refers to a singular definite noun and ngā to a plural one. A demonstrative can locate a thing relative to speaker and listener: He pukapuka tēnei means ‘This is a book.’", "kupu-active", "kupu-demonstratives"),
    morphology: cited("Māori verbs do not take English-style endings for person. Compare Kei te haere au ‘I am going,’ I haere au ‘I went,’ and Kua haere au ‘I have gone.’ The particle changes while haere stays recognizable.\n\nKa has several uses, including a next action in a narrative; it should not be memorized as a one-to-one English future tense.\n\nPassive forms can change the verb: hanga ‘build’ appears as hangaia in Kua hangaia te marae e ngā tohunga, ‘The marae has been built by experts.’ Passive endings differ by root, so copying -ia onto every verb will fail. A dictionary and recorded examples help confirm common forms.", "kupu-active", "kupu-passive"),
    syntax: cited("Pronouns keep track of number and inclusion. Tāua means ‘we two, including you,’ while māua means ‘we two, excluding you’; tātou and mātou extend the distinction to groups of three or more. A speaker choosing one of these words tells the listener whether they belong in the group.\n\nPossession has forms traditionally described as a and o categories. Tāku and tōku can both translate as ‘my,’ but the relationship to the thing possessed differs. The distinction cannot be reduced to a tidy English ownership rule; learn examples such as tō ingoa ‘your name’ as whole expressions and revisit the pattern as your vocabulary grows.", "kupu-pronouns", "kupu-possession"),
    advancedPainPoints: ["Choosing the correct tense or aspect construction from context", "Learning passive forms with each verb rather than applying one ending everywhere", "Using a- and o-category possessives in natural relationships", "Keeping inclusive and exclusive pronouns straight in real conversation", "Following local vocabulary and formal speech beyond classroom dialogue"],
    topics: [
      { title: "Action and time markers", body: cited("Kei te haere au ki te hui says ‘I am going to the meeting.’ Change the opening particle and the same verb can express a past event or a completed state: I haere au and Kua haere au. Start with common full sentences, then notice what the particle contributes rather than attaching an English tense label to the verb alone.", "kupu-active"), example: "Kei te haere au ki te hui.", exampleTranslation: "I am going to the meeting." },
      { title: "Inclusive and exclusive we", body: cited("If a speaker says tātou, the listener is included in a group of three or more; mātou excludes the listener. For exactly two, the corresponding forms are tāua and māua. This is a practical social distinction: an invitation or plan can change meaning if the wrong pronoun is used.", "kupu-pronouns"), example: "Mā tātou katoa tēnei mahi.", exampleTranslation: "This work is for all of us, including you." },
      { title: "Possessive relationships", body: cited("Māori possession has a and o categories, visible in forms such as tāku and tōku. The choice relates to how the possessor stands in relation to what is possessed, with conventional patterns that deserve examples rather than a blanket English rule. Tō ingoa means ‘your name’; check a good grammar or speaker when a new noun does not fit an easy mnemonic.", "kupu-possession"), example: "Ko wai tō ingoa?", exampleTranslation: "What is your name?" },
      { title: "Location and demonstratives", body: cited("Tēnei points to something near the speaker, tēnā near the listener, and tērā farther from both. These words can stand in a complete statement: He pukapuka tēnei, ‘This is a book.’ When asking where someone is, learn a full model like Kei te kāinga koe? rather than rearranging English words.", "kupu-demonstratives", "kupu-pronouns"), example: "He pukapuka tēnei.", exampleTranslation: "This is a book." },
      { title: "Negation changes the construction", body: cited("Kāore does not simply drop into every affirmative sentence without other changes. Ka haere au ki te marae can become Kāore au e haere ki te marae, ‘I will not go to the marae.’ A location statement follows a different shape: Kāore te pene i runga i te tēpu means ‘The pen is not on the table.’ Compare whole positive and negative pairs.", "kupu-negatives"), example: "Kāore au e haere ki te marae.", exampleTranslation: "I will not go to the marae." },
      { title: "Passive and agency", body: cited("Kua hanga ngā tohunga i te marae foregrounds the builders; Kua hangaia te marae e ngā tohunga foregrounds the marae that was built. The passive verb form and the phrase naming the builders both change. This pattern is common in connected speech and writing, so learn it from texts rather than treating it as a rare formal trick.", "kupu-passive"), example: "Kua hangaia te marae e ngā tohunga.", exampleTranslation: "The marae has been built by experts." }
    ]
  },
  whereSpoken: {
    overview: cited("Māori is rooted in Aotearoa, but it does not belong to just one town or one classroom. People use it in cities and rural districts, in homes, on marae, in Māori-medium education, through broadcasters, and online. Its visibility in signs or ceremonies does not tell you how often a particular household uses it.\n\nThe census figure covers people who reported speaking the language in New Zealand in 2023. It does not measure fluency in every setting, nor does it include every Māori speaker living abroad. Community-led learning and transmission remain central to its future.", "stats", "datainfo", "teara"),
    regions: [
      { place: "North Island / Te Ika-a-Māui", note: cited("Large and diverse Māori communities use the language across northern, eastern, central, and western districts. Local iwi and marae traditions give regional speech its setting, even when a learner begins with a national teaching resource.", "teara") },
      { place: "South Island / Te Waipounamu", note: cited("Māori remains connected to southern iwi, places, and families. Regional forms and historical records can differ from the variety a learner first meets in nationally distributed lessons.", "teara") },
      { place: "Urban Aotearoa", note: cited("City communities bring together people with different iwi connections and learning histories. Schools, community classes, workplaces, media, and family networks create places for speaking Māori beyond a single ancestral district.", "teara", "tetaurawhiri") },
      { place: "Māori communities abroad", note: cited("Families outside New Zealand maintain Māori through relatives, online media, teaching resources, and visits. New Zealand census totals should not be read as a world count of all people able to speak the language.", "stats", "datainfo") }
    ]
  },
  difficulty: {
    label: "Demanding",
    overview: cited("Māori gives English-speaking learners a relatively compact spelling system and many chances to hear greetings in public life. Those advantages can make the first lessons inviting. Sustained conversation takes more: vowel length, fast particles, pronoun choices, possessive categories, and the social setting of words all need attention.\n\nA learner who only memorizes signs may recognize place names but still struggle to follow a family conversation or formal speech. Regular listening with speakers and feedback on pronunciation are more valuable than racing through a list of isolated phrases.", "massey", "kupu-active", "kupu-pronouns"),
    easierAspects: ["A compact alphabet with broadly consistent sound-to-letter relationships", "Verb roots that remain recognizable across several tense and aspect constructions", "Accessible teaching media, dictionaries, and broadcast material"],
    hardAspects: ["Hearing and producing long versus short vowels", "Choosing between inclusive and exclusive pronouns", "Using a- and o-category possessives naturally", "Understanding regional and ceremonial speech beyond a standard lesson"],
    plateauRisks: ["Knowing greetings and single words without being able to build a complete sentence", "Reading only normalized text and missing the pace and variation of real speech", "Avoiding contexts where a speaker can correct your pronunciation and usage"],
    workload: cited("Begin with short daily audio and a structured course. Record your own speech, compare vowel length with a speaker's model, and learn each grammar point in a sentence you might actually use. At an intermediate stage, add regular conversations, interviews, and longer texts from one community or topic before broadening out.\n\nFluency has no fixed calendar, and a few memorized greetings are not the same as participating in a conversation. Give yourself time to learn when a phrase is informal, ceremonial, local, or tied to relationships you have not yet learned to describe.", "tewhanake", "massey", "maoriplus")
  },
  advancedLearning: {
    strategy: cited("Choose one sustained strand of speech—a series, interviews with one broadcaster, or a community class—and revisit it until you can follow whole exchanges. Keep a notebook of full clauses, not just translations of single words. Mark the speaker, setting, dialect cues, and forms you want to ask about.\n\nUse Te Whanake or a comparable sequence to fill grammar gaps, then try the same pattern in your own conversation. Work with a teacher or language partner when possible, especially for pronunciation and local usage. If you are learning a formal speech practice, follow the guidance of the community that uses it.", "tewhanake", "maoriplus", "teara"),
    mediaPractice: cited("MĀORI+ carries shows with different levels and registers, from learner-oriented Ōpaki to interviews and current affairs. Watch a short segment first for the main idea, then replay it for recurring particles, pronouns, and words. A transcript or subtitles can help, but listen again without reading to check what you actually hear.\n\nMusic, radio, and interviews show another side of the language. A song or ceremonial speech should be heard as a whole performance with a speaker and occasion, not mined for detachable slogans. Note when a source mixes Māori and English so that switching does not look like a grammar mistake.", "maoriplus", "teara"),
    dictionariesAndCorpora: cited("Te Aka gives definitions and usage examples that help distinguish related senses. Check the whole example before carrying an English gloss into a new sentence. Kupu Māori provides concise grammar explanations and paired sentence patterns; Te Whanake adds a structured path through progressively harder language.\n\nFor a disputed word, compare dictionary entries with current Māori-language media and ask a knowledgeable speaker. Older written archives are valuable, but they reflect their own region and period. Do not assume a historical spelling or translation is the only accepted present-day form.", "teaka", "kupu-active", "tewhanake", "teara-writing"),
    resources: [
      { type: "course", title: "Te Whanake", url: "https://tewhanake.maori.nz/", level: "all", description: cited("A multi-level Māori course with texts and audio. Work through whole dialogues, then use their vocabulary in your own sentences.", "tewhanake") },
      { type: "media", title: "Ōpaki on MĀORI+", url: "https://www.maoriplus.co.nz/show/opaki-he-timonga", level: "beginner", description: cited("A learner-oriented series with Pānia Papa and conversational practice; replay short scenes and imitate full exchanges.", "maoriplus") },
      { type: "dictionary", title: "Te Aka Māori Dictionary", url: "https://maoridictionary.co.nz/", level: "all", description: cited("Definitions and example sentences for checking senses and usage; look beyond the first English gloss.", "teaka") },
      { type: "other", title: "Kupu Māori grammar", url: "https://kupu.maori.nz/", level: "intermediate", description: cited("Short explanations with sentence pairs for particles, pronouns, possession, negation, and other constructions.", "kupu-active") }
    ]
  },
  wordsAndTexts: {
    overview: cited("Some Māori words are widely recognized in New Zealand English, but a borrowed English use may be narrower than the Māori word's range. Whānau can refer to family relationships broader than a small household; mana has meanings shaped by authority, standing, and context. Read such words in Māori sentences and listen to the people using them.\n\nMāori writing includes much more than labels and greetings. Newspapers, letters, songs, storytelling, educational texts, poetry, and contemporary reporting show changing voices and registers. Proverbs also draw on images such as a bird's feathers to make a point about the support people need.\n\nA learner can follow one text genre for a month and see familiar grammar doing new work.", "teaka", "teara-writing", "teara", "chch-proverb"),
    notableWords: [
      { term: "whānau", meaning: "family; extended family", note: cited("A family group can include relationships and obligations wider than an English nuclear-family gloss. Listen to who the speaker includes when they use the word.", "teaka") },
      { term: "whenua", meaning: "land; country; placenta", note: cited("The word has several senses. Its meaning in a sentence depends on context, and the range is a reminder not to reduce a culturally important word to one English label.", "teaka") },
      { term: "aroha", meaning: "love; compassion; concern", note: cited("Aroha can describe affection and care, but the best English equivalent depends on how it is used. Its resemblance to Hawaiian aloha reflects Polynesian relationship, not identical modern usage.", "teaka", "abvd") },
      { term: "mana", meaning: "authority; prestige; influence", note: cited("Mana is often borrowed into English. Read it in Māori examples and social context before choosing an English translation, since one short gloss rarely covers its uses.", "teaka") },
      { term: "marae", meaning: "communal meeting place and its associated setting", note: cited("A marae is not simply a generic hall. Its buildings, people, and protocols form a social setting in which forms of speech carry particular responsibilities.", "teara", "teaka") },
      { term: "whakapapa", meaning: "genealogy; layered relationships", note: cited("Whakapapa connects people, ancestors, and history. A learner should not treat it as a decorative synonym for an English family tree.", "teaka", "teara") },
      { term: "taonga", meaning: "treasure; valued thing", note: cited("The 2016 Māori Language Act describes te reo Māori itself as a taonga of iwi and Māori. The word can refer to more than a material object.", "act", "teaka") }
    ],
    loanwordLayers: cited("Contact with English brought new institutional and technological vocabulary, and Māori speakers have used both adapted borrowings and words formed from Māori material. The choice between a loan and a coined term can differ by speaker, topic, and time. New Zealand English in turn uses many Māori words, especially for place, people, and public life.\n\nA borrowed word in English may shift in meaning. When reading a Māori text, rely on the Māori sentence and a Māori dictionary rather than assuming the English borrowing tells the whole story. Older newspapers also show how writing and vocabulary changed with the institutions of their time.", "teara", "teaka", "teara-writing"),
    idioms: [
      { original: "Ka mau te wehi!", translation: "Fantastic! / Awesome!", note: "A lively response; context and tone can also convey alarm or amazement." },
      { original: "Kia kaha.", translation: "Be strong; keep going.", note: "An encouragement whose force depends on the person and situation." },
      { original: "He waka eke noa.", translation: "We are in this together.", note: "A proverb evoking people aboard one canoe; it can carry a shared-responsibility sense beyond this short gloss." },
      { original: "Mā te huruhuru, ka rere te manu.", translation: "With feathers, the bird will fly.", note: "A proverb often used to stress the support or resources that make an achievement possible." }
    ],
    textGenres: ["Whakapapa and oral histories shared in community settings", "Waiata, poetry, and performed language", "Nineteenth-century letters and Māori-language newspapers", "Children's books and Māori-medium school texts", "Contemporary news, interviews, and digital writing"]
  },
  relationships: {
    overview: cited("Māori belongs to Eastern Polynesian within the larger Polynesian branch of Austronesian. Hawaiian is a nearer historical relative than Samoan; Tagalog and Indonesian are much more distant members of the same broad family. These relationships help explain some inherited patterns but do not make the modern languages interchangeable.\n\nThe most important contact relationship for contemporary Māori is with English in Aotearoa. Many speakers use both, and English has borrowed Māori words that now appear on signs, in news, and in everyday conversation. Learn the Māori meanings and settings rather than expecting an English borrowing to be a complete definition.", "abvd", "glottolog", "teara", "wiki-maori"),
    languages: relatedLanguages
  },
  culturalNotes: "The language is woven into relationships with iwi, hapū, whānau, and place. Learning a greeting is a start; learning how and when a person uses it takes listening and care.",
  resources: [
    { type: "course", title: "Te Whanake", url: "https://tewhanake.maori.nz/", level: "all", description: cited("A structured sequence with course books, activities, and audio. Its levels support a move from first sentences to longer texts and conversation.", "tewhanake") },
    { type: "dictionary", title: "Te Aka Māori Dictionary", url: "https://maoridictionary.co.nz/", level: "all", description: cited("A searchable dictionary with examples. Check several senses and the sentence around a word before using it yourself.", "teaka") },
    { type: "other", title: "Kupu Māori", url: "https://kupu.maori.nz/", level: "all", description: cited("An online grammar reference with short explanations and paired examples for common sentence patterns.", "kupu-active") },
    { type: "video", title: "MĀORI+ Ōpaki", url: "https://www.maoriplus.co.nz/show/opaki-he-timonga", level: "beginner", description: cited("A video series built around confidence in speaking te reo Māori. Use short episodes for repeated listening.", "maoriplus") },
    { type: "media", title: "MĀORI+ Marae", url: "https://www.maoriplus.co.nz/mi/show/marae", level: "advanced", description: cited("A bilingual current-affairs program that exposes learners to interviews and public discussion as well as prepared narration.", "maoriplus-marae") },
    { type: "other", title: "Te Taura Whiri i te Reo Māori", url: "https://www.tetaurawhiri.govt.nz/", level: "all", description: cited("The Māori Language Commission publishes information and resources about the language and revitalization.", "tetaurawhiri") }
  ],
  relatedLanguages,
  phrases: [
    { original: "Kia ora.", translation: "Hello; thank you; good wishes.", usageNote: "Common greeting with a wider range in context." },
    { original: "Tēnā koe.", translation: "Hello to one person.", usageNote: "A respectful greeting for one listener." },
    { original: "Tēnā kōrua.", translation: "Hello to two people.", usageNote: "The greeting changes for exactly two listeners." },
    { original: "Tēnā koutou.", translation: "Hello to three or more people.", usageNote: "Use when addressing a group of at least three." },
    { original: "Kei te pēhea koe?", translation: "How are you?", usageNote: "Addressed to one person." },
    { original: "Kei te pai ahau.", translation: "I am well.", usageNote: "A simple reply; listen for other natural answers too." },
    { original: "Ko wai tō ingoa?", translation: "What is your name?" },
    { original: "Ngā mihi.", translation: "Thanks; greetings.", usageNote: "A concise expression often seen in writing." },
    { original: "Haere rā.", translation: "Goodbye to the person leaving.", usageNote: "Said by someone who is staying." },
    { original: "E noho rā.", translation: "Goodbye to the person staying.", usageNote: "Said by someone who is leaving." },
    { original: "Kāore au e mōhio.", translation: "I do not know.", usageNote: "Say this when you need to avoid guessing." },
    { original: "Kia kaha.", translation: "Keep going; be strong.", usageNote: "An encouragement whose tone depends on context." }
  ],
  sources: [
    { id: "stats", title: "Languages spoken in New Zealand, 2023 Census", url: "https://figure.nz/chart/yYLyq5llJTCKpYlV", publisher: "Figure.NZ using Stats NZ census data", accessedAt: "2026-09-27" },
    { id: "datainfo", title: "Languages spoken: 2023 Census information", url: "https://datainfoplus.stats.govt.nz/item/nz.govt.stats/dcbae0ce-f19e-464c-905f-b7236e10437c/64", publisher: "Stats NZ", accessedAt: "2026-09-27" },
    { id: "teara", title: "Te reo Māori — the Māori language", url: "https://teara.govt.nz/en/te-reo-maori-the-maori-language", publisher: "Te Ara Encyclopedia of New Zealand", accessedAt: "2026-09-27" },
    { id: "teara-writing", title: "Māori non-fiction and scholarship: Māori letters and newspapers", url: "https://teara.govt.nz/en/maori-non-fiction-and-scholarship-nga-tuhinga-me-te-rangahau/page-1", publisher: "Te Ara Encyclopedia of New Zealand", accessedAt: "2026-09-27" },
    { id: "act", title: "Māori Language Act 2016", url: "https://www.legislation.govt.nz/act/public/2016/17/en/latest/", publisher: "New Zealand Legislation", publishedAt: "2016", accessedAt: "2026-09-27" },
    { id: "tetaurawhiri", title: "Te Taura Whiri i te Reo Māori", url: "https://www.tetaurawhiri.govt.nz/", publisher: "Māori Language Commission", accessedAt: "2026-09-27" },
    { id: "tki", title: "Features of the written code", url: "https://tereomaori.tki.org.nz/Curriculum-guidelines/Te-reo-Maori/Features-of-the-written-code", publisher: "New Zealand Ministry of Education", accessedAt: "2026-09-27" },
    { id: "massey", title: "Pronunciation: Whakahuatanga", url: "https://www.massey.ac.nz/student-life/m%C4%81ori-massey/m%C4%81orimassey/ng%C4%81-rauemi-reo-m%C4%81ori-me-te-tikanga-m%C4%81ori/pronunciation-whakahuatanga/", publisher: "Massey University", accessedAt: "2026-09-27" },
    { id: "tewhanake", title: "Te Whanake", url: "https://tewhanake.maori.nz/", publisher: "Te Whanake", accessedAt: "2026-09-27" },
    { id: "teaka", title: "Te Aka Māori Dictionary", url: "https://maoridictionary.co.nz/", publisher: "Te Aka", accessedAt: "2026-09-27" },
    { id: "kupu-active", title: "Active sentences", url: "https://kupu.maori.nz/sentences/active-sentences", publisher: "Kupu Māori", accessedAt: "2026-09-27" },
    { id: "kupu-pronouns", title: "Pronouns", url: "https://kupu.maori.nz/extra/pronouns", publisher: "Kupu Māori", accessedAt: "2026-09-27" },
    { id: "kupu-possession", title: "The a/o categories", url: "https://kupu.maori.nz/possession/the-a-o-categories", publisher: "Kupu Māori", accessedAt: "2026-09-27" },
    { id: "kupu-passive", title: "Passive sentences", url: "https://kupu.maori.nz/sentences/passive-sentences", publisher: "Kupu Māori", accessedAt: "2026-09-27" },
    { id: "kupu-demonstratives", title: "Demonstratives", url: "https://kupu.maori.nz/extra/demonstratives", publisher: "Kupu Māori", accessedAt: "2026-09-27" },
    { id: "kupu-negatives", title: "Negatives", url: "https://kupu.maori.nz/sentences/negatives", publisher: "Kupu Māori", accessedAt: "2026-09-27" },
    { id: "maoriplus", title: "Ōpaki - He Timonga", url: "https://www.maoriplus.co.nz/show/opaki-he-timonga", publisher: "MĀORI+ / Whakaata Māori", accessedAt: "2026-09-27" },
    { id: "maoriplus-marae", title: "Marae", url: "https://www.maoriplus.co.nz/mi/show/marae", publisher: "MĀORI+ / Whakaata Māori", accessedAt: "2026-09-27" },
    { id: "chch-proverb", title: "Ngā Whāinga: Manu", url: "https://my.christchurchcitylibraries.com/blogs/post/nga-whainga-challenges-for-te-wiki-o-te-reo-maori-2020-manu/", publisher: "Christchurch City Libraries", publishedAt: "2020-09-17", accessedAt: "2026-09-27" },
    { id: "abvd", title: "Austronesian Basic Vocabulary Database: Maori", url: "https://abvd.eva.mpg.de/austronesian/language.php?id=85", publisher: "Austronesian Basic Vocabulary Database", accessedAt: "2026-09-27" },
    { id: "glottolog", title: "Maori", url: "https://glottolog.org/resource/languoid/id/maor1246", publisher: "Glottolog", accessedAt: "2026-09-27" },
    { id: "wiki-maori", title: "Māori language", url: "https://en.wikipedia.org/wiki/M%C4%81ori_language", publisher: "Wikipedia", accessedAt: "2026-09-27" }
  ],
  seo: { title: "Māori Language Guide: Te Reo History, Sounds, Grammar and Learning", description: "Explore te reo Māori through its communities, revitalization, vowel length, grammar, everyday phrases, relationships with other Polynesian languages, and learning resources." }
} satisfies LanguageGuide;
