import { cited } from "../citations.js";
import type { LanguageGuide } from "../types.js";

const sources = [
  { id: "glottolog", title: "Spanish", url: "https://glottolog.org/resource/languoid/id/stan1288", publisher: "Glottolog", accessedAt: "2026-09-27" },
  { id: "cervantes-history", title: "El español en el mundo: una historia de expansión", url: "https://cvc.cervantes.es/lengua/anuario/anuario_18/moreno/p02.htm", publisher: "Instituto Cervantes", publishedAt: "2018", accessedAt: "2026-09-27" },
  { id: "cervantes-contact", title: "Lengua española y lenguas indígenas de América", url: "https://cvc.cervantes.es/lengua/anuario/anuario_10-11/lastra/p01.htm", publisher: "Instituto Cervantes", publishedAt: "2011", accessedAt: "2026-09-27" },
  { id: "cervantes-variation", title: "El español en América y la historia de la lengua", url: "https://cvc.cervantes.es/lengua/anuario/anuario_16/elizaincin/p03.htm", publisher: "Instituto Cervantes", publishedAt: "2016", accessedAt: "2026-09-27" },
  { id: "rae-conjugation", title: "Conjugación española", url: "https://www.rae.es/buen-uso-espa%C3%B1ol/conjugaci%C3%B3n-espa%C3%B1ola", publisher: "RAE–ASALE", accessedAt: "2026-09-27" },
  { id: "rae-voseo", title: "Vos", url: "https://www.rae.es/dpd/vos", publisher: "RAE–ASALE", accessedAt: "2026-09-27" },
  { id: "rae-seseo", title: "El seseo y el ceceo", url: "https://www.rae.es/buen-uso-espa%C3%B1ol/el-seseo-y-el-ceceo", publisher: "RAE–ASALE", accessedAt: "2026-09-27" },
  { id: "rae-subjunctive", title: "El modo: ¿indicativo o subjuntivo?", url: "https://www.rae.es/libro-estilo-lengua-espa%C3%B1ola/el-modo-indicativo-o-subjuntivo", publisher: "RAE–ASALE", accessedAt: "2026-09-27" },
  { id: "rae-orthography", title: "Ortografía básica de la lengua española", url: "https://www.rae.es/ortograf%C3%ADa-b%C3%A1sica", publisher: "RAE–ASALE", accessedAt: "2026-09-27" },
  { id: "rae-dictionary", title: "Diccionario de la lengua española", url: "https://dle.rae.es/", publisher: "RAE–ASALE", accessedAt: "2026-09-27" },
  { id: "asale-americanisms", title: "Diccionario de americanismos", url: "https://www.asale.org/damer/", publisher: "ASALE", publishedAt: "2010", accessedAt: "2026-09-27" },
  { id: "cervantes-curriculum", title: "Plan curricular: niveles de referencia para el español", url: "https://cvc.cervantes.es/ensenanza/biblioteca_ele/plan_curricular/default.htm", publisher: "Instituto Cervantes", accessedAt: "2026-09-27" },
  { id: "cervantes-dele", title: "Preparar la prueba DELE", url: "https://examenes.cervantes.es/es/dele/preparar-prueba", publisher: "Instituto Cervantes", accessedAt: "2026-09-27" },
  { id: "cervantes-ave", title: "Cursos de español en línea AVE Global", url: "https://ave.cervantes.es/AVEGlobal/cursos-espanol-en-linea-ave-global.html", publisher: "Instituto Cervantes", accessedAt: "2026-09-27" },
  { id: "wikipedia-spanish", title: "Spanish language", url: "https://en.wikipedia.org/wiki/Spanish_language", publisher: "Wikipedia", accessedAt: "2026-09-27" }
] satisfies LanguageGuide["sources"];

const relatedLanguages = [
  { name: "Portuguese", relationship: "Western Romance relative", explanation: cited("Portuguese and Spanish developed from Latin on the Iberian Peninsula. They share many written forms, but their vowel systems, pronunciation, and common expressions differ. Reading one can help with the other; understanding rapid speech still takes separate practice.", "glottolog", "wikipedia-spanish") },
  { name: "Catalan", relationship: "Romance relative and neighbor", explanation: cited("Catalan is a separate Romance language spoken alongside Spanish in parts of Spain. Bilingual speakers may switch between them, and public signs may use both. Shared Latin ancestry and contact explain familiar words without making Catalan a variety of Spanish.", "glottolog", "wikipedia-spanish") },
  { name: "French", relationship: "Romance relative", explanation: cited("French and Spanish inherited much vocabulary and grammar from Latin. Similar spellings can speed reading, while different sound changes make listening harder than a written comparison suggests. Learners should check current usage instead of assuming a cognate has the same meaning.", "glottolog", "wikipedia-spanish") },
  { name: "Nahuatl", slug: "nahuatl", relationship: "Contact language", explanation: cited("Nahuatl belongs to the Uto-Aztecan family. Spanish borrowed words such as chocolate and tomate through contact in Mexico. Borrowing does not make the two languages relatives; the history also includes colonial pressure on Indigenous languages.", "cervantes-contact", "glottolog") },
  { name: "Quechua", slug: "quechua", relationship: "Contact language", explanation: cited("Quechua languages and Spanish have long been spoken together in the Andes. Local Spanish varieties reflect that shared history in vocabulary and everyday interaction. Quechua is still a language community in its own right rather than a source of colorful words for Spanish.", "cervantes-contact", "glottolog") }
] satisfies LanguageGuide["relationships"]["languages"];

const resources = [
  { type: "course", title: "AVE Global", url: "https://ave.cervantes.es/AVEGlobal/cursos-espanol-en-linea-ave-global.html", level: "beginner", description: cited("The Instituto Cervantes offers structured online courses from A1 through C1. Check the current terms before paying; use live conversation and local media alongside the course for spontaneous speech.", "cervantes-ave") },
  { type: "dictionary", title: "Diccionario de la lengua española", url: "https://dle.rae.es/", level: "all", description: cited("Search meanings, examples, and regional labels. Definitions are in Spanish and are most helpful once you can read short explanations; a bilingual dictionary can support your first months.", "rae-dictionary") },
  { type: "dictionary", title: "Diccionario de americanismos", url: "https://www.asale.org/damer/", level: "intermediate", description: cited("Check where a word or expression is recorded in the Americas. A regional label helps you ask a better question, but it cannot tell you how every person in that place speaks.", "asale-americanisms") },
  { type: "other", title: "Plan curricular del Instituto Cervantes", url: "https://cvc.cervantes.es/ensenanza/biblioteca_ele/plan_curricular/default.htm", level: "all", description: cited("Use the level inventories to see which grammar, pronunciation, and communication tasks belong in a study plan. It is a curriculum reference, not a sequence of lessons to read straight through.", "cervantes-curriculum") },
  { type: "other", title: "DELE sample examinations", url: "https://examenes.cervantes.es/es/dele/preparar-prueba", level: "all", description: cited("Try official sample tasks with audio and answer sheets when you want to measure reading, listening, writing, and speaking against a named level. The exam samples include more than one Spanish variety.", "cervantes-dele") },
  { type: "other", title: "Diccionario panhispánico de dudas", url: "https://www.rae.es/dpd/", level: "advanced", description: cited("Consult a specific usage question, such as forms of vos or competing constructions. Read the regional notes before applying a recommendation to a conversation outside Spain.", "rae-voseo", "rae-subjunctive") }
] satisfies LanguageGuide["resources"];

export const spanishGuide = {
  slug: "spanish",
  name: "Spanish",
  autonym: "Español / castellano",
  status: "published",
  publishedAt: "2026-09-27",
  summary: "Spanish connects communities across the Americas, Europe, and beyond. Learn how its regional voices, verbs, sounds, writing, and contact histories fit together, then choose a study path grounded in real speech.",
  family: "Indo-European, Romance, Ibero-Romance",
  macroRegion: "The Americas and Europe; global diaspora",
  primaryScript: "Latin alphabet",
  difficultyLabel: "Moderate",
  learnerHook: "Start with familiar-looking words and a fairly regular spelling system, then learn how verb choices, pronouns, and regional speech change what people mean in a real conversation.",
  hero: { callToActionLabel: "Explore Spanish in use" },
  classification: "A Romance language that developed from spoken Latin on the Iberian Peninsula",
  speakerCommunity: "Spanish is a first or additional language for communities across most of Latin America, Spain, the United States, and many other places. Its global reach reflects migration, education, and media as well as a history of empire. An exact speaker total changes with the year and with whether a count includes heritage speakers, learners, and people who use Spanish alongside another home language.\n\nMany people use español and castellano for the same language. Local preferences reflect history and politics, so follow the term used by the people or institution you are speaking with. Spanish also shares homes, classrooms, and streets with Indigenous languages, other European languages, and sign languages. Do not assume a country has one language or one kind of Spanish.",
  facts: [
    { label: "Family", value: "Indo-European · Romance" },
    { label: "Community", value: "First- and additional-language speakers across several continents" },
    { label: "Writing", value: "Latin alphabet with ñ and written accent marks" },
    { label: "Address", value: "Tú, vos, usted, ustedes, and in much of Spain vosotros" },
    { label: "Sound pattern", value: "Five main vowel phonemes; consonants vary by region" },
    { label: "Names", value: "Español and castellano" }
  ],
  learnerOverview: "A friend in Buenos Aires may ask ¿Vos tenés tiempo? A friend in Mexico might say ¿Tienes tiempo? Both ask whether you have time. The change in pronoun and verb is a normal regional choice, not a failure to speak a shared language.\n\nBegin with a variety tied to the people, places, or media that matter to you. Learn its forms well enough to speak without stopping at every sentence. At the same time, listen to other varieties early: you will meet different greetings, /s/ pronunciations, and words for everyday objects. You need recognition before you need to produce every regional form.\n\nWritten Spanish gives you many clues to pronunciation, especially if you learn stress marks and the values of letters in your chosen variety. Conversation adds another layer. Unstressed words run together, familiar consonants weaken in some positions, and speakers choose verb forms to show time, certainty, and their relationship to the listener. Record complete phrases and the situation in which you heard them.",
  origins: {
    overview: cited("Spanish developed from varieties of spoken Latin in the Iberian Peninsula. It did not appear in one town on one date. Medieval Castilian became increasingly influential through politics, writing, and movement among communities, while neighboring Romance varieties continued to change too.\n\nThe Spanish carried to the Americas from the late fifteenth century onward already had regional differences. In the colonies, settlement, forced labor, institutions, and daily contact with Indigenous and African peoples shaped new local varieties. Indigenous languages survived and continue to shape life across the region. A history of Spanish needs to tell both the language's spread and what that spread meant for other communities.", "cervantes-history", "cervantes-variation", "cervantes-contact"),
    timeline: [
      { period: "Roman period to early Middle Ages", event: cited("Latin spread through Roman rule in Iberia. After Roman administration ended, local forms kept changing; the Romance languages gradually became distinct. Arabic and other languages also formed part of the peninsula's multilingual life.", "cervantes-history", "wikipedia-spanish") },
      { period: "Medieval centuries", event: cited("Castilian expanded through writing, government, and movement across Iberia. Texts show a changing language rather than a finished standard. Other Iberian languages developed beside it and still have their own speakers.", "cervantes-history", "cervantes-variation") },
      { period: "Late fifteenth century onward", event: cited("Spanish colonial expansion carried the language to the Americas. New communities formed through conquest, migration, and coercion; Spanish came into sustained contact with Indigenous and African languages. The present map of speakers cannot be understood apart from that history.", "cervantes-contact", "cervantes-history") },
      { period: "Nineteenth century to present", event: cited("Independent American states expanded schooling, print, radio, and later television in Spanish. Academies and publishers increasingly worked across countries. Migration and digital media now connect speakers who once met fewer varieties in daily life.", "cervantes-variation", "wikipedia-spanish") }
    ],
    contactHistory: cited("Spanish took words from Arabic during long contact in Iberia: aceite and almohada are familiar examples. In the Americas, words for foods, plants, places, and practices entered Spanish from Indigenous languages. Tomate and chocolate came through Nahuatl; other regions have different contact vocabularies. Borrowing works in more than one direction, and words alone tell only part of the story.\n\nSpanish has also lived beside Portuguese, Catalan, Basque, English, Quechua, Guaraní, and many other languages. A bilingual speaker may choose a word or sentence pattern that reflects both. Treat that choice as part of a community's speech, and ask who uses it before assigning it to an entire nation.", "cervantes-contact", "cervantes-variation", "asale-americanisms"),
    standardization: cited("Schools, publishing, and public institutions teach shared written conventions. The Real Academia Española and the academies in other Spanish-speaking countries collaborate on dictionaries, grammar, and spelling references. Their work describes a language used across many regions; a reference spelling does not make every accent or local word identical.\n\nFormal writing is relatively portable between countries. A contract, novel, or news report can still carry local vocabulary and address forms. When you write for a specific audience, check that audience's terms rather than replacing every regional expression with a supposed universal synonym.", "rae-orthography", "rae-dictionary", "asale-americanisms")
  },
  variants: {
    overview: cited("Spanish variation crosses national borders. A speaker's age, neighborhood, education, audience, and task can shape a conversation as much as their passport. The broad groups below help you notice patterns, but each contains many local voices.\n\nChoose recordings with a named place and setting. Compare one news interview with one unscripted conversation from the same area; the difference will teach you more than a list of stereotypes about how a country speaks.", "cervantes-variation", "rae-seseo", "rae-voseo"),
    items: [
      { name: "Mexico and Central America", note: cited("Spanish is used across highly diverse communities, often alongside Indigenous languages. Local words, rhythm, and pronoun choices differ within the region. Some Central American communities use vos; check the speaker and setting before choosing tú or vos yourself.", "cervantes-contact", "rae-voseo") },
      { name: "Caribbean varieties", note: cited("Cuba, the Dominican Republic, Puerto Rico, and coastal communities elsewhere share some patterns, including weakening of /s/ in certain positions. The amount and social meaning vary. Begin by listening for the whole phrase instead of trying to recover every written consonant from a recording.", "cervantes-variation", "rae-seseo") },
      { name: "Andean communities", note: cited("Spanish is used beside Quechua, Aymara, and other languages in many Andean areas. Speakers differ in first language and local history. Avoid treating bilingual speech as a learner error; record who is speaking and what their sentence means in context.", "cervantes-contact", "cervantes-variation") },
      { name: "Río de la Plata", note: cited("Much informal speech in Argentina and Uruguay uses vos with forms such as tenés. Other sounds and everyday words also distinguish local speech. Learn these forms from speakers if that is your destination, and recognize tú forms used elsewhere.", "rae-voseo", "cervantes-variation") },
      { name: "Spain", note: cited("Many speakers use vosotros for informal plural address and ustedes in more formal settings, while regional practice varies. Some areas distinguish the sounds written s and z or c before e and i; others have seseo. Spain also has Catalan, Basque, Galician, and other languages.", "rae-conjugation", "rae-seseo", "wikipedia-spanish") }
    ]
  },
  pronunciation: {
    overview: cited("Spanish has five main vowel phonemes, written a, e, i, o, u. Their usual values stay fairly stable across stressed and unstressed syllables compared with English. Clear vowels help listeners recognize words even when consonants vary.\n\nConsonants demand more regional awareness. Many speakers pronounce written s, z, and c before e or i with the same /s/ sound; much of Spain distinguishes /s/ from a sound like English th in thin. Both systems are ordinary Spanish. A listener also hears changes to final /s/ and to y or ll across communities.", "rae-seseo", "cervantes-curriculum"),
    script: "Latin alphabet; examples use standard spelling rather than a regional phonetic transcription",
    soundSystem: cited("The letter j and g before e or i usually mark a sound made further back than English h, though its strength changes by region. Written b and v generally do not contrast as English b and v do. Between vowels, sounds written b, d, and g often have a softer contact than at the start of a phrase.\n\nSome speakers pronounce ll and y alike, a merger called yeísmo. The merged sound itself can differ greatly: listen to calle in several recordings instead of learning one universal value. Written h is normally silent, while ch and ñ represent sounds you should learn as units.", "rae-orthography", "cervantes-curriculum", "wikipedia-spanish"),
    prosody: cited("Spanish words have stressed syllables, and stress can change meaning: término, termino, and terminó are different forms. Accent marks tell you when stress departs from the general spelling pattern or distinguish certain words. Practice hearing and marking stress as you learn a new verb, not after memorizing its letters.\n\nIn connected speech, vowel sequences may join across word boundaries and short pronouns attach closely to verbs. Read a transcript while listening, then hide it and replay the same stretch. This shows where your ear divided the stream differently from the speaker.", "rae-orthography", "cervantes-curriculum"),
    learnerTraps: ["Do not pronounce written b and v as a fixed English contrast.", "Do not assume every speaker distinguishes written s and z.", "Do not ignore accent marks: they can separate words and verb forms.", "Listen for reduced or weakened final consonants without copying a pattern you have not understood."],
    sampleWords: [
      { original: "año", translation: "year", note: "Ñ marks a different sound from n; ano is another word." },
      { original: "gente", translation: "people", note: "G before e has the sound also written j." },
      { original: "casa", translation: "house", note: "Two clear a vowels make a good first listening anchor." },
      { original: "calle", translation: "street", note: "Listen for how a local speaker pronounces ll." },
      { original: "término / terminó", translation: "term / (someone) finished", note: "The accent shows a stress and meaning difference." },
      { original: "zapato", translation: "shoe", note: "The initial sound follows a local distinction or seseo pattern." }
    ]
  },
  writing: {
    overview: cited("Spanish uses the Latin alphabet with ñ. Written accents mark stress in many words and distinguish some short forms. An opening question or exclamation mark tells readers where the relevant span begins: ¿Vienes? and ¡Qué bien! are everyday punctuation, not decoration.\n\nSpelling is widely shared across the Spanish-speaking world even where pronunciation differs. Casa, zapato, and calle keep their written forms across varieties with different sounds. That consistency makes reading a strong support for listening, but it cannot replace exposure to local speech.", "rae-orthography", "rae-seseo"),
    primaryScript: "Latin alphabet with ñ, accented vowels, and opening question and exclamation marks",
    romanization: cited("Spanish already uses a Latin alphabet, so romanization is unnecessary. If you make pronunciation notes for yourself, keep standard spelling beside them. A homemade English-based spelling can hide stress and regional sounds that the normal word form preserves.", "rae-orthography"),
    spellingNorms: cited("The accent rules depend on where stress falls and on a word's ending. Lápiz has an accent because its stress differs from the usual pattern for words ending in z; canción has one because its final syllable is stressed. Accent marks can also distinguish sí from si and él from el.\n\nLearn the rules by sorting actual words you read. Check an uncertain form in a current dictionary or spelling reference, especially when a pronoun attaches to a verb and changes the written accent.", "rae-orthography", "rae-dictionary"),
    styleNotes: [
      cited("Keep ñ distinct when typing names and ordinary words. Most phone and computer keyboards let you add a Spanish layout or hold a key to select ñ.", "rae-orthography"),
      cited("Use both signs in a full question or exclamation. If only part of a sentence is a question, the opening mark belongs where that question starts.", "rae-orthography"),
      cited("Watch regional vocabulary in editing. A word common in one country may be unfamiliar or mean something else in another; a dictionary's locality labels are a starting point.", "asale-americanisms"),
      cited("Preserve accents in published text even when a chat partner omits them while typing quickly. They help a reader resolve stress and short-word contrasts.", "rae-orthography")
    ]
  },
  grammar: {
    overview: cited("Spanish verbs carry information about person, number, tense, and mood. A subject pronoun can therefore disappear when the verb ending and context already identify the speaker. Nouns and many adjectives show grammatical gender and number, while articles help listeners anticipate the noun.\n\nThe hardest patterns are usually choices, not isolated forms. You can memorize both hablé and hablaba yet still need context to choose between a bounded event and background or habitual past. Learn a new form in a short exchange, with the speaker's reason for using it.", "rae-conjugation", "cervantes-curriculum"),
    typologicalProfile: cited("Spanish usually places a subject before a verb and an object after it, but word order can move with topic and emphasis. It marks much grammar on verbs and noun phrases rather than through fixed position alone. Small object pronouns such as lo, la, and le have their own placement rules; their regional patterns deserve attention too.", "rae-conjugation", "cervantes-curriculum"),
    morphology: cited("A regular present-tense verb changes ending with its subject: hablo, hablas, habla, hablamos. Frequent verbs include irregular forms, so learn tengo and voy early rather than waiting until you finish all regular tables. Nouns typically mark plural with -s or -es. Adjectives often agree with the noun in gender and number, but the exact ending depends on the adjective's form.", "rae-conjugation", "cervantes-curriculum"),
    syntax: cited("Object pronouns usually come before a finite verb, as in Lo veo, but can attach to an infinitive or an affirmative command. Negation commonly places no before the verb. Questions can use intonation and punctuation without reversing every word as English often does. These patterns are easier to learn from paired sentences than from a single translation rule.", "cervantes-curriculum", "rae-conjugation"),
    advancedPainPoints: ["Choosing between past forms for an event and its background.", "Tracking object pronouns and their regional uses.", "Choosing indicative or subjunctive in a clause tied to desire, doubt, or an unknown referent.", "Using address forms that fit a specific community and relationship."],
    topics: [
      { title: "Articles and agreement", body: cited("El libro rojo and la casa roja show articles and adjectives agreeing with their nouns. Learn a noun together with its article; an English translation will not tell you its gender. Some words have forms that complicate a simple -o/-a rule, so confirm them in a dictionary.", "cervantes-curriculum", "rae-dictionary"), example: "La casa roja está abierta.", exampleTranslation: "The red house is open." },
      { title: "A subject can stay unspoken", body: cited("Hablo español already tells a listener who is speaking. Add yo when you need emphasis or contrast: Yo hablo español, pero ella habla portugués. Keeping the pronoun in every sentence may be grammatical, yet it can sound more pointed than you intended.", "rae-conjugation", "cervantes-curriculum"), example: "Hablo español con mi vecino.", exampleTranslation: "I speak Spanish with my neighbor." },
      { title: "Two common ways to locate a situation", body: cited("Ser often classifies or identifies; estar often locates or presents a state. Compare Es médico with Está en el hospital. The choice is not a universal permanent-versus-temporary test: locations of events and familiar expressions need their own patterns.", "cervantes-curriculum"), example: "La biblioteca está cerca.", exampleTranslation: "The library is nearby." },
      { title: "Past events and background", body: cited("A speaker can use the simple past to move a story forward and the imperfect to give background or a repeated habit. Ayer llegué temprano points to an arrival; antes llegaba temprano describes what used to happen. Study the surrounding story instead of translating both forms as one English past tense.", "rae-conjugation", "cervantes-curriculum"), example: "Llegué cuando llovía.", exampleTranslation: "I arrived while it was raining." },
      { title: "Pronouns near the verb", body: cited("Lo veo puts a direct-object pronoun before a conjugated verb. In Voy a verlo, the same pronoun attaches to the infinitive. When two object pronouns occur together, their order and form change; practice with people and objects you actually discuss.", "cervantes-curriculum", "rae-conjugation"), example: "¿Tienes el libro? Sí, lo tengo.", exampleTranslation: "Do you have the book? Yes, I have it." },
      { title: "Desire, doubt, and the subjunctive", body: cited("Quiero que vengas uses a subjunctive form because one person wants another person's action. Creo que viene presents a belief differently. No single English word announces every subjunctive use, and regional choices can differ; learn the trigger, meaning, and full clause together.", "rae-subjunctive", "cervantes-curriculum"), example: "Espero que tengas tiempo.", exampleTranslation: "I hope you have time." },
      { title: "Addressing a listener", body: cited("Tú, vos, and usted can address one person, with different verb forms and social meanings. Ustedes is a plural form across the Americas; many people in Spain also use vosotros for informal plural address. Start with the usage of your intended community and recognize the other forms in media.", "rae-voseo", "rae-conjugation"), example: "¿Vos tenés tiempo? / ¿Tú tienes tiempo?", exampleTranslation: "Do you have time?" }
    ]
  },
  whereSpoken: {
    overview: cited("Spanish has large communities in the Americas and Europe, and smaller communities connected by migration elsewhere. A map of national borders cannot show who uses Spanish at home, who learned it later, or which other languages share a place.\n\nFor learners, a practical map has people and media on it. Name a city, family network, teacher, or broadcaster, then gather recordings from that context. Add another region once you can follow the first one comfortably. This builds range without treating one variety as the only legitimate form.", "cervantes-contact", "cervantes-variation", "wikipedia-spanish"),
    regions: [
      { place: "Mexico and Central America", note: cited("Spanish is prominent in public life and shares space with many Indigenous languages. Local speech and forms of address vary within each country. Seek material connected to the community you expect to meet.", "cervantes-contact", "rae-voseo") },
      { place: "South America", note: cited("Spanish is used across much of the continent beside Portuguese, Indigenous languages, and immigrant languages. Coastal, highland, urban, and rural voices can differ inside one country. Country labels alone are too coarse for a listening plan.", "cervantes-contact", "cervantes-variation") },
      { place: "Caribbean", note: cited("Spanish-speaking island and coastal communities have strong ties through music, migration, and media. Some pronunciation patterns are shared, yet a Cuban interview and a Dominican family conversation should each be heard on their own terms.", "cervantes-variation") },
      { place: "Spain", note: cited("Spanish is widely used, while Catalan, Galician, Basque, and other languages remain central to many communities. Speakers may use different language combinations at school, home, and work. Listening materials should reflect that multilingual setting.", "cervantes-history", "wikipedia-spanish") },
      { place: "United States and diaspora", note: cited("Spanish lives in families, local media, workplaces, and community institutions across the United States and beyond. Heritage speakers have varied experiences with formal schooling and writing. Neither a surname nor an accent tells you a person's full language history.", "cervantes-variation", "wikipedia-spanish") }
    ]
  },
  difficulty: {
    label: "Moderate",
    overview: cited("For an English-speaking beginner, many written Spanish words look familiar and the five-vowel system gives a clear starting point. The amount of available media makes it easy to hear a chosen variety. Those advantages do not make verb forms, rapid speech, or social choices automatic.\n\nDifficulty depends on your first languages and goals. A Portuguese speaker may read much Spanish early but still need to resist familiar-sounding false matches. A heritage speaker may converse fluently and want separate practice with formal writing. Give each skill its own plan.", "cervantes-curriculum", "cervantes-dele"),
    easierAspects: ["A broadly shared spelling system supports reading across regions.", "Five main vowel sounds give many beginners a clear listening anchor.", "Courses, dictionaries, and recordings cover many levels and communities."],
    hardAspects: ["Frequent verbs have many forms, including irregular ones.", "Past tense and mood choices depend on the speaker's meaning.", "Fast connected speech and regional vocabulary can outpace classroom audio.", "Pronouns and address forms carry local social meaning."],
    plateauRisks: ["Reading familiar-looking words without checking their everyday meaning.", "Practicing one careful accent so exclusively that natural conversation elsewhere feels unfamiliar.", "Learning conjugation charts without using the forms in a conversation."],
    workload: cited("A workable routine combines short daily listening with reading and regular conversation. For example, replay a two-minute exchange until you can follow its turns, keep three phrases you could say yourself, and use one of them with a person. Once a week, review the grammar behind an error you actually made. No fixed number of hours guarantees a level: available partners, prior language knowledge, and your target tasks all change the pace.", "cervantes-curriculum", "cervantes-dele")
  },
  advancedLearning: {
    strategy: cited("At the beginning, choose a core course and a speaker or media source you want to understand. Practice pronunciation with full words and stress, then build sentences with common verbs, articles, and questions. Let the course give you order while real recordings show which phrases people actually use.\n\nAt an intermediate level, keep a notebook of decisions: why a speaker chose a past form, whether a pronoun refers to a person or thing, and which address form fits the relationship. Compare two transcripts from the same region before generalizing. When you can explain a choice in ordinary words, try it in your own conversation.\n\nAt an advanced level, select a domain such as work, literature, family history, or public affairs. Read and listen in that domain, collect recurring terms, and write or speak for a real audience. Ask a knowledgeable reader to mark passages that sound unlike local usage. Revision, not another list of rare words, often brings the largest gain.", "cervantes-curriculum", "cervantes-dele", "asale-americanisms"),
    mediaPractice: cited("Use one clip twice: first to understand the topic, then to notice stress, pronouns, and verb choices. A transcript can reveal what you missed, but return to the audio afterward. Alternate prepared speech with unscripted interviews so you learn to handle pauses and overlapping voices.\n\nKeep source labels in your notes. If a singer, journalist, and neighbor use three forms, the difference may be regional, personal, or tied to the setting. Try to explain it before you copy a phrase. Subtitles are helpful for checking a line, but watching only with subtitles can hide a listening gap.", "cervantes-curriculum", "cervantes-variation"),
    dictionariesAndCorpora: cited("Use a general Spanish dictionary for meaning and spelling, then the Diccionario de americanismos when a word seems local. Read a full entry: an example and locality label often matter more than the first short definition. For a grammar doubt, consult the Diccionario panhispánico de dudas and check whether its note describes the area you are studying.\n\nSearch several real examples of a phrase before treating it as an all-purpose pattern. Newspapers and books show edited writing; conversations show different habits. If a dictionary and a speaker appear to disagree, ask about the speaker's setting and whether the dictionary labels a regional use.", "rae-dictionary", "asale-americanisms", "rae-voseo"),
    resources: resources.slice(0, 4)
  },
  wordsAndTexts: {
    overview: cited("Spanish vocabulary shows a history of movement and contact. Some words are widespread, while others point to a local object, community, or style of speech. A learner gains more by learning who says a word and when than by collecting lists headed “Spanish slang.”\n\nTexts also need context. A recipe may use local food names, a news article may follow a formal shared register, and a poem may bend ordinary word order. Read several examples within one genre before copying its style into a message to a friend.", "asale-americanisms", "cervantes-contact"),
    notableWords: [
      { term: "ojalá", meaning: "hopefully; I hope", note: cited("This word has an Arabic history and often introduces a wish. Ojalá que llueva means you hope it rains, with a verb form that belongs to the subjunctive pattern.", "cervantes-history", "rae-subjunctive") },
      { term: "tomate", meaning: "tomato", note: cited("Spanish took this food word from Nahuatl through contact in Mexico. A familiar international word can carry a specific history of Indigenous knowledge and colonial exchange.", "cervantes-contact", "rae-dictionary") },
      { term: "aprovechar", meaning: "to make use of; take advantage", note: cited("The best English wording depends on the object and situation. Aprovecha el tiempo urges someone to use their time well; copy the whole phrase, not a single translation.", "rae-dictionary") },
      { term: "sobremesa", meaning: "conversation or time spent at the table after a meal", note: cited("The term names an activity, but it does not mean every family follows one ritual. Read it in a story or invitation to see what the speakers intend.", "rae-dictionary") },
      { term: "ahorita", meaning: "a form built from ahora, now", note: cited("Its timing depends on region and context. Do not assume one precise English equivalent; ask a local speaker when the action is expected.", "asale-americanisms") },
      { term: "vos", meaning: "an informal singular way to address someone in some regions", note: cited("It is ordinary in Argentina and Paraguay and occurs in other American areas with different patterns. Its verb forms are part of the expression, as in vos tenés.", "rae-voseo") }
    ],
    loanwordLayers: cited("Arabic contact left many familiar words in Iberian Spanish, often beginning with al-. American Indigenous languages supplied names for plants, foods, places, and local practices as Spanish spread through colonization. English now influences technology and entertainment vocabulary, though adoption differs by community.\n\nA word's origin does not determine whether a present-day speaker sees it as foreign. Nor should borrowing be used to erase the language it came from. When a word points to an Indigenous practice or place, look for material created by that community and a Spanish dictionary entry.", "cervantes-contact", "cervantes-history", "asale-americanisms"),
    idioms: [
      { original: "Poco a poco", translation: "Little by little", note: "Use it for gradual progress, not as a fixed promise of a completion date." },
      { original: "No pasa nada", translation: "It's okay; don't worry about it", note: "Tone and situation decide whether it reassures or dismisses a concern." },
      { original: "Echar una mano", translation: "To lend a hand", note: "The phrase means helping someone, not throwing a physical hand." },
      { original: "Estar al tanto", translation: "To be up to date or aware", note: "Ask what information the person needs to keep track of." }
    ],
    textGenres: ["Personal voice notes and family messages", "News interviews and explanatory journalism", "Recipes with regional food vocabulary", "Songs and spoken-word performance", "Short stories and contemporary novels", "Public notices and institutional forms"]
  },
  relationships: {
    overview: cited("Spanish belongs to the Romance branch of Indo-European, alongside Portuguese, Catalan, French, Italian, and others. Their similarities mostly come from Latin inheritance, with later borrowing adding another layer. Resemblance on a page is not a measure of effortless mutual understanding in speech.\n\nSpanish also shares long contact histories with languages outside that family. Nahuatl and Quechua loanwords, bilingual practices, and regional pronunciations belong in the story. Keep descent and contact separate: a shared ancestor explains one relationship, while neighbors changing each other's daily speech explains another.", "glottolog", "cervantes-contact", "cervantes-variation"),
    languages: relatedLanguages
  },
  culturalNotes: "Spanish can give access to literature, film, science, sport, family stories, and public life in many communities. Choose material made in the community you want to know, and notice when an author or speaker brings another language into the work. Translation may help you begin, but local words and address forms often carry the relationship between people as well as the dictionary meaning.",
  resources,
  relatedLanguages,
  phrases: [
    { original: "Hola, ¿cómo estás?", translation: "Hi, how are you?", usageNote: "An informal greeting with tú; use the local address form when speaking with someone you do not know." },
    { original: "Mucho gusto.", translation: "Nice to meet you.", usageNote: "Common when people are introduced; another reply or greeting may be more natural in your community." },
    { original: "¿Cómo se dice esto?", translation: "How do you say this?", usageNote: "Point to a word or object and let the other person give the local term." },
    { original: "No entendí la última parte.", translation: "I didn't understand the last part.", usageNote: "This tells the speaker exactly what to repeat." },
    { original: "¿Puedes hablar un poco más despacio?", translation: "Can you speak a little more slowly?", usageNote: "Informal tú form; with usted, use puede." },
    { original: "¿De dónde eres?", translation: "Where are you from?", usageNote: "Informal tú form; ask about someone's background with care rather than assuming it from their accent." },
    { original: "Estoy aprendiendo español.", translation: "I'm learning Spanish.", usageNote: "A straightforward way to explain a pause or request help." },
    { original: "¿Qué significa esta palabra?", translation: "What does this word mean?", usageNote: "Keep the whole sentence around the word if you want an answer you can use." },
    { original: "¿Me puedes recomendar algo para leer?", translation: "Can you recommend something for me to read?", usageNote: "Add your interests and level so the person can suggest a text you can read." },
    { original: "Gracias por explicármelo.", translation: "Thank you for explaining it to me.", usageNote: "The attached pronouns make this a good example to notice in writing and speech." },
    { original: "Nos vemos mañana.", translation: "See you tomorrow.", usageNote: "A common informal way to close a conversation when you expect to meet again." },
    { original: "¿Te parece bien?", translation: "Does that sound good to you?", usageNote: "Use it to check whether a proposed plan suits the other person." }
  ],
  sources,
  seo: {
    title: "Spanish Language Guide: Regional Speech, Grammar, Sounds and Learning",
    description: "Explore Spanish as it is spoken across communities: its history, accents, writing, verbs, regional forms, everyday phrases, sources, and a practical learning path."
  }
} satisfies LanguageGuide;
