import { cited } from "../citations.js";
import type { LanguageGuide } from "../types.js";

const relatedLanguages = [
  { name: "Azerbaijani", relationship: "Close Oghuz relative", explanation: cited("Turkish and Azerbaijani share much basic grammar and vocabulary. Speakers can sometimes understand part of a careful exchange, though fast everyday speech may be harder. Each language has its own standard, sound patterns, and recent history.", "glottolog", "wiki-turkish") },
  { name: "Turkmen", relationship: "Oghuz relative", explanation: cited("Turkmen shares old Oghuz roots and many familiar endings with Turkish. Its sounds, words, and written standard differ enough that a Turkish speaker must study it to follow ordinary speech.", "glottolog") },
  { name: "Persian", slug: "persian", relationship: "Literary contact, separate family", explanation: cited("Persian belongs to the Indo-European family. Persian writers and readers shaped Ottoman vocabulary, compounds, court style, and poetry, and modern Turkish still has many Persian-origin words.", "wiki-turkish", "tdk-dictionary") },
  { name: "Arabic", slug: "arabic", relationship: "Religious and scholarly contact, separate family", explanation: cited("Arabic contributed many words to Ottoman religious, scholarly, and administrative writing. Turkish speakers still use some of those words every day. The borrowed vocabulary did not make Turkish grammar Arabic.", "wiki-turkish", "tdk-dictionary") }
] satisfies LanguageGuide["relationships"]["languages"];

export const turkishGuide = {
  slug: "turkish",
  name: "Turkish",
  autonym: "Türkçe",
  status: "published",
  publishedAt: "2026-07-09",
  summary: "Turkish adds endings to words to show who did what, where, and when. Meet its sounds, history, regional voices, everyday expressions, and paths into reading and conversation.",
  family: "Turkic, Oghuz",
  macroRegion: "Anatolia, Cyprus, the Balkans, and European diasporas",
  primaryScript: "Latin",
  difficultyLabel: "Moderate",
  learnerHook: "In evlerimizden, Turkish packs “from our houses” into one word. Learn to hear those endings, and ordinary conversations and headlines begin to make more sense.",
  hero: { imageAlt: "Contemporary Turkish print and handwriting showing the dotted and dotless i and other distinctive letters.", callToActionLabel: "Explore Turkish in use" },
  classification: "An Oghuz Turkic language and the national standard of Türkiye",
  speakerCommunity: "Most people in Türkiye grow up speaking Turkish. Turkish-speaking communities also live in Cyprus, the Balkans, Western Europe, Australia, and North America. At home, at school, and on screen, speakers draw on different regional and social styles.\n\nMany people in Türkiye speak Kurdish, Arabic, Zaza, Armenian, Greek, Laz, Circassian languages, or other languages too. A person's citizenship, identity, and first language needn't line up in one way. Turkish speakers abroad may keep family expressions, switch between languages, and develop new local styles.",
  facts: [
    { label: "Family", value: "Turkic · Common Turkic · Oghuz" },
    { label: "Standard base", value: "Istanbul-centered modern Turkish" },
    { label: "Alphabet", value: "29 Latin letters since 1928" },
    { label: "Core profile", value: "Suffixing, agglutinative, vowel-harmonizing, generally head-final" },
    { label: "Gender", value: "No grammatical gender in pronouns or nouns" },
    { label: "Major communities", value: "Türkiye, Cyprus, the Balkans, and a large European diaspora" }
  ],
  introduction: cited(
    "Turkish is spoken by families across Türkiye and by communities in Cyprus, the Balkans, and Western Europe, especially Germany. It belongs to the Oghuz branch of the Turkic language family, alongside Azerbaijani. Its presence across these regions reflects centuries of movement as well as more recent migration.\n\nModern Turkish is written in a 29-letter Latin alphabet adopted in 1928, when it replaced the Arabic-derived alphabet used for Ottoman Turkish. Its dotted i and dotless ı stand for different vowel sounds, a small but consequential distinction in names and everyday words. The alphabet change also means an older Ottoman document looks very different from a contemporary Turkish newspaper.\n\nTurkish words often grow by adding endings in a set order. Evlerimizden, meaning “from our houses,” joins ev, “house,” with endings for plural, possession, and movement away; the vowels in many endings adjust to the word they follow. The same pattern carries information about time, place, and people through ordinary conversation, while regional and diaspora varieties give familiar forms their own local sounds and expressions.",
    "wiki-turkish",
    "glottolog",
    "unicode-latin",
    "dd-grammar",
    "dd-vowels"
  ),
  origins: {
    overview: cited("Turkish belongs to the Oghuz branch of the Turkic language family. Oghuz-speaking groups moved west into Iran and Anatolia over centuries and lived alongside speakers of Greek, Armenian, Kurdish, Arabic, Persian, and other languages. Written Anatolian Turkish appears in the late medieval record.\n\nOttoman writers later used Turkish across an empire and drew heavily on Arabic and Persian for learned vocabulary. Their most elaborate court prose differed from everyday speech, which varied from place to place. Modern Turkish grew from these earlier forms and kept Turkic grammar through those changes.", "wiki-turkish", "glottolog"),
    timeline: [
      { period: "11th–13th centuries", event: cited("Oghuz Turkic speakers settled in growing numbers in Anatolia. They lived among communities who spoke other languages, and contact shaped local vocabulary.", "wiki-turkish", "glottolog") },
      { period: "13th–15th centuries", event: cited("Writers used Old Anatolian Turkish in religious and literary works and in other records. Their choices of Arabic and Persian vocabulary varied with audience and genre.", "wiki-turkish") },
      { period: "15th–19th centuries", event: cited("Ottoman writers used an Arabic-derived script and often drew on Arabic and Persian words and constructions. Letters, songs, popular writing, and conversation did not all sound like formal court prose.", "wiki-turkish") },
      { period: "1928", event: cited("The republic adopted a new Latin alphabet in place of the Ottoman Arabic-derived script. Readers of modern Turkish now need separate training to read older documents.", "wiki-turkish", "unicode-latin") },
      { period: "1930s onward", event: cited("State-led reformers promoted new words and Turkish-rooted alternatives to many Arabic- and Persian-origin terms. Speakers adopted some alternatives widely and kept others beside older words, often with differences in tone and setting.", "wiki-turkish", "tdk-dictionary") }
    ],
    contactHistory: cited("Arabic and Persian contributed many words connected with religion, scholarship, and literature. Turkish speakers also borrowed through everyday contact with Greek, Armenian, Kurdish, Italian, and Balkan languages. Later, French supplied words such as istasyon, “station,” and English became prominent in technology and business.\n\nBorrowed words follow Turkish grammar: kitap, “book,” becomes kitabım, “my book.” The final p changes to b before the vowel of the possession ending. Turkish also left words in neighboring languages during Ottoman rule; a word’s origin tells a history of contact, not how Turkish someone sounds today.", "tdk-dictionary", "wiki-turkish"),
    standardization: cited("Schools, publishers, and broadcasters use a standard centered on Istanbul speech. The Turkish Language Association, or TDK, publishes dictionaries and spelling guidance, while regional speech continues in homes, workplaces, and media. Daily usage does not always follow every official recommendation.\n\nAlphabet and vocabulary reforms changed how readers approach older writing. You can sound out a modern Latin-script page, but an Ottoman document asks you to learn another script and older word choices. You can study that tradition later without making it a condition for ordinary conversation.", "tdk-dictionary", "wiki-turkish")
  },
  variants: {
    overview: cited("The Istanbul-centered standard gives learners a common starting point. Speakers around the Black Sea, Aegean, central and eastern Anatolia, Cyprus, and the Balkans may use different sounds, endings, words, and rhythms. Each region also contains more than one way of speaking.\n\nAge, setting, and migration shape speech within a single city. An Istanbul television presenter and an Istanbul teenager may choose different words. When you meet a form your course never taught, ask who uses it and where before calling it an error.", "wiki-turkish", "tdk-dictionary"),
    items: [
      { name: "Istanbul-centered standard", note: cited("Schools, newsrooms, and most courses teach this variety. Formal writers often turn actions into noun-like or adjective-like forms to fit more information into a sentence. People speaking casually may shorten sounds and use small conversational words that beginner dialogues omit.", "wiki-turkish", "oxford-grammar") },
      { name: "Anatolian regional varieties", note: cited("Western, central, Black Sea, southern, and eastern varieties differ from each other and within their own regions. The TDK dialect dictionary records local words that standard textbooks often leave out.", "tdk-dictionary") },
      { name: "Cypriot Turkish", note: cited("Turkish Cypriots use local forms with their own sounds, vocabulary, and question patterns. A 2024 study describes speakers moving between local and standard forms by setting and relationship. The examples in this guide use the Istanbul-centered standard unless a note says otherwise.", "cypriot-study") },
      { name: "Balkan and diaspora Turkish", note: cited("Communities in southeastern and western Europe speak Turkish alongside other languages. Speakers may switch languages within a conversation or use words familiar to their local community. These are ordinary ways multilingual communities use Turkish.", "wiki-turkish") }
    ]
  },
  pronunciation: {
    overview: cited("Modern Turkish spelling usually gives you a good clue to pronunciation. Its eight vowels divide into front and back groups, and many endings change vowel to match the last vowel of a word. Speakers call this vowel harmony.\n\nThe dotted i and dotless ı name different sounds, even in capitals: İ/i and I/ı. Consonants can also change when an ending joins a word: kitap, “book,” becomes kitabı, “the book,” while the location ending takes t after the final sound of ağaç in ağaçta, “at the tree.” Say whole words aloud to hear these changes together.", "dd-vowels", "dd-consonants", "wiki-turkish"),
    script: "29-letter Turkish Latin alphabet; examples follow standard spelling",
    soundSystem: cited("The front vowels are e, i, ö, ü; the back vowels are a, ı, o, u. The plural ending becomes -ler in evler, “houses,” and -lar in çocuklar, “children.” Other endings choose among ı, i, u, and ü according to the last vowel.\n\nEnglish has no exact counterpart to dotless ı, a high back vowel made without rounded lips. The letters c, ç, ş, and j sound like the main consonants in English jam, church, ship, and the middle of measure, respectively. In the Istanbul-centered standard, ğ often lengthens or links vowels rather than sounding like a hard g.", "dd-vowels", "wiki-turkish"),
    prosody: cited("Many Turkish words place stress near the end, though place names, compounds, and some endings do something else. Keep each vowel clear when a word grows longer. Speakers also shift emphasis to show what is new or contrasted in a sentence.\n\nThe letter e may sound a little more open in some settings; spelling does not mark this difference. Yes/no questions use a separate written word, mı, mi, mu, or mü, and voice pitch also helps signal the question. Listen to a whole clause before copying its rhythm.", "dd-e", "wiki-turkish"),
    learnerTraps: ["Confusing dotted i with dotless ı, especially when typing capital letters", "Pronouncing c like English k or j like English dʒ", "Giving ğ a hard consonant sound in every position", "Choosing suffix vowels from the spelling of the suffix rather than the stem's last vowel", "Ignoring consonant alternations such as kitap → kitabı and ağaç → ağaçta"],
    sampleWords: [
      { original: "kız", translation: "girl; daughter", note: "The dotless ı is a back vowel made without rounded lips. It differs from the sound of i in iz, “trace.”" },
      { original: "gül", translation: "rose; smile!", note: "Practice front rounded ü; context distinguishes the noun from the verb command." },
      { original: "göl", translation: "lake", note: "Ö is front and rounded but lower than ü." },
      { original: "çocuk", translation: "child", note: "Ç sounds like English ch. In çocuğu, “the child” as an object, the final k becomes ğ before the added vowel." },
      { original: "yağmur", translation: "rain", note: "In the Istanbul-centered standard, ğ can lengthen the preceding a here. It does not sound like a hard g." },
      { original: "şişe", translation: "bottle", note: "Ş is sh, and both vowels stay clear." }
    ]
  },
  writing: {
    overview: cited("Turkish writers have used several scripts, and the republic adopted today's Latin alphabet in 1928. It has 29 letters, including ç, ğ, ı, İ, ö, ş, and ü. Treat dotted and dotless i as separate letters when you read, search, and type.\n\nWriters join ordinary endings directly to a word. With a proper name, they usually write an apostrophe before a case or possession ending: Ankara’da means “in Ankara.” TDK spelling rules explain exceptions for names of institutions and other cases.", "wiki-turkish", "unicode-latin", "tdk-spelling"),
    primaryScript: "Turkish Latin alphabet",
    romanization: cited("You can read modern Turkish in its own Latin alphabet, so you do not need a second spelling system. Install a Turkish keyboard early. Typing i in place of ı can change a word, and leaving out ş, ç, ö, or ü can hide its sound.", "unicode-latin"),
    spellingNorms: cited("Writers join most endings to the preceding word. They write the question word mı, mi, mu, or mü separately, even when a person ending follows it: Geldin mi? means “Did you come?” Proper-name endings often take an apostrophe, while institutional names follow a different TDK rule.\n\nYou will also see a circumflex in selected words, such as hâl, to show a spelling distinction or a pronunciation detail. Everyday typing varies, so check the TDK dictionary when a spelling matters in public writing.", "tdk-spelling", "tdk-question", "tdk-dictionary"),
    styleNotes: [
      cited("Modern spelling does not teach you to read Ottoman texts. Those require the older script and familiarity with historical words and genres.", "wiki-turkish"),
      cited("People sometimes leave out special letters in quick messages. Keep them in edited writing: İstanbul and Isparta begin with different kinds of i.", "unicode-latin"),
      cited("Learn where TDK puts the apostrophe with personal and place names, then check its separate rule for institution names.", "tdk-spelling")
    ]
  },
  grammar: {
    overview: cited("Turkish often adds several endings to one word. Evlerimizden means “from our houses”: ev is “house,” -ler is plural, -imiz means “our,” and -den means “from.” Linguists call this pattern agglutination because each piece has a job.\n\nVerbs can also carry endings for negation, ability, time, and person. The vowel in an ending may change to fit the word, and some consonants change at the join. Learn the meaning of each piece, then listen until a familiar chain sounds like one ordinary word.", "dd-grammar", "dd-vowels"),
    typologicalProfile: cited("A Turkish object usually comes before the verb, and the main verb often closes the sentence. A possessor comes before what they own, while descriptive clauses come before the noun they describe. Linguists call this a head-final pattern.\n\nVerb endings can tell you who acts, so speakers often leave out a separate “I” or “you.” Turkish has no grammatical gender and no articles matching English a and the. Speakers move words around to manage the topic or highlight new information; verb-last is a starting point, not a rigid rule.", "oxford-grammar", "wiki-turkish"),
    morphology: cited("Noun endings can show number, ownership, and a word’s role in the sentence. These roles are called cases: an ending may mark a destination, a location, a source, or a particular direct object. Kitap okudum can mean “I read a book,” while Kitabı okudum points to “I read the book.”\n\nVerbs add their own pieces for doing, being able to do, or not doing something, followed by time and person. Try separating a long form with hyphens in your notes. When you write Turkish, join the pieces again.", "oxford-grammar", "dd-grammar"),
    syntax: cited("In a plain statement, Turkish commonly puts the verb last. Speakers often put the new or contrasted item just before it. Hear the whole clause before deciding which English word order best conveys its point.\n\nTurkish also puts descriptive clauses before the noun they describe. Okuduğum kitap means “the book I read”: the action comes first, and an ending connects it to kitap, “book.” These verb forms are called participles when they work like adjectives; they become central to reading longer articles and stories.", "oxford-grammar"),
    advancedPainPoints: ["Choosing accusative marking according to specificity and discourse", "Building and decoding participial relative clauses", "Separating direct past -di from inferential/reported -miş nuances", "Controlling causative, passive, reflexive, and reciprocal suffix sequences", "Following long nominalized clauses in formal prose"],
    topics: [
      { title: "Vowel harmony makes suffix families", body: cited("The plural ending has two shapes: -lar after back vowels and -ler after front vowels. An ending that marks a particular object may take ı, i, u, or ü. Listen to the last vowel before choosing the ending.", "dd-vowels", "dd-grammar"), example: "Sütü içtim. / Kahveyi içtim.", exampleTranslation: "I drank the milk. / I drank the coffee. The object endings use ü and i after different vowels." },
      { title: "Endings show paths and relationships", body: cited("An ending meaning “to” or “toward” marks a destination or recipient; grammars call it dative case. Another marks being “at” a place, and another marks coming “from” it. Learn the ending a verb expects: birine bakmak means “look at someone” even though English uses at.", "dd-grammar", "case-study"), example: "Eve gittim. / Evden geldim.", exampleTranslation: "I went home. / I came from the house. The endings -e and -den mark destination and source." },
      { title: "A particular object takes an ending", body: cited("An object without a case ending can mean an unspecified thing or name an activity. The object ending points to a particular thing already in view; grammars call it the accusative case. English a and the help you feel the contrast, though the two languages do not match perfectly.", "oxford-grammar"), example: "Kahve içiyorum. / Kahveyi içiyorum.", exampleTranslation: "I am drinking coffee. / I am drinking the coffee." },
      { title: "Past forms can show how you learned something", body: cited("A verb ending in -di presents a past event as directly known or plainly asserted. The ending -miş can show that the speaker heard the news, inferred it, or just discovered it. Linguists call that marking of the information source evidentiality; context tells you which meaning is in play.", "turkish-evidential", "oxford-grammar"), example: "Ali gelmiş.", exampleTranslation: "Apparently Ali has come, or I see that Ali came. The speaker does not present the arrival as something directly witnessed." },
      { title: "Ability and inability sit inside the verb", body: cited("A piece inside the verb expresses “can.” Its negative form changes shape rather than simply placing an ordinary negative ending after “can.” Yapabilirim means “I can do it,” while yapamam means “I cannot do it.”", "dd-can"), example: "Artık gidebiliriz. / Şu anda gidemem.", exampleTranslation: "We can go now. / I cannot go right now. The first verb marks ability and the second inability." },
      { title: "Obligation has several strengths", body: cited("The ending -malı/-meli can express “should” or “must.” Zorunda olmak stresses obligation, while gerek or lazım can state that something is needed. A request from a friend and a written rule may choose different forms.", "dd-must", "oxford-grammar"), example: "Para biriktirmem lazım.", exampleTranslation: "I need to save money. The ending on biriktirmem connects the action to me." },
      { title: "Descriptive clauses come before nouns", body: cited("Turkish can put a whole action before the noun it describes. Okuduğum kitap means “the book I read,” with the ending on okuduğum connecting “read” to “book.” Read the action first, then let the following noun complete the idea.", "oxford-grammar", "relative-grammar"), example: "Bu, geçen yıl okuduğum kitap.", exampleTranslation: "This is the book I read last year. The action before kitap identifies which book." },
      { title: "Questions use a separate word", body: cited("For a yes/no question, Turkish writes mı, mi, mu, or mü separately. An ending for the person may attach to that question word. Questions using ne, “what,” do not need it.", "tdk-question", "dd-grammar"), example: "Hazır mısınız?", exampleTranslation: "Are you ready? This addresses several people or one person politely." }
    ]
  },
  whereSpoken: {
    overview: cited("Most Turkish speakers live in Türkiye, and large communities also live beyond its borders. Turkish has official status in the Republic of Cyprus, while Turkish Cypriots maintain local speech alongside the standard. Longstanding Balkan communities and later migration across Europe extend the language's reach.\n\nTelevision, music, football, and online media connect people across these places. Published speaker totals do not always count the same thing: some count first language, some home use, and some heritage ties. That is why this guide does not give one supposedly exact worldwide figure.", "wiki-turkish", "cypriot-study"),
    regions: [
      { place: "Türkiye", note: cited("Schools teach the nationwide standard, while people speak regional Turkish and many other languages. Kurdish, Arabic, Zaza, Laz, Armenian, Greek, Circassian, and migrant languages all belong to the country's daily life. A city name alone cannot tell you everything a resident speaks.", "wiki-turkish") },
      { place: "Cyprus and the eastern Mediterranean", note: cited("Turkish Cypriots use local and standard forms in different settings. Researchers describe variation within Cypriot Turkish itself, including choices shaped by age, place, and contact with Greek. Ask a speaker how they name their own variety rather than treating a political map as a language map.", "cypriot-study") },
      { place: "Balkans", note: cited("Communities in Bulgaria, Greece, North Macedonia, Kosovo, Romania, and nearby areas speak Turkish in different local settings. Schooling, travel, and neighboring languages shape the forms you hear.", "wiki-turkish") },
      { place: "Western Europe", note: cited("Large Turkish-speaking communities live in Germany and across the Netherlands, Austria, Belgium, France, Switzerland, Scandinavia, and the United Kingdom. Many younger speakers learn Turkish at home while using another language at school or work.", "wiki-turkish") }
    ]
  },
  difficulty: {
    label: "Moderate",
    overview: cited("If you speak English, Turkish spelling and repeating endings may feel clear early on. Longer sentences can take more time because the main verb often arrives last and a few endings may carry what English expresses with a whole clause. Discover Discomfort's learner account separates these stages.\n\nYour background matters too. A heritage speaker may know everyday conversation but want more reading practice; someone who knows another language with long suffix chains may recognize the structure sooner. An hour estimate cannot describe both learners.", "dd-hard", "dd-grammar"),
    easierAspects: ["Highly consistent modern spelling", "Regular suffix families and few irregular verb paradigms", "No grammatical gender or noun classes", "Abundant television, music, tutors, dictionaries, and learner media", "Subjects can be omitted once verb endings are familiar"],
    hardAspects: ["Hearing vowel harmony and suffix boundaries at conversational speed", "Case selection with individual verbs", "Participles and nominalizations in long sentences", "Vocabulary layers across casual, formal, and older registers", "Pragmatic meanings of word order and evidential forms"],
    plateauRisks: ["Admiring suffix logic without doing enough listening", "Reading every sentence in English order before finding the final verb", "Treating -miş as a single mechanical hearsay tense", "Avoiding Turkish-only dictionaries and remaining dependent on one-word translations"],
    workload: cited("At the beginning, pair short daily listening with a small set of verbs and endings you can hear again tomorrow. Take five real sentences, mark the ending boundaries, and say the whole sentences aloud. Ask a teacher or conversation partner which forms sound natural in their setting.\n\nLater, watch one short scene with Turkish subtitles and retell it without them. Read news alongside interviews so written and spoken word order both become familiar. Novels, comedy, and fast group conversation take sustained contact beyond a first travel course.", "dd-hard", "dd-reasons")
  },
  advancedLearning: {
    strategy: cited("First, learn to hear a familiar ending inside a whole word. Next, collect full sentences with forms such as okuduğum, “that I read,” and mark who did the action. A grammar book can explain the pieces; a teacher can tell you how a complete sentence sounds in a real exchange.\n\nAt an intermediate level, retell one news story in conversational Turkish, then compare your version with the written article. Ask for feedback on what you placed before the final verb as well as on the endings. Discover Discomfort's grammar articles give another explanation when harmony, ability, or obligation feels unclear.", "dd-grammar", "dd-vowels", "dd-must"),
    mediaPractice: cited("Turkish television gives you many hours of dialogue. Choose a short scene and listen for how speakers address each other, where they put the verb, and what the subtitles leave out. Replay it without text before moving on.\n\nThen add interviews, radio, comedy, or speakers from the region you care about. Songs can teach recurring expressions, though melody may change normal stress. If you already follow football, cooking, or design, find a Turkish voice on that subject and keep returning to it.", "dd-reasons", "dd-phrases"),
    dictionariesAndCorpora: cited("Use the TDK dictionary to check a Turkish word's spelling, meaning, and idioms. The Turkish National Corpus lets researchers search collected writing and speech, although access may require registration. Save a complete example whenever you look up a new word.\n\nA bilingual dictionary can give you a first candidate. A Turkish definition and several real sentences show whether that candidate sounds casual, formal, regional, or old-fashioned. Keep those labels with the example rather than with a bare English gloss.", "tdk-dictionary", "tnc"),
    resources: [
      { type: "other", title: "Discover Discomfort: Turkish Grammar Overview", url: "https://discoverdiscomfort.com/turkish-grammar-overview-for-learners/", level: "beginner", description: cited("Start here to see how endings, vowel harmony, cases, and word order fit together. Check its examples against a reference grammar when you need finer detail.", "dd-grammar", "oxford-grammar") },
      { type: "other", title: "Discover Discomfort: Turkish Vowel Harmony", url: "https://discoverdiscomfort.com/turkish-vowel-harmony/", level: "beginner", description: cited("The two-way and four-way ending patterns are easy to scan here. Use a dictionary to verify spellings in examples before you copy them.", "dd-vowels", "tdk-dictionary") },
      { type: "dictionary", title: "Türk Dil Kurumu Dictionaries", url: "https://sozluk.gov.tr/", level: "all", description: cited("Search Turkish definitions and idioms here. The site suits readers who can already work with short Turkish explanations.", "tdk-dictionary") },
      { type: "corpus", title: "Turkish National Corpus", url: "https://www.tnc.org.tr/", level: "advanced", description: cited("Search collected texts for the company a word keeps and the genres where it appears. Check current access requirements before planning a lesson around it.", "tnc") },
      { type: "book", title: "The Oxford Turkish Grammar", url: "https://global.oup.com/academic/product/the-oxford-turkish-grammar-9780198851509", level: "advanced", description: cited("Gerjan van Schaaik gives a detailed reference for longer clauses and endings that a first course may only introduce. It is a reference book, not a first-week conversation course.", "oxford-grammar") }
    ]
  },
  wordsAndTexts: {
    overview: cited("Turkish speakers have short expressions for particular moments. Say Kolay gelsin to someone working, Elinize sağlık to thank someone for what they made, and Geçmiş olsun after illness or another setback. Each expression names the other person's situation more precisely than a general “thanks” or “sorry.”\n\nVocabulary also carries the history of reform. An older Arabic-origin word may sit beside a newer Turkish-rooted alternative. Speakers may choose between them by habit, age, setting, or the phrase around them.", "dd-miss", "dd-phrases", "tdk-dictionary"),
    notableWords: [
      { term: "gönül", meaning: "inner heart; feeling; affection", note: cited("People use gönül for feeling, affection, and desire rather than for the physical organ alone. Songs and poems give it many shades, so read the whole phrase before choosing an English word.", "tdk-dictionary") },
      { term: "yakamoz", meaning: "glimmer stirred in the sea", note: cited("TDK defines yakamoz first as the glimmer made when fish or oars disturb seawater. It also names a light-producing marine animal. Moonlight alone does not match either dictionary meaning.", "tdk-yakamoz") },
      { term: "imece", meaning: "shared voluntary work", note: cited("Neighbors traditionally came together for a task that one household could not easily do alone. Writers can also use imece for a new cooperative project.", "tdk-dictionary") },
      { term: "hüzün", meaning: "sadness; melancholy", note: cited("This Arabic-origin word can name ordinary sadness. A novelist or songwriter may give it a broader mood through the surrounding story.", "tdk-dictionary") },
      { term: "kısmet", meaning: "fortune; one's allotted share", note: cited("Someone may say kısmet while hoping for an opportunity or accepting that a plan depends on events beyond them. Tone tells you whether they sound hopeful, resigned, or playful.", "tdk-dictionary") },
      { term: "gurbet", meaning: "being away from home", note: cited("In migration songs, gurbet can carry the loneliness of living far from home. It can also name the distant place itself.", "tdk-dictionary") },
      { term: "merak", meaning: "curiosity; interest; worry", note: cited("Merak etmek may mean “wonder about” or “worry about.” The object of the sentence and the situation tell you which sense fits.", "tdk-dictionary") }
    ],
    loanwordLayers: cited("Common verbs, family words, body words, and endings show the Turkic inheritance. Arabic and Persian contributed vocabulary for religion, government, learning, and literature; French later supplied words such as gar, “station,” and kuaför, “hairdresser.” English now contributes technology and business terms.\n\nReformers also promoted words such as olanak alongside older imkân, both meaning “possibility.” A speaker's choice may depend on the sentence, generation, or setting. Once people borrow a word, they can give it Turkish endings, new meanings, and a place in jokes or songs.", "wiki-turkish", "tdk-dictionary"),
    idioms: [
      { original: "Etekleri zil çalmak", translation: "To be overjoyed", note: "The picture is of someone's skirts ringing like bells. Say it when a person can barely contain their happiness." },
      { original: "Pabucu dama atılmak", translation: "To lose favor to a newer favorite", note: "The image puts someone's shoe on the roof. Speakers use it when another person or thing takes their place in someone's attention." },
      { original: "İğneyle kuyu kazmak", translation: "To do painfully slow, demanding work", note: "The image has someone digging a well with a needle. It fits a task that takes great patience with limited tools." },
      { original: "Dereyi görmeden paçaları sıvamak", translation: "To prepare too early", note: "Someone rolls up their trouser legs before they have even seen the stream. The phrase warns against acting before you know what lies ahead." },
      { original: "Bir taşla iki kuş vurmak", translation: "To achieve two goals with one action", note: "The image matches the English saying about two birds and one stone. Check the surrounding sentence to see which two goals the speaker means." }
    ],
    textGenres: ["Ottoman divan poetry and prose, requiring historical language and script", "Folk poetry, aşık performance, türkü songs, and oral narrative", "Modern novels, short stories, memoirs, essays, and graphic narratives", "Newspaper columns and long-form political or cultural commentary", "Television drama, cinema, stand-up, podcasts, and pop or alternative music", "Diaspora literature and multilingual digital culture"]
  },
  relationships: { overview: cited("Turkish shares its family history with other Turkic languages. Azerbaijani, Turkmen, and Gagauz sit with it in the Oghuz branch, while Uzbek, Kazakh, Kyrgyz, Uyghur, Tatar, and Sakha are more distant relatives. Shared ancestry does not guarantee that two speakers can follow a quick conversation.\n\nArabic, Persian, Greek, Armenian, Kurdish, French, and Balkan languages contributed words and influenced local styles through contact. Those connections do not place them in the Turkic family. Compare an inherited ending with a borrowed noun and you can see both histories at work.", "glottolog", "wiki-turkish"), languages: relatedLanguages },
  culturalNotes: "People who speak Turkish have different ethnicities, faiths, politics, and relationships to Türkiye. Many also speak another language from childhood. An Istanbul television voice tells you little about the full range of those lives.\n\nForms of address show how speakers relate to each other. Sen is familiar singular “you,” while siz addresses several people or one person politely. Words such as hocam, abi, abla, bey, and hanım carry shades of respect, warmth, age, or distance that a single English title cannot capture.",
  resources: [
    { type: "other", title: "Discover Discomfort Turkish Grammar Series", url: "https://discoverdiscomfort.com/turkish-grammar-overview-for-learners/", level: "all", description: cited("Read the main guide, then follow its focused articles on harmony, ability, and obligation when a sentence raises a question.", "dd-grammar") },
    { type: "other", title: "Discover Discomfort Everyday Turkish Phrases", url: "https://discoverdiscomfort.com/turkish-phrases-everyday/", level: "beginner", description: cited("Hear short everyday requests and replies with audio. The writer describes a visitor's experience, so check with local speakers before carrying a phrase into every setting.", "dd-phrases") },
    { type: "other", title: "Discover Discomfort: How Hard Is Turkish?", url: "https://discoverdiscomfort.com/how-hard-is-turkish/", level: "beginner", description: cited("Read one learner's account of spelling, listening, and grammar challenges. Use it to plan practice, not to predict your own timetable.", "dd-hard") },
    { type: "dictionary", title: "TDK Online Dictionaries", url: "https://sozluk.gov.tr/", level: "all", description: cited("Look up spelling, Turkish definitions, idioms, and proverbs. Check which dictionary section supplied a result.", "tdk-dictionary") },
    { type: "corpus", title: "Turkish National Corpus", url: "https://www.tnc.org.tr/", level: "advanced", description: cited("Compare a new word across collected texts instead of guessing its tone from one web result. Access may require registration.", "tnc") },
    { type: "book", title: "The Oxford Turkish Grammar", url: "https://global.oup.com/academic/product/the-oxford-turkish-grammar-9780198851509", level: "advanced", description: cited("Consult its detailed treatment of verbs and long clauses when a short lesson leaves a question open.", "oxford-grammar") }
  ],
  relatedLanguages,
  phrases: [
    { original: "Merhaba", translation: "Hello.", usageNote: "A broad greeting when you arrive or address someone." },
    { original: "Günaydın", translation: "Good morning.", usageNote: "Say this during the morning at home, in a shop, or at work." },
    { original: "Nasılsınız?", translation: "How are you?", usageNote: "Polite or plural; Nasılsın? is singular and familiar." },
    { original: "Teşekkür ederim", translation: "Thank you.", usageNote: "Teşekkürler is a common shorter alternative." },
    { original: "Rica ederim", translation: "You're welcome.", literalMeaning: "I request/ask it.", usageNote: "A conventional response to thanks." },
    { original: "Affedersiniz", translation: "Excuse me; pardon me.", usageNote: "Say it to get someone's attention politely or to apologize." },
    { original: "Türkçe öğreniyorum", translation: "I am learning Turkish." },
    { original: "Biraz daha yavaş konuşabilir misiniz?", translation: "Could you speak a little more slowly?", usageNote: "Use this with someone you address politely; misiniz carries that form of “you.”" },
    { original: "Bu ne demek?", translation: "What does this mean?" },
    { original: "Ne kadar?", translation: "How much?", usageNote: "Also means “how much/how many” more generally." },
    { original: "Kolay gelsin", translation: "May your work come easily.", usageNote: "Say this to someone working as you arrive, pass, or leave." },
    { original: "Elinize sağlık", translation: "Thank you for making/cooking this.", literalMeaning: "Health to your hands.", usageNote: "Polite or plural; eline sağlık is familiar singular." },
    { original: "Geçmiş olsun", translation: "Get well soon; may the trouble be behind you.", usageNote: "Used after illness, an accident, or another unpleasant event." },
    { original: "Görüşürüz", translation: "See you.", literalMeaning: "We will see one another." }
  ],
  sources: [
    { id: "dd-grammar", title: "Turkish Grammar — The Main Features for Learners", url: "https://discoverdiscomfort.com/turkish-grammar-overview-for-learners/", publisher: "Discover Discomfort", publishedAt: "2023-08-14", updatedAt: "2023-09-14", accessedAt: "2026-09-27" },
    { id: "dd-vowels", title: "Turkish Vowel Harmony Explained Simply", url: "https://discoverdiscomfort.com/turkish-vowel-harmony/", publisher: "Discover Discomfort", publishedAt: "2023-09-01", updatedAt: "2023-09-14", accessedAt: "2026-09-27" },
    { id: "dd-consonants", title: "Turkish Consonant Harmony", url: "https://discoverdiscomfort.com/turkish-consonant-harmony/", publisher: "Discover Discomfort", publishedAt: "2023-09-14", accessedAt: "2026-09-27" },
    { id: "dd-e", title: "How to Pronounce E in Turkish", url: "https://discoverdiscomfort.com/how-to-pronounce-e-in-turkish/", publisher: "Discover Discomfort", publishedAt: "2023-10-24", accessedAt: "2026-09-27" },
    { id: "dd-can", title: "How to Say Can or Cannot in Turkish", url: "https://discoverdiscomfort.com/can-or-cannot-in-turkish/", publisher: "Discover Discomfort", publishedAt: "2023-09-30", accessedAt: "2026-09-27" },
    { id: "dd-must", title: "Should, Must, and Have To in Turkish", url: "https://discoverdiscomfort.com/should-must-have-to-in-turkish/", publisher: "Discover Discomfort", publishedAt: "2023-09-19", accessedAt: "2026-09-27" },
    { id: "dd-phrases", title: "Turkish Words and Phrases for Everyday Life", url: "https://discoverdiscomfort.com/turkish-phrases-everyday/", publisher: "Discover Discomfort", publishedAt: "2023-09-10", updatedAt: "2024-08-25", accessedAt: "2026-09-27" },
    { id: "dd-miss", title: "The Turkish Phrases I'll Most Miss from Türkiye", url: "https://discoverdiscomfort.com/turkish-phrases-ill-miss/", publisher: "Discover Discomfort", publishedAt: "2024-01-30", accessedAt: "2026-09-27" },
    { id: "dd-hard", title: "How Hard Is Turkish?", url: "https://discoverdiscomfort.com/how-hard-is-turkish/", publisher: "Discover Discomfort", publishedAt: "2023-09-08", updatedAt: "2023-09-14", accessedAt: "2026-09-27" },
    { id: "dd-reasons", title: "Why Learn Turkish?", url: "https://discoverdiscomfort.com/learn-turkish-reasons/", publisher: "Discover Discomfort", publishedAt: "2023-09-27", accessedAt: "2026-09-27" },
    { id: "wiki-turkish", title: "Turkish language", url: "https://en.wikipedia.org/wiki/Turkish_language", publisher: "Wikipedia", accessedAt: "2026-09-27" },
    { id: "tdk-dictionary", title: "Türk Dil Kurumu Sözlükleri", url: "https://sozluk.gov.tr/", publisher: "Türk Dil Kurumu", accessedAt: "2026-09-27" },
    { id: "tdk-yakamoz", title: "Güncel Türkçe Sözlük: yakamoz", url: "https://sozluk.gov.tr/gts?ara=yakamoz", publisher: "Türk Dil Kurumu", accessedAt: "2026-09-27" },
    { id: "tdk-spelling", title: "Kesme İşareti", url: "https://tdk.gov.tr/icerik/yazim-kurallari/kesme-isareti/", publisher: "Türk Dil Kurumu", publishedAt: "2019-01-30", accessedAt: "2026-09-27" },
    { id: "tdk-question", title: "Soru Eki mı, mi, mu, mü’nün Yazılışı", url: "https://tdk.gov.tr/icerik/yazim-kurallari/soru-eki-mi-mi-mu-munun-yazilisi/", publisher: "Türk Dil Kurumu", publishedAt: "2019-01-20", accessedAt: "2026-09-27" },
    { id: "cypriot-study", title: "Gidecen/Gidecek min/Gidecek misin? Where Turkish Cypriots Think Dialect Variation Is Going", url: "https://edizionicafoscari.it/media/pdf/books/978-88-6969-800-2/978-88-6969-800-2_vBCfXJs.pdf", publisher: "Edizioni Ca’ Foscari", publishedAt: "2024-07-18", accessedAt: "2026-09-27" },
    { id: "turkish-evidential", title: "The Evidential in Turkish", url: "https://library.dogus.edu.tr/mvt/pdf.php?lng=1&pdf=0016177", publisher: "Doğuş University Library", accessedAt: "2026-09-27" },
    { id: "case-study", title: "GoURMET Survey of Relevant Low-Resource Languages", url: "https://gourmet-project.eu/wp-content/uploads/2019/05/GoURMET_D1_1.pdf", publisher: "GoURMET H2020 Project", accessedAt: "2026-09-27" },
    { id: "relative-grammar", title: "Basic Participles in Turkish", url: "https://www.settemilalingue.com/en/languages/tr/grammar/basic-participles", publisher: "Settemila Lingue", accessedAt: "2026-09-27" },
    { id: "glottolog", title: "Glottolog: Turkish", url: "https://glottolog.org/resource/languoid/id/nucl1301", publisher: "Glottolog", accessedAt: "2026-09-27" },
    { id: "unicode-latin", title: "The Unicode Standard, Latin", url: "https://www.unicode.org/versions/Unicode17.0.0/core-spec/chapter-7/", publisher: "Unicode Consortium", updatedAt: "2025", accessedAt: "2026-09-27" },
    { id: "tnc", title: "Turkish National Corpus", url: "https://www.tnc.org.tr/", publisher: "Mersin University", accessedAt: "2026-09-27" },
    { id: "oxford-grammar", title: "The Oxford Turkish Grammar", url: "https://global.oup.com/academic/product/the-oxford-turkish-grammar-9780198851509", publisher: "Oxford University Press", publishedAt: "2020", accessedAt: "2026-09-27" }
  ],
  seo: { title: "Turkish (Türkçe): Sounds, Grammar, History and Everyday Speech", description: "See how Turkish builds words with endings, how speakers use local and standard forms, and where to start with its alphabet, phrases, history, and learning resources." }
} satisfies LanguageGuide;
