import { cited } from "../citations.js";
import type { LanguageGuide } from "../types.js";

const relatedLanguages = [
  { name: "Azerbaijani", relationship: "Closest major Oghuz relative", explanation: cited("Turkish and Azerbaijani share much basic grammar and vocabulary, and patient speakers can often establish partial understanding. They are separate standards with different sound changes, conventional vocabulary, and modern histories; reading one is easier than following every rapid conversation in the other.", "glottolog", "wiki-turkish") },
  { name: "Turkmen", relationship: "Eastern Oghuz relative", explanation: cited("Turkmen preserves an Oghuz inheritance recognizable in Turkish suffixes and core words, but its sound system, lexicon, and literary standard make it a language to learn rather than a Turkish dialect. Comparison reveals which familiar patterns are broadly Turkic and which belong specifically to Turkey Turkish.", "glottolog") },
  { name: "Persian", slug: "persian", relationship: "Unrelated language with deep literary contact", explanation: cited("Persian is Indo-European, not Turkic, yet Persian literary culture profoundly influenced Ottoman vocabulary, compounds, courtly style, and poetic genres. Modern Turkish retains many Persian-origin words even after twentieth-century lexical reform.", "wiki-turkish", "tdk-dictionary") },
  { name: "Arabic", slug: "arabic", relationship: "Unrelated language with religious and scholarly contact", explanation: cited("Arabic supplied a large learned vocabulary to Ottoman Turkish, often through Persian conventions. Many such words remain ordinary today, but Turkish grammar stayed Turkic: a shared noun never implies shared sentence structure.", "wiki-turkish", "tdk-dictionary") }
] satisfies LanguageGuide["relationships"]["languages"];

export const turkishGuide = {
  slug: "turkish",
  name: "Turkish",
  autonym: "Türkçe",
  status: "published",
  publishedAt: "2026-07-09",
  summary: "Turkish builds remarkably precise meanings from orderly suffixes, carries the layered history of Anatolia and the Ottoman world, and lives today in conversation, film, music, journalism, and a vast transnational community.",
  family: "Turkic, Oghuz",
  macroRegion: "Anatolia, Cyprus, the Balkans, and European diasporas",
  primaryScript: "Latin",
  difficultyLabel: "Moderate",
  learnerHook: "A single Turkish word can unfold like a compact sentence: once its suffixes become audible, menus, headlines, family conversations, songs, and novels begin exposing an elegant logic that translation often hides.",
  hero: { imageAlt: "Contemporary Turkish print and handwriting showing the dotted and dotless i and other distinctive letters.", callToActionLabel: "Explore Turkish in use" },
  classification: "An Oghuz Turkic language and the national standard of Türkiye",
  speakerCommunity: "Turkish is the first language of most people in Türkiye and a major community language in Cyprus, the Balkans, Western Europe, Australia, and North America. Its public life spans informal neighborhood speech, regionally colored conversation, a nationwide school and broadcast standard, highly conventional bureaucratic prose, and creative digital slang. Many citizens of Türkiye also speak Kurdish, Arabic, Zaza, Armenian, Greek, Laz, Circassian languages, or other languages; Turkish identity and linguistic biography are therefore not one simple category. Diaspora Turkish can conserve older expressions, absorb German, Dutch, French, or English, and develop its own styles without becoming defective Turkish.",
  facts: [
    { label: "Family", value: "Turkic · Common Turkic · Oghuz" },
    { label: "Standard base", value: "Istanbul-centered modern Turkish" },
    { label: "Alphabet", value: "29 Latin letters since 1928" },
    { label: "Core profile", value: "Suffixing, agglutinative, vowel-harmonizing, generally head-final" },
    { label: "Gender", value: "No grammatical gender in pronouns or nouns" },
    { label: "Major communities", value: "Türkiye, Cyprus, the Balkans, and a large European diaspora" }
  ],
  learnerOverview: "Turkish gives beginners unusually clean feedback. The alphabet is close to phonemic, meaning letters correspond fairly consistently to sounds; plural -lar/-ler and location -da/-de soon reveal how suffixes adapt to a stem. That regularity is real, but it is only the entrance. Natural Turkish depends on choosing cases with particular verbs, placing information before the verb, hearing omitted subjects, and unpacking participles that English turns into relative clauses. Begin with usable chunks—Kolay gelsin, Ne demek?, Görüşürüz—then take them apart. Keep a suffix notebook organized by function, not an intimidating table: movement toward, location, source, possession, tense, evidence. Discover Discomfort's learner accounts are especially helpful because they describe where transparent spelling stops being enough. Alternate structured grammar with a daily Turkish voice: one series, podcast, tutor, or friend. The aim is not to manufacture record-length words, but to recognize ordinary forms instantly: evlerimizden “from our houses,” yapabilirim “I can do it,” gelmiş “apparently he or she came.”",
  origins: {
    overview: cited("Turkish belongs to the Oghuz branch of the Turkic family. Oghuz-speaking groups moved westward into Iran and Anatolia over centuries, especially in the Seljuk and post-Seljuk periods, entering landscapes already rich in Greek, Armenian, Kurdish, Arabic, Persian, and other languages. Written Anatolian Turkish developed from the late medieval period; Ottoman Turkish later served an empire whose administration and literary culture drew heavily on Arabic and Persian. That history produced a striking combination: fundamentally Turkic suffixes and syntax carrying a multilingual learned lexicon. Everyday speech never matched the most ornate court prose exactly. Modern standard Turkish emerged from this continuum, not from a clean rupture between two unrelated languages.", "wiki-turkish", "glottolog"),
    timeline: [
      { period: "11th–13th centuries", event: cited("Oghuz Turkic speakers became increasingly established in Anatolia. Contact and bilingualism shaped vocabulary and place-based varieties while Turkic grammatical structure remained recognizable.", "wiki-turkish", "glottolog") },
      { period: "13th–15th centuries", event: cited("Old Anatolian Turkish appears in religious, literary, administrative, and practical texts. Writers made different choices about the growing Arabic and Persian learned vocabulary, so there was never one simple spoken-versus-written line.", "wiki-turkish") },
      { period: "15th–19th centuries", event: cited("Ottoman Turkish developed elaborate written registers using an Arabic-derived script and extensive Arabic-Persian vocabulary and constructions. Popular writing, correspondence, songs, and speech remained more varied and often more transparently Turkic than elite prose.", "wiki-turkish") },
      { period: "1928", event: cited("The republic replaced the Ottoman Arabic-derived writing system with a purpose-designed Latin alphabet. The change made modern print highly sound-transparent but also placed older archives behind a separate literacy skill.", "wiki-turkish", "unicode-latin") },
      { period: "1930s onward", event: cited("State-led language reform promoted Turkish-rooted replacements for many Arabic- and Persian-origin words and created terminology for modern institutions and science. Adoption was uneven, leaving speakers with productive layers of older, newer, formal, and colloquial vocabulary.", "wiki-turkish", "tdk-dictionary") }
    ],
    contactHistory: cited("Turkish vocabulary is a map of mobility. Arabic and Persian shaped religion, scholarship, literature, and administration; Greek, Armenian, Kurdish, Italian, and Balkan languages reflect trade and shared local life; French supplied much nineteenth- and early twentieth-century modern vocabulary; English is prominent in technology and business today. Borrowings are remodeled by Turkish sounds and suffixes: kitap “book” takes kitabım “my book,” with consonant alternation, and French station became istasyon. Turkish also contributed words and structures to neighboring languages during Ottoman rule. Etymology should illuminate encounters, not rank words as pure or impure.", "tdk-dictionary", "wiki-turkish"),
    standardization: cited("The Istanbul-centered standard dominates national education, publishing, subtitling, and broadcasting, while the Turkish Language Association (Türk Dil Kurumu, TDK) publishes dictionaries and orthographic guidance. Standardization did not erase regional speech, and actual educated usage sometimes outruns official recommendations. The alphabet and lexical reforms altered access to the past: a contemporary reader can pronounce a 1930s Latin-script page, yet an Ottoman document requires another script plus historical vocabulary and genres. Learners should treat Ottoman Turkish as an optional later specialization, not as a prerequisite for conversation.", "tdk-dictionary", "wiki-turkish")
  },
  variants: {
    overview: cited("“Standard Turkish” is useful but incomplete. Regional varieties differ in vowels, consonants, tense forms, particles, vocabulary, and melody; social setting and generation matter too. Black Sea, Aegean, Central Anatolian, eastern, Balkan, and Cypriot speech each contain internal diversity. Istanbul itself includes migration-shaped voices rather than one museum accent. Learn the standard for maximum access, then label forms by person and place instead of dismissing them as errors.", "wiki-turkish", "tdk-dictionary"),
    items: [
      { name: "Istanbul-centered standard", note: cited("The basis of school, news, and most teaching materials. Formal writing tends to pack information into nominalizations and participles; relaxed Istanbul conversation reduces sounds and favors discourse particles absent from beginner dialogues.", "wiki-turkish") },
      { name: "Anatolian regional varieties", note: cited("A broad label covering substantial western, central, Black Sea, southern, and eastern differences. The TDK dialect dictionary documents regional vocabulary rather than treating the standard as the whole language.", "tdk-dictionary") },
      { name: "Cypriot Turkish", note: cited("A living regional variety shaped by Cyprus's history and contact ecology. It has characteristic intonation, sounds, particles, and vocabulary; speakers also command forms closer to the transnational standard in formal settings.", "wiki-turkish") },
      { name: "Balkan and diaspora Turkish", note: cited("Communities in southeastern Europe and Western Europe maintain Turkish alongside other languages. Code-switching, heritage-language schooling, and contact innovations are part of their linguistic lives, not proof of incomplete competence.", "wiki-turkish") }
    ]
  },
  pronunciation: {
    overview: cited("Turkish pronunciation is approachable because modern spelling is systematic, but three details separate careful speech from letter reading. The eight vowels form front/back and rounded/unrounded sets that control harmony. The letters ı and i represent different vowels and retain their identities in uppercase: I/ı versus İ/i. Consonants change at suffix boundaries: kitap becomes kitabı “the book” in the accusative, while a suffix beginning with d may surface with t after a voiceless consonant. Discover Discomfort's harmony guides present these alternations as connected habits rather than exceptions to memorize separately.", "dd-vowels", "dd-consonants", "dd-e"),
    script: "29-letter Turkish Latin alphabet; examples follow standard spelling",
    soundSystem: cited("The front vowels are e, i, ö, ü; the back vowels are a, ı, o, u. Many suffixes choose between two shapes (-lar/-ler) or four (-ı/-i/-u/-ü) according to the last vowel: evler “houses,” çocuklar “children,” evi “the house,” yolu “the road.” The dotless ı is a high back unrounded vowel, not an unstressed English i. Ö and ü resemble their German values. C is /dʒ/ as in English jam; ç is /tʃ/; ş is /ʃ/; j is /ʒ/. Ğ, yumuşak ge or “soft g,” usually lengthens or links surrounding vowels rather than sounding like a hard g in standard speech.", "dd-vowels", "dd-consonants", "wiki-turkish"),
    prosody: cited("Word stress often falls late, but common suffixes, place names, compounds, and sentence focus complicate the shortcut. Turkish rhythm depends on keeping vowels distinct even inside long words. The letter e can be somewhat more open or closed according to environment, a nuance Discover Discomfort examines without pretending it creates a simple spelling contrast. Questions carry both the separate particle mı/mi/mu/mü and characteristic intonation. Shadow whole clauses, because a mechanically perfect suffix chain can still sound puzzling if focus lands on the wrong word.", "dd-e", "wiki-turkish"),
    learnerTraps: ["Confusing dotted i with dotless ı, especially when typing capital letters", "Pronouncing c like English k or j like English dʒ", "Giving ğ a hard consonant sound in every position", "Choosing suffix vowels from the spelling of the suffix rather than the stem's last vowel", "Ignoring consonant alternations such as kitap → kitabı and ağaç → ağaçta"],
    sampleWords: [
      { original: "kız", transliteration: "kuz without lip rounding", translation: "girl; daughter", note: "The dotless ı is high and back; it is not English ee." },
      { original: "gül", translation: "rose; smile!", note: "Practice front rounded ü; context distinguishes the noun from the verb command." },
      { original: "göl", translation: "lake", note: "Ö is front and rounded but lower than ü." },
      { original: "çocuk", translation: "child", note: "Ç is English ch; the final suffix vowel in çocuğu changes with harmony and consonant softening." },
      { original: "yağmur", translation: "rain", note: "The ğ links or lengthens the vowel sequence rather than behaving like hard g." },
      { original: "şişe", translation: "bottle", note: "Ş is sh, and both vowels stay clear." }
    ]
  },
  writing: {
    overview: cited("Turkish has used several scripts across its history; the modern Republic adopted its Latin alphabet in 1928. Its 29 letters omit q, w, and x from native spelling and add ç, ğ, ı, İ, ö, ş, and ü. This is not English orthography with decorations: each dotted form is a separate letter, and Turkish alphabetical order reflects that. Spelling makes suffix structure visible, so reading aloud and grammatical analysis reinforce each other. Apostrophes separate most suffixes attached to proper names—Ankara'da “in Ankara”—but ordinary nouns take suffixes directly.", "wiki-turkish", "unicode-latin", "tdk-dictionary"),
    primaryScript: "Turkish Latin alphabet",
    romanization: cited("No separate romanization is normally needed because Turkish already uses Latin letters. English-only keyboards are risky: replacing ı with i can change a word, and replacing ş, ç, ö, or ü obscures pronunciation. Install a Turkish keyboard and learn I/İ capitalization from the first week.", "unicode-latin"),
    spellingNorms: cited("Suffixes normally join the word, creating long but transparent forms; the question particle mı/mi/mu/mü is written separately even though later personal endings attach to it: Geldin mi? “Did you come?” Proper-name suffixes usually follow an apostrophe, while derivational suffixes can behave differently under detailed TDK rules. Circumflexes survive in selected words to mark length or distinctions, but everyday usage varies. Consult the current TDK dictionary rather than guessing from social media typography.", "tdk-dictionary", "dd-grammar"),
    styleNotes: [
      cited("Modern spelling is not a dependable key to Ottoman texts: those require the Arabic-derived script, historical vocabulary, and conventions of genre.", "wiki-turkish"),
      cited("Informal messages often omit diacritics for keyboard convenience, yet polished public writing expects them and search results can change without them.", "unicode-latin"),
      cited("Turkish punctuation resembles wider European practice, but suffix attachment and capitalization around proper names deserve specific attention.", "tdk-dictionary")
    ]
  },
  grammar: {
    overview: cited("Turkish is agglutinative: grammatical pieces tend to attach in an ordered chain and remain recognizable. Ev “house” can become evlerimizden “from our houses” (ev-ler-imiz-den). This is not a party trick; ordinary verbs routinely encode negation, ability, tense, evidence, person, and questions around one stem. Harmony changes a suffix's surface vowels, and consonant rules smooth boundaries. The system is regular enough to analyze, while real mastery requires knowing which meaning and case a situation invites.", "dd-grammar", "dd-vowels"),
    typologicalProfile: cited("Turkish is strongly suffixing and generally head-final: objects commonly precede verbs, possessors precede possessed nouns, and relative information appears before the noun it modifies. It allows subjects to be omitted because verb endings identify person, and it has no grammatical gender or articles equivalent to English a/the. Word order remains flexible for topic, contrast, and focus, so “SOV” describes a neutral tendency rather than a cage.", "oxford-grammar", "glottolog"),
    morphology: cited("Nouns mark plural, possession, and cases such as accusative, dative, locative, ablative, and genitive. The accusative often signals a specific or identifiable direct object: Kitap okudum “I read a book/books,” but Kitabı okudum “I read the book.” Verbs build from stem through voice, negation, ability, tense/aspect/mood, and person. Learners should segment authentic words with hyphens temporarily, then return to standard joined spelling.", "oxford-grammar", "dd-grammar"),
    syntax: cited("Neutral clauses place the verb last, but known material often moves earlier and focused material tends to sit immediately before the verb. Turkish subordination frequently turns an event into a noun or adjective: geldiğini biliyorum is literally close to “I know your/his/her coming” and naturally means “I know that you/he/she came.” Participles distinguish whether the modified noun is understood as the embedded subject or another role. This compact architecture is the main bridge from textbook survival Turkish to essays and serious conversation.", "oxford-grammar", "oxford-grammar"),
    advancedPainPoints: ["Choosing accusative marking according to specificity and discourse", "Building and decoding participial relative clauses", "Separating direct past -di from inferential/reported -miş nuances", "Controlling causative, passive, reflexive, and reciprocal suffix sequences", "Following long nominalized clauses in formal prose"],
    topics: [
      { title: "Vowel harmony makes suffix families", body: cited("Plural has two common shapes: -lar after back vowels and -ler after front vowels. Four-way suffixes choose ı, i, u, or ü. Learn one function with its harmony template, then say it across contrasting stems until sound predicts spelling.", "dd-vowels"), example: "ev-ler-de / okul-lar-da", exampleTranslation: "in the houses / in the schools" },
      { title: "Cases encode paths and relationships", body: cited("The dative -a/-e marks movement toward and recipients; locative -da/-de marks location; ablative -dan/-den marks movement or origin. Verbs govern cases idiomatically, so note birine bakmak “look at someone” with dative rather than translating English prepositions.", "dd-grammar"), example: "Arkadaşıma evden bir mesaj gönderdim.", exampleTranslation: "I sent my friend a message from home." },
      { title: "Specific objects take accusative", body: cited("An unmarked object is commonly nonspecific or incorporated into the activity, while accusative marking identifies a particular object. This contrast is about discourse meaning, not simply English definite articles.", "oxford-grammar"), example: "Kahve içiyorum. / Kahveyi içiyorum.", exampleTranslation: "I am drinking coffee. / I am drinking the coffee." },
      { title: "Past tense can mark the evidence path", body: cited("The -di past normally presents an event as directly known or asserted. The -miş form can report what was learned from others, inferred from evidence, newly discovered, or expressed with surprise; context and intonation decide the nuance. Calling it only “hearsay” is too narrow.", "oxford-grammar", "oxford-grammar"), example: "Ali gelmiş.", exampleTranslation: "Apparently Ali came / I see that Ali has come." },
      { title: "Ability and inability sit inside the verb", body: cited("The productive ability form uses -(y)Abil-. Its negative is not built by mechanically adding ordinary negation after ability; yapabilirim means “I can do it,” while yapamam means “I cannot do it.” Discover Discomfort treats these as usable conversational patterns.", "dd-can"), example: "Türkçe okuyabiliyorum ama hızlı konuşamıyorum.", exampleTranslation: "I can read Turkish, but I cannot speak quickly." },
      { title: "Obligation has several strengths", body: cited("The suffix -malı/-meli can express should or must; zorunda olmak conveys being obliged, and gerek/lazım can express necessity. Relationship and situation determine whether a form sounds like advice, inference, rule, or pressure.", "dd-must"), example: "Yarın erken kalkmam lazım.", exampleTranslation: "I need to get up early tomorrow." },
      { title: "Relative clauses come before nouns", body: cited("Turkish participles package a clause as a modifier. In geldiğim şehir “the city I came to,” the possessive-looking ending helps identify the embedded participant. Learn these as full noun phrases, because English word-for-word order obscures their logic.", "oxford-grammar", "oxford-grammar"), example: "Dün tanıştığımız öğretmen burada çalışıyor.", exampleTranslation: "The teacher whom we met yesterday works here." },
      { title: "Questions use a separate harmonic particle", body: cited("Yes/no questions use mı/mi/mu/mü, written separately. Person marking may attach to the particle, while question words such as ne “what” do not require it.", "tdk-dictionary", "dd-grammar"), example: "Hazır mısınız?", exampleTranslation: "Are you ready? (polite or plural)" }
    ]
  },
  whereSpoken: {
    overview: cited("Turkish is centered in Türkiye but has never been bounded neatly by the republic's borders. It is an official language in the Republic of Cyprus and is used by Turkish Cypriots; longstanding communities live across the Balkans, while labor migration and family networks created major German, Dutch, Austrian, Belgian, French, and Nordic communities. Turkish media travels through satellite television, streaming, music, football, and social platforms. Speaker totals vary with whether censuses record mother tongue, home use, heritage competence, or ethnicity, so this guide avoids presenting one unstable headline number as exact.", "wiki-turkish", "glottolog"),
    regions: [
      { place: "Türkiye", note: cited("The nationwide standard coexists with regional Turkish and with Kurdish, Arabic, Zaza, Laz, Armenian, Greek, Circassian languages, and many migrant languages. A city label alone does not describe a speaker's repertoire.", "wiki-turkish") },
      { place: "Cyprus and the eastern Mediterranean", note: cited("Turkish Cypriot speech has local histories and features alongside access to standard Turkish. Political terminology and place names can be sensitive; follow speakers' own usage and distinguish linguistic description from territorial claims.", "wiki-turkish") },
      { place: "Balkans", note: cited("Communities in Bulgaria, Greece, North Macedonia, Kosovo, Romania, and elsewhere maintain varied forms of Turkish shaped by education, mobility, and neighboring languages.", "wiki-turkish") },
      { place: "Western Europe", note: cited("Germany hosts the largest diaspora concentration, but Turkish is also visible across the Netherlands, Austria, Belgium, France, Scandinavia, Switzerland, and the United Kingdom. Heritage speakers may move fluidly between Turkish and a national language.", "wiki-turkish") }
    ]
  },
  difficulty: {
    label: "Moderate",
    overview: cited("Turkish is not difficult for one single reason. For English speakers, transparent spelling and regular suffixes provide quick wins, while unfamiliar sentence architecture produces a later climb. Discover Discomfort's assessment usefully separates pronunciation and regular morphology from listening, long compounds, subordinate clauses, and vocabulary distance. No official hour count predicts an individual: experience with another suffixing or head-final language, heritage exposure, and daily contact matter more than a universal ranking.", "dd-hard", "dd-grammar"),
    easierAspects: ["Highly consistent modern spelling", "Regular suffix families and few irregular verb paradigms", "No grammatical gender or noun classes", "Abundant television, music, tutors, dictionaries, and learner media", "Subjects can be omitted once verb endings are familiar"],
    hardAspects: ["Hearing vowel harmony and suffix boundaries at conversational speed", "Case selection with individual verbs", "Participles and nominalizations in long sentences", "Vocabulary layers across casual, formal, and older registers", "Pragmatic meanings of word order and evidential forms"],
    plateauRisks: ["Admiring suffix logic without doing enough listening", "Reading every sentence in English order before finding the final verb", "Treating -miş as a single mechanical hearsay tense", "Avoiding Turkish-only dictionaries and remaining dependent on one-word translations"],
    workload: cited("A useful week combines short daily listening, three focused grammar sessions, two conversations, and one longer reading. Segment five real sentences rather than generating monstrous words for fun. Recycle the same scene: watch with Turkish subtitles, collect five chunks, shadow them, then explain the scene aloud. Early travel competence may come in months; comfortable novels, comedy, and fast group conversation require sustained years. The regular system reduces confusion, not the amount of language you must meet.", "dd-hard", "dd-reasons")
  },
  advancedLearning: {
    strategy: cited("Move from suffix recognition to clause recognition. For each new participle or nominalizer, save a complete sentence and mark who did what. Retell one news item in casual Turkish, then compare it with the written article to expose register. Ask a tutor to correct information structure and collocations, not only endings. Discover Discomfort's grammar series works best as a readable second explanation beside a systematic course, especially when harmony or modality feels abstract.", "dd-grammar", "dd-vowels", "dd-must"),
    mediaPractice: cited("Turkish television offers huge quantities of dialogue, but long subtitled dramas can become passive entertainment. Work from two-minute scenes and notice address forms, sentence-final particles, and what subtitles compress. Alternate scripted drama with interviews, radio, comedy, and regional speakers. Songs are excellent for formulaic language but may bend stress or preserve poetic vocabulary. Keep one Turkish-only media habit whose subject you already love—football analysis, cooking, history, games, or design.", "dd-reasons", "dd-phrases") ,
    dictionariesAndCorpora: cited("The TDK online dictionary combines current definitions, pronunciation, idioms, proverbs, dialect material, and etymological resources. Use it to check spelling and sense, then search the Turkish National Corpus for register and collocation when access permits. A bilingual dictionary gets you to a candidate; a monolingual definition and several authentic sentences tell you whether that candidate belongs in a message, an essay, or an Ottoman-flavored joke.", "tdk-dictionary", "tnc"),
    resources: [
      { type: "other", title: "Discover Discomfort: Turkish Grammar Overview", url: "https://discoverdiscomfort.com/turkish-grammar-overview-for-learners/", level: "beginner", description: cited("A learner-oriented map of agglutination, harmony, cases, and word order, with links to focused lessons.", "dd-grammar") },
      { type: "other", title: "Discover Discomfort: Turkish Vowel Harmony", url: "https://discoverdiscomfort.com/turkish-vowel-harmony/", level: "beginner", description: cited("A practical explanation of two-way and four-way harmony through common suffixes and examples.", "dd-vowels") },
      { type: "dictionary", title: "Türk Dil Kurumu Dictionaries", url: "https://sozluk.gov.tr/", level: "all", description: cited("The official portal for current Turkish definitions plus idiom, proverb, dialect, etymological, and specialist dictionaries.", "tdk-dictionary") },
      { type: "corpus", title: "Turkish National Corpus", url: "https://www.tnc.org.tr/", level: "advanced", description: cited("A balanced reference corpus for testing frequency, collocation, and genre beyond intuition or isolated web hits.", "tnc") },
      { type: "book", title: "The Oxford Turkish Grammar", url: "https://global.oup.com/academic/product/the-oxford-turkish-grammar-9780198851509", level: "advanced", description: cited("Gerjan van Schaaik's detailed modern reference for morphology, syntax, and the edge cases compact learner summaries omit.", "oxford-grammar") }
    ]
  },
  wordsAndTexts: {
    overview: cited("Turkish becomes socially vivid in small formulas that rarely map onto a single English line. Kolay gelsin recognizes someone at work; eline sağlık praises the hands that cooked or made something; geçmiş olsun wishes that illness or trouble pass. These phrases are not ornamental politeness. They locate the speaker inside a moment of labor, hospitality, recovery, arrival, or departure. Vocabulary also preserves reform-era doublets: an older Arabic-origin term and a newer Turkish-derived form may differ in register rather than meaning exactly the same thing.", "dd-miss", "dd-phrases", "tdk-dictionary"),
    notableWords: [
      { term: "gönül", meaning: "heart, inner feeling, willing affection", note: cited("More inward and relational than the anatomical kalp, it appears constantly in songs, poetry, compounds, and idioms; translations vary with context.", "tdk-dictionary") },
      { term: "yakamoz", meaning: "shimmer on water, especially moonlight", note: cited("Often romanticized as untranslatable, but best learned through Turkish definitions and real descriptions rather than a viral one-word gloss.", "tdk-dictionary") },
      { term: "imece", meaning: "collective voluntary work", note: cited("Traditionally associated with neighbors pooling labor for a shared task; modern writers also use it metaphorically for collaborative efforts.", "tdk-dictionary") },
      { term: "hüzün", meaning: "sadness; melancholy", note: cited("An Arabic-origin everyday word with literary and cultural resonances. Context decides whether it is ordinary sadness or a cultivated collective mood.", "tdk-dictionary") },
      { term: "kısmet", meaning: "destined share; fortune; what is meant to be", note: cited("Used seriously, lightly, or resignedly around opportunities and relationships; it is not always a declaration of fixed fatalism.", "tdk-dictionary") },
      { term: "gurbet", meaning: "life away from home; a foreign place", note: cited("Especially resonant in migration songs and diaspora speech, where it can name distance, longing, and the social condition of being away.", "tdk-dictionary") },
      { term: "merak", meaning: "curiosity; interest; worry", note: cited("Merak etmek can mean to wonder or to worry, which makes the surrounding object and context essential.", "tdk-dictionary") }
    ],
    loanwordLayers: cited("Basic verbs, kin terms, body words, and suffixes display the Turkic core, while Arabic and Persian layers remain pervasive in religion, abstraction, administration, and literature. French loans such as gar “station” and kuaför “hairdresser” evoke modernization, and contemporary English enters technology and corporate speech. Reform created alternatives such as olanak beside imkân “possibility”; speakers may hear differences of generation, ideology, rhythm, or collocation. Avoid counting origins as a measure of authenticity. Once borrowed, a word participates in Turkish harmony, derivation, humor, and social history.", "wiki-turkish", "tdk-dictionary"),
    idioms: [
      { original: "Etekleri zil çalmak", translation: "To be overjoyed", note: "Literally, for one's skirts to ring like bells: a vivid idiom for barely contained happiness." },
      { original: "Pabucu dama atılmak", translation: "To be displaced by a newer favorite", note: "Literally, for one's shoe to be thrown onto the roof; used when a person or thing loses attention to a replacement." },
      { original: "İğneyle kuyu kazmak", translation: "To undertake painfully slow, exacting work", note: "Literally, to dig a well with a needle—good for research, bureaucracy, or any task whose tool seems absurdly small." },
      { original: "Dereyi görmeden paçaları sıvamak", translation: "To prepare prematurely", note: "Literally, to roll up one's trouser legs before seeing the stream; warns against acting on an obstacle that has not appeared." },
      { original: "Bir taşla iki kuş vurmak", translation: "To achieve two goals with one action", note: "Literally, to hit two birds with one stone; close in imagery and use to the English idiom." }
    ],
    textGenres: ["Ottoman divan poetry and prose, requiring historical language and script", "Folk poetry, aşık performance, türkü songs, and oral narrative", "Modern novels, short stories, memoirs, essays, and graphic narratives", "Newspaper columns and long-form political or cultural commentary", "Television drama, cinema, stand-up, podcasts, and pop or alternative music", "Diaspora literature and multilingual digital culture"]
  },
  relationships: { overview: cited("Turkish's closest relatives are other Turkic languages, not Arabic or Persian. Azerbaijani, Turkmen, and Gagauz belong with it in Oghuz; more distant relatives such as Uzbek, Kazakh, Kyrgyz, Uyghur, Tatar, and Sakha share pieces of grammar and vocabulary without automatic mutual intelligibility. Arabic, Persian, Greek, Armenian, Kurdish, French, and Balkan languages belong to other families but have deep contact relationships. Separating genealogy from borrowing makes both stories more interesting.", "glottolog", "wiki-turkish"), languages: relatedLanguages },
  culturalNotes: "Turkish is spoken by people with varied ethnicities, religions, politics, and relationships to the Turkish state. Do not treat one Istanbul television register as the voice of everyone in Türkiye, or assume a Turkish speaker cannot also be a native Kurdish, Arabic, Armenian, Greek, or German speaker. Forms of address matter: sen is singular and familiar, siz plural or polite, and titles such as hocam, abi, abla, bey, and hanım carry relationships that dictionary English flattens. Türkiye is the country's official English short name in many international contexts, while “Turkey” remains common English usage; quote people and institutions accurately rather than turning naming into a language test.",
  resources: [
    { type: "other", title: "Discover Discomfort Turkish Grammar Series", url: "https://discoverdiscomfort.com/turkish-grammar-overview-for-learners/", level: "all", description: cited("A hub for accessible articles on harmony, ability, obligation, and the points learners actually ask about.", "dd-grammar") },
    { type: "other", title: "Discover Discomfort Everyday Turkish Phrases", url: "https://discoverdiscomfort.com/turkish-phrases-everyday/", level: "beginner", description: cited("Context-rich everyday expressions that move beyond transactional phrasebook lines.", "dd-phrases") },
    { type: "other", title: "Discover Discomfort: How Hard Is Turkish?", url: "https://discoverdiscomfort.com/how-hard-is-turkish/", level: "beginner", description: cited("A candid learner's account separating easy orthography from later grammar and listening demands.", "dd-hard") },
    { type: "dictionary", title: "TDK Online Dictionaries", url: "https://sozluk.gov.tr/", level: "all", description: cited("Current definitions, audio, spelling, proverbs, idioms, dialect vocabulary, and etymological tools in Turkish.", "tdk-dictionary") },
    { type: "corpus", title: "Turkish National Corpus", url: "https://www.tnc.org.tr/", level: "advanced", description: cited("Search authentic written and spoken contexts to check collocations and register.", "tnc") },
    { type: "book", title: "The Oxford Turkish Grammar", url: "https://global.oup.com/academic/product/the-oxford-turkish-grammar-9780198851509", level: "advanced", description: cited("A comprehensive contemporary reference for questions that survive introductory courses.", "oxford-grammar") }
  ],
  relatedLanguages,
  phrases: [
    { original: "Merhaba", translation: "Hello.", usageNote: "Neutral and broadly usable." },
    { original: "Günaydın", translation: "Good morning.", literalMeaning: "May the day be bright.", usageNote: "Used through the morning in homes, shops, and workplaces." },
    { original: "Nasılsınız?", translation: "How are you?", usageNote: "Polite or plural; Nasılsın? is singular and familiar." },
    { original: "Teşekkür ederim", translation: "Thank you.", usageNote: "Teşekkürler is a common shorter alternative." },
    { original: "Rica ederim", translation: "You're welcome.", literalMeaning: "I request/ask it.", usageNote: "A conventional response to thanks." },
    { original: "Affedersiniz", translation: "Excuse me; pardon me.", usageNote: "Useful for getting attention or apologizing politely." },
    { original: "Türkçe öğreniyorum", translation: "I am learning Turkish." },
    { original: "Biraz daha yavaş konuşabilir misiniz?", translation: "Could you speak a little more slowly?", usageNote: "Polite; notice the ability and question morphology." },
    { original: "Bu ne demek?", translation: "What does this mean?" },
    { original: "Ne kadar?", translation: "How much?", usageNote: "Also means “how much/how many” more generally." },
    { original: "Kolay gelsin", translation: "May your work come easily.", usageNote: "Said to someone working, when arriving, passing, or leaving; there is no single English equivalent." },
    { original: "Elinize sağlık", translation: "Thank you for making/cooking this.", literalMeaning: "Health to your hands.", usageNote: "Polite or plural; eline sağlık is familiar singular." },
    { original: "Geçmiş olsun", translation: "Get well soon; may the trouble be behind you.", usageNote: "Used after illness, an accident, or another unpleasant event." },
    { original: "Görüşürüz", translation: "See you.", literalMeaning: "We will see one another." }
  ],
  sources: [
    { id: "dd-grammar", title: "Turkish Grammar — The Main Features for Learners", url: "https://discoverdiscomfort.com/turkish-grammar-overview-for-learners/", publisher: "Discover Discomfort", publishedAt: "2023-08-14", updatedAt: "2023-09-14", accessedAt: "2026-07-10" },
    { id: "dd-vowels", title: "Turkish Vowel Harmony Explained Simply", url: "https://discoverdiscomfort.com/turkish-vowel-harmony/", publisher: "Discover Discomfort", publishedAt: "2023-09-01", updatedAt: "2023-09-14", accessedAt: "2026-07-10" },
    { id: "dd-consonants", title: "Turkish Consonant Harmony", url: "https://discoverdiscomfort.com/turkish-consonant-harmony/", publisher: "Discover Discomfort", publishedAt: "2023-09-14", accessedAt: "2026-07-10" },
    { id: "dd-e", title: "How to Pronounce E in Turkish", url: "https://discoverdiscomfort.com/how-to-pronounce-e-in-turkish/", publisher: "Discover Discomfort", publishedAt: "2023-10-24", accessedAt: "2026-07-10" },
    { id: "dd-can", title: "How to Say Can or Cannot in Turkish", url: "https://discoverdiscomfort.com/can-or-cannot-in-turkish/", publisher: "Discover Discomfort", publishedAt: "2023-09-30", accessedAt: "2026-07-10" },
    { id: "dd-must", title: "Should, Must, and Have To in Turkish", url: "https://discoverdiscomfort.com/should-must-have-to-in-turkish/", publisher: "Discover Discomfort", publishedAt: "2023-09-19", accessedAt: "2026-07-10" },
    { id: "dd-phrases", title: "Turkish Words and Phrases for Everyday Life", url: "https://discoverdiscomfort.com/turkish-phrases-everyday/", publisher: "Discover Discomfort", publishedAt: "2023-09-10", updatedAt: "2024-08-25", accessedAt: "2026-07-10" },
    { id: "dd-miss", title: "The Turkish Phrases I'll Most Miss from Türkiye", url: "https://discoverdiscomfort.com/turkish-phrases-ill-miss/", publisher: "Discover Discomfort", publishedAt: "2024-01-30", accessedAt: "2026-07-10" },
    { id: "dd-hard", title: "How Hard Is Turkish?", url: "https://discoverdiscomfort.com/how-hard-is-turkish/", publisher: "Discover Discomfort", publishedAt: "2023-09-08", updatedAt: "2023-09-14", accessedAt: "2026-07-10" },
    { id: "dd-reasons", title: "Why Learn Turkish?", url: "https://discoverdiscomfort.com/learn-turkish-reasons/", publisher: "Discover Discomfort", publishedAt: "2023-09-27", accessedAt: "2026-07-10" },
    { id: "wiki-turkish", title: "Turkish language", url: "https://en.wikipedia.org/wiki/Turkish_language", publisher: "Wikipedia", accessedAt: "2026-07-10" },
    { id: "tdk-dictionary", title: "Türk Dil Kurumu Sözlükleri", url: "https://sozluk.gov.tr/", publisher: "Türk Dil Kurumu", accessedAt: "2026-07-10" },
    { id: "glottolog", title: "Glottolog: Turkish", url: "https://glottolog.org/resource/languoid/id/nucl1301", publisher: "Glottolog", accessedAt: "2026-07-10" },
    { id: "unicode-latin", title: "The Unicode Standard, Latin", url: "https://www.unicode.org/versions/Unicode17.0.0/core-spec/chapter-7/", publisher: "Unicode Consortium", updatedAt: "2025", accessedAt: "2026-07-10" },
    { id: "tnc", title: "Turkish National Corpus", url: "https://www.tnc.org.tr/", publisher: "Mersin University", accessedAt: "2026-07-10" },
    { id: "oxford-grammar", title: "The Oxford Turkish Grammar", url: "https://global.oup.com/academic/product/the-oxford-turkish-grammar-9780198851509", publisher: "Oxford University Press", publishedAt: "2020", accessedAt: "2026-07-10" }
  ],
  seo: { title: "Turkish Language Guide: Grammar, History, Phrases and Culture", description: "An accessible, deeply researched guide to Turkish vowel harmony, suffixes, evidentiality, alphabet reform, regional usage, practical phrases, culture, and modern learning resources." }
} satisfies LanguageGuide;
